name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: npm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - shell: bash
      run: npm install --ci
