import type { MassMap } from "../../domain";

export const SANCTI_01: MassMap = {
  SANCTI_01_01: {
    flexibility: "santos",
    id: "SANCTI_01_01",
    name: "Circuncisão do Senhor e Oitava do Natal",
    rank: 1,
    color: "w",
    link: "missal/santos/01-01",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 1,
  },
  SANCTI_01_02: {
    flexibility: "santos",
    id: "SANCTI_01_02",
    name: "Oitava de S. Estevão, Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/01-02",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 2,
  },
  SANCTI_01_03: {
    flexibility: "santos",
    id: "SANCTI_01_03",
    name: "Oitava de S. João, Apóstolo e Evangelista",
    rank: 3,
    color: "w",
    link: "missal/santos/01-03",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 3,
  },
  SANCTI_01_04: {
    flexibility: "santos",
    id: "SANCTI_01_04",
    name: "Oitava dos Santos Inocentes",
    rank: 3,
    color: "r",
    link: "missal/santos/01-04",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 4,
  },
  SANCTI_01_05: {
    flexibility: "santos",
    id: "SANCTI_01_05",
    name: "Vigília Epifania",
    rank: 2,
    color: "w",
    link: "missal/santos/01-05",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 5,
  },
  SANCTI_01_06: {
    flexibility: "santos",
    id: "SANCTI_01_06",
    name: "Epifania do Senhor",
    rank: 1,
    color: "w",
    link: "missal/santos/01-06",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 6,
  },
  // Die Segundo infra Octavam Epiphaniae - Semiduplex 5.6 pre-55;
  // Rubrics 1960 reduce them to ferias (our post-Epiphany tempora cover those).
  SANCTI_01_07: {
    flexibility: "santos",
    id: "SANCTI_01_07",
    name: "Segundo dia dentro da Oitava da Epifania",
    rank: 2,
    color: "w",
    link: "missal/santos/01-06",
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5.6 },
      { rubrics: "Rubrics 1960 - 1960", name: "Feria", precedence: 1.2 },
    ],
    type: "sancti",
    category: "santos",
    month: 1,
    day: 7,
  },
  // Die Terceiro infra Octavam Epiphaniae - Semiduplex 5.6 pre-55;
  // Rubrics 1960 reduce them to ferias (our post-Epiphany tempora cover those).
  SANCTI_01_08: {
    flexibility: "santos",
    id: "SANCTI_01_08",
    name: "Terceiro dia dentro da Oitava da Epifania",
    rank: 2,
    color: "w",
    link: "missal/santos/01-06",
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5.6 },
      { rubrics: "Rubrics 1960 - 1960", name: "Feria", precedence: 1.2 },
    ],
    type: "sancti",
    category: "santos",
    month: 1,
    day: 8,
  },
  // Die Quarto infra Octavam Epiphaniae - Semiduplex 5.6 pre-55;
  // Rubrics 1960 reduce them to ferias (our post-Epiphany tempora cover those).
  SANCTI_01_09: {
    flexibility: "santos",
    id: "SANCTI_01_09",
    name: "Quarto dia dentro da Oitava da Epifania",
    rank: 2,
    color: "w",
    link: "missal/santos/01-06",
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5.6 },
      { rubrics: "Rubrics 1960 - 1960", name: "Feria", precedence: 1.2 },
    ],
    type: "sancti",
    category: "santos",
    month: 1,
    day: 9,
  },
  // Die Quinto infra Octavam Epiphaniae - Semiduplex 5.6 pre-55;
  // Rubrics 1960 reduce them to ferias (our post-Epiphany tempora cover those).
  SANCTI_01_10: {
    flexibility: "santos",
    id: "SANCTI_01_10",
    name: "Quinto dia dentro da Oitava da Epifania",
    rank: 2,
    color: "w",
    link: "missal/santos/01-06",
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5.6 },
      { rubrics: "Rubrics 1960 - 1960", name: "Feria", precedence: 1.2 },
    ],
    type: "sancti",
    category: "santos",
    month: 1,
    day: 10,
  },
  // Die Sexto infra Octavam Epiphaniae - Semiduplex 5.6 pre-55;
  // Rubrics 1960 reduce them to ferias (our post-Epiphany tempora cover those).
  SANCTI_01_11: {
    flexibility: "santos",
    id: "SANCTI_01_11",
    name: "Sexto dia dentro da Oitava da Epifania",
    rank: 2,
    color: "w",
    link: "missal/santos/01-06",
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5.6 },
      { rubrics: "Rubrics 1960 - 1960", name: "Feria", precedence: 1.2 },
    ],
    type: "sancti",
    category: "santos",
    month: 1,
    day: 11,
  },
  // Die Sétimo infra Octavam Epiphaniae - Semiduplex 5.6 pre-55;
  // Rubrics 1960 reduce them to ferias (our post-Epiphany tempora cover those).
  SANCTI_01_12: {
    flexibility: "santos",
    id: "SANCTI_01_12",
    name: "Sétimo dia dentro da Oitava da Epifania",
    rank: 2,
    color: "w",
    link: "missal/santos/01-06",
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5.6 },
      { rubrics: "Rubrics 1960 - 1960", name: "Feria", precedence: 1.2 },
    ],
    type: "sancti",
    category: "santos",
    month: 1,
    day: 12,
  },
  SANCTI_01_13: {
    flexibility: "santos",
    id: "SANCTI_01_13",
    name: "Comemoração do Baptismo do Senhor",
    rank: 2,
    color: "w",
    link: "missal/santos/01-13",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 13,
    rankVariants: [
      { rubrics: "*", name: "Duplex majus", precedence: 4 },
      { rubrics: "Rubrics 1960 - 1960", name: "Duplex II. classis", precedence: 5 },
    ],
  },
  SANCTI_01_14: {
    flexibility: "santos",
    id: "SANCTI_01_14",
    name: "S. Hilário, Bispo Confessor e Doutor",
    rank: 3,
    color: "w",
    link: "missal/santos/01-14",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 14,
  },
  SANCTI_01_14_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_01_14_OUTRO",
    name: "S. Félix, Presb. e Márt.",
    rank: 4,
    color: "r",
    link: "missal/santos/01-14-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 1,
    day: 14,
  },
  SANCTI_01_15: {
    flexibility: "santos",
    id: "SANCTI_01_15",
    name: "S. Paulo, 1.º Eremita, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/01-15",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 15,
  },
  SANCTI_01_15_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_01_15_OUTRO",
    name: "S. Amaro, Abade",
    rank: 4,
    color: "w",
    link: "missal/santos/01-15-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 1,
    day: 15,
  },
  SANCTI_01_16: {
    flexibility: "santos",
    id: "SANCTI_01_16",
    name: "S. Marcelo, Papa e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/01-16",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 16,
  },
  SANCTI_01_16_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_01_16_PORTUGAL",
    name: "Os Santos Mártires de Marrocos",
    rank: 3,
    color: "r",
    link: "missal/santos/01-16-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 1,
    day: 16,
  },
  SANCTI_01_17: {
    flexibility: "santos",
    id: "SANCTI_01_17",
    name: "S. António, Abade",
    rank: 3,
    color: "w",
    link: "missal/santos/01-17",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 17,
  },
  SANCTI_01_18: {
    flexibility: "santos",
    id: "SANCTI_01_18",
    name: "Cadeira de S. Pedro em Roma",
    rank: 4,
    color: "w",
    link: "missal/santos/01-18",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 18,
      suppressedIn: ["62"],
},
  SANCTI_01_18_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_01_18_OUTRO",
    name: "Santa Prisca, Virgem e Mártir",
    rank: 4,
    color: "r",
    link: "missal/santos/01-18-outro",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 18,
  },
  SANCTI_01_19_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_01_19_PORTUGAL",
    name: "S. Gonçalo de Amarante, Confessor",
    rank: 4,
    color: "r",
    link: "missal/santos/01-19-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 1,
    day: 19,
  },
  SANCTI_01_20: {
    flexibility: "santos",
    id: "SANCTI_01_20",
    name: "S.S. Fabião, Papa e Sebastião, Mártires",
    rank: 3,
    color: "r",
    link: "missal/santos/01-20",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 20,
  },
  SANCTI_01_21: {
    flexibility: "santos",
    id: "SANCTI_01_21",
    name: "S. Inês, Virgem e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/01-21",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 21,
  },
  SANCTI_01_22: {
    flexibility: "santos",
    id: "SANCTI_01_22",
    name: "S.S. Vicente e Anastácio, Mártires",
    rank: 3,
    color: "r",
    link: "missal/santos/01-22",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 22,
  },
  SANCTI_01_22_LISBOA_FARO: {
    flexibility: "santos",
    id: "SANCTI_01_22_LISBOA_FARO",
    name: "S. Vicente, Mártires",
    rank: 3,
    color: "r",
    link: "missal/santos/01-22-lisboa-faro",
    type: "sancti",
    local: "lisboa-faro",
    category: "santos",
    month: 1,
    day: 22,
  },
  SANCTI_01_23: {
    flexibility: "santos",
    id: "SANCTI_01_23",
    name: "S. Raimundo de Penhafort, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/01-23",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 23,
  },
  SANCTI_01_23_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_01_23_OUTRO",
    name: "Santa Emerenciana, Virgem e Márt.",
    rank: 4,
    color: "w",
    link: "missal/santos/01-23-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 1,
    day: 23,
  },
  SANCTI_01_24: {
    flexibility: "santos",
    id: "SANCTI_01_24",
    name: "S. Timóteo, Bispo e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/01-24",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 24,
  },
  SANCTI_01_25: {
    flexibility: "santos",
    id: "SANCTI_01_25",
    name: "Conversão S. Paulo, Apóstolo",
    rank: 3,
    color: "w",
    link: "missal/santos/01-25",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 25,
  },
  SANCTI_01_26: {
    flexibility: "santos",
    id: "SANCTI_01_26",
    name: "S. Policarpo, Bispo e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/01-26",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 26,
  },
  SANCTI_01_27: {
    flexibility: "santos",
    id: "SANCTI_01_27",
    name: "S. João Crisóstomo, Confessor, Bispo e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/01-27",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 27,
  },
  SANCTI_01_27_LAMEGO: {
    flexibility: "santos",
    id: "SANCTI_01_27_LAMEGO",
    name: "Oitava de S. Sebastião, Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/01-27-lamego",
    type: "sancti",
    local: "lamego",
    category: "santos",
    month: 1,
    day: 27,
  },
  SANCTI_01_28: {
    flexibility: "santos",
    id: "SANCTI_01_28",
    name: "S. Pedro Nolasco, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/01-28",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 28,
  },
  SANCTI_01_28_LISBOA_FARO: {
    flexibility: "santos",
    id: "SANCTI_01_28_LISBOA_FARO",
    name: "Sétimo dia dentro da Oitava de S. Vicente, Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/01-28-lisboa-faro",
    type: "sancti",
    local: "lisboa-faro",
    category: "santos",
    month: 1,
    day: 28,
  },
  SANCTI_01_29: {
    flexibility: "santos",
    id: "SANCTI_01_29",
    name: "S. Francisco de Sales, Bispo, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/01-29",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 29,
  },
  SANCTI_01_29_LISBOA_FARO: {
    flexibility: "santos",
    id: "SANCTI_01_29_LISBOA_FARO",
    name: "Oitava de S. Vicente, Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/01-29-lisboa-faro",
    type: "sancti",
    local: "lisboa-faro",
    category: "santos",
    month: 1,
    day: 29,
  },
  SANCTI_01_30: {
    flexibility: "santos",
    id: "SANCTI_01_30",
    name: "S. Martinha, Virgem e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/01-30",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 30,
  },
  SANCTI_01_31: {
    flexibility: "santos",
    id: "SANCTI_01_31",
    name: "S. João Bosco, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/01-31",
    type: "sancti",
    category: "santos",
    month: 1,
    day: 31,
  },
};
