import type { MassMap } from "../../domain";

export const SANCTI_02: MassMap = {
  SANCTI_02_01: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_01",
    name: "S. Inácio, Bispo e Mártir",
    color: "r",
    link: "missal/santos/02-01",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 1,
  },
  SANCTI_02_02: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex II classis", precedence: 5 },
     ],
    id: "SANCTI_02_02",
    name: "Purificação da B. V. Maria",
    color: "w",
    link: "missal/santos/02-02",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 2,
  },
  SANCTI_02_03: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_02_03",
    name: "S. Brás, Bispo e Mártir",
    color: "r",
    link: "missal/santos/02-03",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 3,
  },
  SANCTI_02_04: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_04",
    name: "S. André Corsino, Bispo e Confessor",
    color: "w",
    link: "missal/santos/02-04",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 4,
  },
  SANCTI_02_04_PORTUGAL: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_04_PORTUGAL",
    name: "Beato João de Brito, Mártir",
    color: "r",
    link: "missal/santos/02-04-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 2,
    day: 4,
  },
  SANCTI_02_05: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_05",
    name: "S. Águeda, Virgem e Mártir",
    color: "r",
    link: "missal/santos/02-05",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 5,
  },
  SANCTI_02_06: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_06",
    name: "S. Tito, Bispo e Confessor",
    color: "w",
    link: "missal/santos/02-06",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 6,
  },
  SANCTI_02_06_OUTRO: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_02_06_OUTRO",
    name: "Santa Dorotéia, V. e Márt.",
    color: "r",
    link: "missal/santos/02-06-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 2,
    day: 6,
  },
  SANCTI_02_07: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_07",
    name: "S. Romualdo, Abade",
    color: "w",
    link: "missal/santos/02-07",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 7,
  },
  SANCTI_02_08: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_08",
    name: "S. João da Mata, Confessor",
    color: "w",
    link: "missal/santos/02-08",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 8,
  },
  SANCTI_02_09: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_09",
    name: "S. Cirilo de Alexandria, Bispo, Confessor e Doutor da Igreja",
    color: "w",
    link: "missal/santos/02-09",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 9,
  },
  SANCTI_02_09_OUTRO: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_02_09_OUTRO",
    name: "Santa Apolónia, Virgem e Márt.",
    color: "r",
    link: "missal/santos/02-09-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 2,
    day: 9,
  },
  SANCTI_02_10: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_10",
    name: "S. Escolástica",
    color: "w",
    link: "missal/santos/02-10",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 10,
  },
  SANCTI_02_11: {
    flexibility: "santos",
    id: "SANCTI_02_11",
    name: "Aparição de Nossa Senhora, em Lourdes",
    color: "w",
    link: "missal/santos/02-11",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 11,
    rankVariants: [
        { rubrics: "*", name: "Duplex majus", precedence: 4 },
        { rubrics: "R1960", name: "Duplex", precedence: 2.1 },
     ],
  },
  SANCTI_02_12: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_12",
    name: "Os VII Fundadores dos Servitas de B. V. Maria, Confessores",
    color: "w",
    link: "missal/santos/02-12",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 12,
  },
  SANCTI_02_13_PORTUGAL: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_13_PORTUGAL",
    name: "As Cinco Chagas de N. S. Jesus Cristo",
    color: "r",
    link: "missal/santos/02-13-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 2,
    day: 13,
  },
  SANCTI_02_14: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_02_14",
    name: "S. Valentim, Presbítero e Mártir",
    color: "r",
    link: "missal/santos/02-14",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 14,
  },
  SANCTI_02_15: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_02_15",
    name: "S.S. Faustino e Jovita, Mártires",
    color: "r",
    link: "missal/santos/02-15",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 15,
  },
  SANCTI_02_15_PORTUGAL: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_02_15_PORTUGAL",
    name: "Trasladação de S. António de Lisboa",
    color: "w",
    link: "missal/santos/02-15-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 2,
    day: 15,
  },
  SANCTI_02_18: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_02_18",
    name: "S. Simeão, Bispo e Mártir",
    color: "r",
    link: "missal/santos/02-18",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 18,
  },
  SANCTI_02_18_PORTUGAL: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_02_18_PORTUGAL",
    name: "S. Teotónio, Confessor",
    color: "w",
    link: "missal/santos/02-18-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 2,
    day: 18,
  },
  SANCTI_02_22: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex II classis", precedence: 5 },
     ],
    id: "SANCTI_02_22",
    name: "Cadeira S. Pedro em Antióquia",
    color: "w",
    link: "missal/santos/02-22",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 22,
  },
  SANCTI_02_23: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_23",
    name: "S. Pedro Damião, Bispo, Confessor e Doutor da Igreja",
    color: "w",
    link: "missal/santos/02-23",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 23,
  },
  SANCTI_02_24: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex II classis", precedence: 5 },
     ],
    id: "SANCTI_02_24",
    name: "S. Matias, Apóstolo",
    color: "r",
    link: "missal/santos/02-24",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 24,
  },
  SANCTI_02_27: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_27",
    name: "S. Gabriel de Nossa Senhora das Dores",
    color: "w",
    link: "missal/santos/02-27",
    type: "sancti",
    category: "santos",
    month: 2,
    day: 27,
  },
  SANCTI_02_27_PORTUGAL: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_27_PORTUGAL",
    name: "S. Torquato, Bispo e Mártir",
    color: "r",
    link: "missal/santos/02-27-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 2,
    day: 27,
  },
  SANCTI_02_28_PORTUGAL: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_02_28_PORTUGAL",
    name: "Trasladação de S. Agostinho, Bispo, Confessor e Doutor",
    color: "w",
    link: "missal/santos/02-28-coimbra-lamego-leiria",
    type: "sancti",
    local: "coimbra-lamego-leiria",
    category: "santos",
    month: 2,
    day: 28,
  },
};
