import type { MassMap } from "../../domain";

export const SANCTI_03: MassMap = {
  SANCTI_03_01_BRAGA: {
    flexibility: "santos",
    id: "SANCTI_03_01_BRAGA",
    name: "B. Miguel de Carvalho e Outros, Mártires",
    rank: 3,
    color: "r",
    link: "missal/santos/03-01-braga",
    type: "sancti",
    local: "braga",
    category: "santos",
    month: 3,
    day: 1,
  },
  SANCTI_03_04: {
    flexibility: "santos",
    id: "SANCTI_03_04",
    name: "S. Casimiro, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/03-04",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 4,
  },
  SANCTI_03_04_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_03_04_OUTRO",
    name: "S. Lúcio I, Papa e Mártir",
    rank: 4,
    color: "r",
    link: "missal/santos/03-04-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 3,
    day: 4,
  },
  SANCTI_03_06: {
    flexibility: "santos",
    id: "SANCTI_03_06",
    name: "S.S. Perpétua e Felicidade, Mártires",
    rank: 3,
    color: "r",
    link: "missal/santos/03-06",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 6,
  },
  SANCTI_03_07: {
    flexibility: "santos",
    id: "SANCTI_03_07",
    name: "S. Tomás de Aquino, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/03-07",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 7,
  },
  SANCTI_03_08: {
    flexibility: "santos",
    id: "SANCTI_03_08",
    name: "S. João de Deus, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/03-08",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 8,
  },
  SANCTI_03_09: {
    flexibility: "santos",
    id: "SANCTI_03_09",
    name: "S. Francisca Romana, Viúva",
    rank: 3,
    color: "w",
    link: "missal/santos/03-09",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 9,
  },
  SANCTI_03_10: {
    flexibility: "santos",
    id: "SANCTI_03_10",
    name: "S.S. Quarenta Mártires",
    rank: 3,
    color: "r",
    link: "missal/santos/03-10",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 10,
  },
  SANCTI_03_12: {
    flexibility: "santos",
    id: "SANCTI_03_12",
    name: "S. Gregório, Papa, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/03-12",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 12,
  },
  SANCTI_03_13_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_03_13_PORTUGAL",
    name: "B. B. Sancha e Mafalda, Virgens",
    rank: 3,
    color: "w",
    link: "missal/santos/03-13-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 3,
    day: 13,
  },
  SANCTI_03_17: {
    flexibility: "santos",
    id: "SANCTI_03_17",
    name: "S. Patrício, Bispo e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/03-17",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 17,
    rankVariants: [
      { rubrics: "*", name: "Duplex", precedence: 3 },
      { rubrics: "Rubrics 1960 - 1960", name: "Duplex", precedence: 2 },
    ],
  },
  SANCTI_03_18: {
    flexibility: "santos",
    id: "SANCTI_03_18",
    name: "S. Cirilo de Jerusalém, Bispo, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/03-18",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 18,
  },
  SANCTI_03_19: {
    flexibility: "santos",
    id: "SANCTI_03_19",
    name: "S. José, Esposo de Nossa Senhora",
    rank: 1,
    color: "w",
    link: "missal/santos/03-19",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 19,
    novena: true,
    rankVariants: [
      { rubrics: "*", name: "Duplex I classis", precedence: 6.1 },
      { rubrics: "Tridentine - 1570", name: "Duplex", precedence: 3 },
      { rubrics: "Rubrics 1960 - 1960", name: "Duplex I classis", precedence: 6 },
    ],
  },
  SANCTI_03_20_BRAGA: {
    flexibility: "santos",
    id: "SANCTI_03_20_BRAGA",
    name: "S. Martinho de Dume, Bispo e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/03-20-braga",
    type: "sancti",
    local: "braga",
    category: "santos",
    month: 3,
    day: 20,
  },
  SANCTI_03_21: {
    flexibility: "santos",
    id: "SANCTI_03_21",
    name: "S. Bento, Abade",
    rank: 3,
    color: "w",
    link: "missal/santos/03-21",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 21,
  },
  SANCTI_03_24: {
    flexibility: "santos",
    id: "SANCTI_03_24",
    name: "S. Gabriel Arcanjo",
    rank: 3,
    color: "w",
    link: "missal/santos/03-24",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 24,
  },
  SANCTI_03_24_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_03_24_PORTUGAL",
    name: "Festa do Santíssimo Sacramento",
    rank: 3,
    color: "w",
    link: "missal/santos/03-24-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 3,
    day: 24,
  },
  SANCTI_03_25: {
    flexibility: "santos",
    id: "SANCTI_03_25",
    name: "Anunciação de Nossa Senhora",
    rank: 1,
    color: "w",
    link: "missal/santos/03-25",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 25,
    novena: true,
  },
  SANCTI_03_27: {
    flexibility: "santos",
    id: "SANCTI_03_27",
    name: "S. João Damasceno, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/03-27",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 27,
  },
  SANCTI_03_28: {
    flexibility: "santos",
    id: "SANCTI_03_28",
    name: "S. João Capistrano, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/03-28",
    type: "sancti",
    category: "santos",
    month: 3,
    day: 28,
  },
};
