import type { MassMap } from "../../domain";

export const SANCTI_04: MassMap = {
  SANCTI_04_02: {
    flexibility: "santos",
    id: "SANCTI_04_02",
    name: "S. Francisco de Paula, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/04-02",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 2,
  },
  SANCTI_04_04: {
    flexibility: "santos",
    id: "SANCTI_04_04",
    name: "S. Isidoro, Bispo, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/04-04",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 4,
  },
  SANCTI_04_05: {
    flexibility: "santos",
    id: "SANCTI_04_05",
    name: "S. Vicente Ferrer, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/04-05",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 5,
  },
  SANCTI_04_11: {
    flexibility: "santos",
    id: "SANCTI_04_11",
    name: "S. Leão I, Papa, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/04-11",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 11,
  },
  SANCTI_04_13: {
    flexibility: "santos",
    id: "SANCTI_04_13",
    name: "S. Hermenegildo, Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/04-13",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 13,
  },
  SANCTI_04_14: {
    flexibility: "santos",
    id: "SANCTI_04_14",
    name: "S. Justino, Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/04-14",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 14,
  },
  SANCTI_04_16_LISBOA_GUARDA: {
    flexibility: "santos",
    id: "SANCTI_04_16_LISBOA_GUARDA",
    name: "S. Engrácia, Virgem e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/04-16-lisboa-guarda",
    type: "sancti",
    local: "lisboa-guarda",
    category: "santos",
    month: 4,
    day: 16,
  },
  SANCTI_04_16_BRAGA: {
    flexibility: "santos",
    id: "SANCTI_04_16_BRAGA",
    name: "S. Frutuoso, Bispo",
    rank: 3,
    color: "w",
    link: "missal/santos/04-16-braga",
    type: "sancti",
    local: "braga",
    category: "santos",
    month: 4,
    day: 16,
  },
  SANCTI_04_17: {
    flexibility: "santos",
    id: "SANCTI_04_17",
    name: "S. Aniceto, Papa e Mártir",
    rank: 4,
    color: "r",
    link: "missal/santos/04-17",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 17,
  },
  SANCTI_04_21: {
    flexibility: "santos",
    id: "SANCTI_04_21",
    name: "S. Anselmo, Bispo, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/04-21",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 21,
  },
  SANCTI_04_22: {
    flexibility: "santos",
    id: "SANCTI_04_22",
    name: "S.S. Sotero e Caio, Papas e Mártires",
    rank: 3,
    color: "r",
    link: "missal/santos/04-22",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 22,
  },
  SANCTI_04_23: {
    flexibility: "santos",
    id: "SANCTI_04_23",
    name: "S. Jorge, Mártir, Patrono de Portugal",
    rank: 4,
    color: "r",
    link: "missal/santos/04-23",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 23,
    novena: true,
  },
  SANCTI_04_24: {
    flexibility: "santos",
    id: "SANCTI_04_24",
    name: "S. Fiel de Sigmaringen, Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/04-24",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 24,
  },
  SANCTI_04_25: {
    flexibility: "santos",
    id: "SANCTI_04_25",
    name: "S. Marcos, Evangelista",
    rank: 2,
    color: "r",
    link: "missal/santos/04-25",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 25,
  },
  SANCTI_04_26: {
    flexibility: "santos",
    id: "SANCTI_04_26",
    name: "S.S. Cleto e Marcelino, Papas e Mártires",
    rank: 3,
    color: "r",
    link: "missal/santos/04-26",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 26,
  },
  SANCTI_04_26_BRAGA: {
    flexibility: "santos",
    id: "SANCTI_04_26_BRAGA",
    name: "S. Pedro de Rates",
    rank: 3,
    color: "r",
    link: "missal/santos/04-26-braga",
    outro: true,
    type: "sancti",
    category: "santos",
    local: "braga",
    month: 4,
    day: 26,
  },
  SANCTI_04_27: {
    flexibility: "santos",
    id: "SANCTI_04_27",
    name: "S. Pedro Canísio, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/04-27",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 27,
  },
  SANCTI_04_28: {
    flexibility: "santos",
    id: "SANCTI_04_28",
    name: "S. Paulo da Cruz, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/04-28",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 28,
  },
  SANCTI_04_29: {
    flexibility: "santos",
    id: "SANCTI_04_29",
    name: "S. Pedro de Verona, Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/04-29",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 29,
  },
  SANCTI_04_30: {
    flexibility: "santos",
    id: "SANCTI_04_30",
    name: "S. Catarina de Sena, Virgem",
    rank: 3,
    color: "w",
    link: "missal/santos/04-30",
    type: "sancti",
    category: "santos",
    month: 4,
    day: 30,
  },
};
