import type { MassMap } from "../../domain";

export const SANCTI_05: MassMap = {
  SANCTI_05_01: {
    flexibility: "santos",
    id: "SANCTI_05_01",
    name: "S. Filipe e S. Tiago, Apóstolos",
    rank: 2,
    color: "r",
    link: "missal/santos/05-01",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 1,
  },
  SANCTI_05_01_FUNCHAL: {
    flexibility: "santos",
    id: "SANCTI_05_01_FUNCHAL",
    name: "S. Tiago, Apóstolo",
    rank: 2,
    color: "r",
    link: "missal/santos/05-01-funchal",
    type: "sancti",
    local: "funchal",
    category: "santos",
    month: 5,
    day: 1,
  },
  SANCTI_05_02: {
    flexibility: "santos",
    id: "SANCTI_05_02",
    name: "S. Atanásio, Bispo, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/05-02",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 2,
  },
  SANCTI_05_03: {
    flexibility: "santos",
    id: "SANCTI_05_03",
    name: "A Invenção da Santa Cruz",
    rank: 2,
    color: "r",
    link: "missal/santos/05-03",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 3,
      suppressedIn: ["62"],
},
  SANCTI_05_04: {
    flexibility: "santos",
    id: "SANCTI_05_04",
    name: "S. Mónica, Viúva",
    rank: 3,
    color: "w",
    link: "missal/santos/05-04",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 4,
  },
  SANCTI_05_04_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_05_04_PORTUGAL",
    name: "Trasl. das Relíquias de S. Vicente",
    rank: 3,
    color: "w",
    link: "missal/santos/05-04-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 5,
    day: 4,
  },
  SANCTI_05_05: {
    flexibility: "santos",
    id: "SANCTI_05_05",
    name: "S. Pio V, Papa e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/05-05",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 5,
  },
  SANCTI_05_06: {
    flexibility: "santos",
    id: "SANCTI_05_06",
    name: "S. João ante a Porta Latina",
    rank: 3,
    color: "r",
    link: "missal/santos/05-06",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 6,
  },
  SANCTI_05_07: {
    flexibility: "santos",
    id: "SANCTI_05_07",
    name: "S. Estanislau, Bispo e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/05-07",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 7,
  },
  SANCTI_05_08: {
    flexibility: "santos",
    id: "SANCTI_05_08",
    name: "Aparição de S. Miguel, Arcanjo",
    rank: 2,
    color: "w",
    link: "missal/santos/05-08",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 8,
  },
  SANCTI_05_09: {
    flexibility: "santos",
    id: "SANCTI_05_09",
    name: "S. Gregório de Nazianzeno, Bispo, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/05-09",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 9,
  },
  SANCTI_05_10: {
    flexibility: "santos",
    id: "SANCTI_05_10",
    name: "S. Antonino, Bispo e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/05-10",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 10,
  },
  SANCTI_05_12: {
    flexibility: "santos",
    id: "SANCTI_05_12",
    name: "S.S. Nereu, Achileu, Domitila, Virgem e Pancracio, Mártires",
    rank: 3,
    color: "r",
    link: "missal/santos/05-12",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 12,
  },
  SANCTI_05_12_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_05_12_PORTUGAL",
    name: "B. Joana, Princesa",
    rank: 3,
    color: "w",
    link: "missal/santos/05-12-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 5,
    day: 12,
  },
  SANCTI_05_13: {
    flexibility: "santos",
    id: "SANCTI_05_13",
    name: "S. Roberto Belarmino, Bispo, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/05-13",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 13,
  },
  SANCTI_05_13_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_05_13_PORTUGAL",
    name: "Votiva do Imaculado Coração da B. Virgem Maria",
    rank: 3,
    color: "w",
    link: "missal/santos/05-13-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 5,
    day: 13,
    novena: true,
  },
  SANCTI_05_14: {
    flexibility: "santos",
    id: "SANCTI_05_14",
    name: "S. Bonifácio, Mártir",
    rank: 4,
    color: "r",
    link: "missal/santos/05-14",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 14,
  },
  SANCTI_05_14_LISBOA: {
    flexibility: "santos",
    id: "SANCTI_05_14_LISBOA",
    name: "S. Gil, Confessor",
    rank: 4,
    color: "w",
    link: "missal/santos/05-14-lisboa",
    type: "sancti",
    local: "lisboa",
    category: "santos",
    month: 5,
    day: 14,
  },
  SANCTI_05_15: {
    flexibility: "santos",
    id: "SANCTI_05_15",
    name: "S. João Baptista de la Salle, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/05-15",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 15,
  },
  SANCTI_05_15_EVORA: {
    flexibility: "santos",
    id: "SANCTI_05_15_EVORA",
    name: "S. Mâncio, B. e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/05-15-evora",
    type: "sancti",
    local: "evora",
    category: "santos",
    month: 5,
    day: 15,
  },
  SANCTI_05_16: {
    flexibility: "santos",
    id: "SANCTI_05_16",
    name: "S. Ubaldo, Bispo e Confessor",
    rank: 4,
    color: "w",
    link: "missal/santos/05-16",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 16,
  },
  SANCTI_05_17: {
    flexibility: "santos",
    id: "SANCTI_05_17",
    name: "S. Pascoal Bailão, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/05-17",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 17,
  },
  SANCTI_05_18: {
    flexibility: "santos",
    id: "SANCTI_05_18",
    name: "S. Venâncio, Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/05-18",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 18,
  },
  SANCTI_05_19: {
    flexibility: "santos",
    id: "SANCTI_05_19",
    name: "S. Pedro Celestino, Papa e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/05-19",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 19,
  },
  SANCTI_05_20: {
    flexibility: "santos",
    id: "SANCTI_05_20",
    name: "S. Bernardino de Sena, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/05-20",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 20,
  },
  SANCTI_05_22: {
    flexibility: "santos",
    id: "SANCTI_05_22",
    name: "S. Rita de Cássia, Viúva",
    rank: 3,
    color: "w",
    link: "missal/santos/05-22",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 22,
  },
  SANCTI_05_22_BRAGA: {
    flexibility: "santos",
    id: "SANCTI_05_22_BRAGA",
    name: "B. B. João B. Machado e Outros, Ms.",
    rank: 3,
    color: "w",
    link: "missal/santos/05-22-braga",
    type: "sancti",
    local: "braga",
    category: "santos",
    month: 5,
    day: 22,
  },
  SANCTI_05_22_EVORA: {
    flexibility: "santos",
    id: "SANCTI_05_22_EVORA",
    name: "Dedicação da Catedral de Évora",
    rank: 3,
    color: "w",
    link: "missal/santos/05-22-evora",
    type: "sancti",
    local: "evora",
    category: "santos",
    month: 5,
    day: 22,
  },
  SANCTI_05_24: {
    flexibility: "santos",
    id: "SANCTI_05_24",
    name: "B. Virgem Maria, Auxílio dos Cristãos",
    rank: 3,
    color: "w",
    link: "missal/santos/05-24",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 24,
  },
  SANCTI_05_24_BRAGA: {
    flexibility: "santos",
    id: "SANCTI_05_24_BRAGA",
    name: "Trasl. das Rel. de S. Tiago Intercísio",
    rank: 3,
    color: "r",
    link: "missal/santos/05-24-braga",
    type: "sancti",
    local: "braga",
    category: "santos",
    month: 5,
    day: 24,
  },
  SANCTI_05_25: {
    flexibility: "santos",
    id: "SANCTI_05_25",
    name: "S. Gregório VII, Papa e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/05-25",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 25,
  },
  SANCTI_05_26: {
    flexibility: "santos",
    id: "SANCTI_05_26",
    name: "S. Filipe Néri, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/05-26",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 26,
  },
  SANCTI_05_26_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_05_26_OUTRO",
    name: "S. Eleutério, Papa e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/05-26-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    rankVariants: [
      { rubrics: "*", name: "Duplex", precedence: 3.0 },
    ],
    type: "sancti",
    category: "santos",
    month: 5,
    day: 26,
  },
  SANCTI_05_27: {
    flexibility: "santos",
    id: "SANCTI_05_27",
    name: "S. Beda, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/05-27",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 27,
  },
  SANCTI_05_27_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_05_27_OUTRO",
    name: "S. João, Papa e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/05-27-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    rankVariants: [
      { rubrics: "*", name: "Duplex", precedence: 3.0 },
    ],
    type: "sancti",
    category: "santos",
    month: 5,
    day: 27,
  },
  SANCTI_05_28: {
    flexibility: "santos",
    id: "SANCTI_05_28",
    name: "S. Agostinho de Cantuária, Bispo e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/05-28",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 28,
  },
  SANCTI_05_29: {
    flexibility: "santos",
    id: "SANCTI_05_29",
    name: "S. Maria Madalena de Pazzi, Virgem",
    rank: 3,
    color: "w",
    link: "missal/santos/05-29",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 29,
  },
  SANCTI_05_30: {
    flexibility: "santos",
    id: "SANCTI_05_30",
    name: "S. Félix I, Papa e Mártir",
    rank: 4,
    color: "r",
    link: "missal/santos/05-30",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 30,
  },
  SANCTI_05_31: {
    flexibility: "santos",
    id: "SANCTI_05_31",
    name: "Nossa Senhora, Rainha",
    rank: 2,
    color: "w",
    link: "missal/santos/05-31",
    type: "sancti",
    category: "santos",
    month: 5,
    day: 31,
  },
  SANCTI_05_31_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_05_31_PORTUGAL",
    name: "B. V. Maria, Mediadora das Graças",
    rank: 3,
    color: "w",
    link: "missal/santos/05-31-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 5,
    day: 31,
  },
};
