import type { MassMap } from "../../domain";

export const SANCTI_06: MassMap = {
  SANCTI_06_01: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_01",
    name: "Santa Ângela Mericia, Virgem",
    color: "w",
    link: "missal/santos/06-01",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 1,
  },
  SANCTI_06_02: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_06_02",
    name: "S.S. Marcelino e Pedro, Mártires e Erasmo, Bispo",
    color: "r",
    link: "missal/santos/06-02",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 2,
  },
  SANCTI_06_03_ANGOLA: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_06_03_ANGOLA",
    name: "S. S. Carlos Lwanga e Outros, Mártires",
    color: "r",
    link: "missal/santos/06-03-angola",
    type: "sancti",
    local: "angola",
    category: "santos",
    month: 6,
    day: 3,
  },
  SANCTI_06_04: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_04",
    name: "S. Francisco Caraccíolo, Confessor",
    color: "w",
    link: "missal/santos/06-04",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 4,
  },
  SANCTI_06_05: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_05",
    name: "S. Bonifácio, Bispo e Mártir",
    color: "r",
    link: "missal/santos/06-05",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 5,
  },
  SANCTI_06_06: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_06",
    name: "S. Norberto, Bispo e Confessor",
    color: "w",
    link: "missal/santos/06-06",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 6,
  },
  SANCTI_06_09: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_06_09",
    name: "S.S. Primo e Feliciano, Mártires",
    color: "r",
    link: "missal/santos/06-09",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 9,
  },
  SANCTI_06_10: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_10",
    name: "Santa Margarida, Viúva",
    color: "w",
    link: "missal/santos/06-10",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 10,
  },
  SANCTI_06_11: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_11",
    name: "S. Barnabé, Apóstolo",
    color: "r",
    link: "missal/santos/06-11",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 11,
  },
  SANCTI_06_12: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_12",
    name: "S. João de Facundo, Confessor",
    color: "r",
    link: "missal/santos/06-12",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 12,
  },
  SANCTI_06_13: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_13",
    name: "S. António de Lisboa, Confessor e Doutor da Igreja",
    color: "w",
    link: "missal/santos/06-13",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 13,
    novena: true,
  },
  SANCTI_06_14: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_14",
    name: "S. Basílio Magno, Confessor, Bispo e Doutor da Igreja",
    color: "w",
    link: "missal/santos/06-14",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 14,
  },
  SANCTI_06_15: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_15",
    name: "S.S. Vito, Modesto e Crescência, Mártires",
    color: "w",
    link: "missal/santos/06-15",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 15,
  },
  SANCTI_06_17_PORTUGAL: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_17_PORTUGAL",
    name: "Beata Teresa, Princesa de Portugal, Viúva",
    color: "w",
    link: "missal/santos/06-17-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 6,
    day: 17,
  },
  SANCTI_06_18: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_18",
    name: "S. Efrém, Diácono, Confessor e Doutor da Igreja",
    color: "r",
    link: "missal/santos/06-18",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 18,
  },
  SANCTI_06_19: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_19",
    name: "S. Juliana Falconiéri, Virgem",
    color: "r",
    link: "missal/santos/06-19",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 19,
  },
  SANCTI_06_20: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_06_20",
    name: "S. Silvestre, Papa e Mártir",
    color: "r",
    link: "missal/santos/06-20",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 20,
  },
  SANCTI_06_20_PORTUGAL: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Simplex", precedence: 1.5 },
     ],
    id: "SANCTI_06_20_PORTUGAL",
    name: "B. Francisco Pacheco e Outros, Márts.",
    color: "r",
    link: "missal/santos/06-20-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 6,
    day: 20,
  },
  SANCTI_06_21: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_21",
    name: "S. Luís Gonzaga, Confessor",
    color: "w",
    link: "missal/santos/06-21",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 21,
  },
  SANCTI_06_22: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_22",
    name: "S. Paulino, Bispo e Confessor",
    color: "w",
    link: "missal/santos/06-22",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 22,
  },
  SANCTI_06_23: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_23",
    name: "Vigília da Natividade de S. João Baptista",
    color: "v",
    link: "missal/santos/06-23",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 23,
  },
  SANCTI_06_24: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex I classis", precedence: 6.5 },
     ],
    id: "SANCTI_06_24",
    name: "Nascimento de S. João Baptista",
    color: "w",
    link: "missal/santos/06-24",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 24,
    novena: true,
  },
  SANCTI_06_25: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_25",
    name: "S. Guilherme, Abade",
    color: "w",
    link: "missal/santos/06-25",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 25,
  },
  SANCTI_06_26: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_26",
    name: "S.S. João e Paulo, Mártires",
    color: "r",
    link: "missal/santos/06-26",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 26,
  },
  SANCTI_06_27: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_27",
    name: "Terceiro dia na Oitava de São João",
    color: "w",
    link: "missal/santos/06-27",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 27,
  },
  SANCTI_06_26_PORTUGAL: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_26_PORTUGAL",
    name: "S. Pelágio",
    color: "r",
    link: "missal/santos/06-26-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 6,
    day: 26,
  },
  SANCTI_06_28: {
    flexibility: "santos",
    id: "SANCTI_06_28",
    name: "Vigília de S. Pedro e S. Paulo, Apóstolos",
    color: "r",
    link: "missal/santos/06-28",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 28,
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
        { rubrics: "R1960", name: "Duplex II classis", precedence: 5 },
     ],
  },
  SANCTI_06_28_OUTRO: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_28_OUTRO",
    name: "S. Ireneu, B. e Mártir",
    color: "r",
    link: "missal/santos/06-28-outro",
    // Universal Roman calendar under Divino Afflatu; Rubrics 1960 move
    // him to Jul 3rd (see SANCTI_07_03_OUTRO_1962 in the override layer).
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 6,
    day: 28,
  },
  SANCTI_06_29: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex I classis", precedence: 6.5 },
     ],
    id: "SANCTI_06_29",
    name: "S. Pedro e S. Paulo, Apóstolos",
    color: "r",
    link: "missal/santos/06-29",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 29,
    novena: true,
  },
  SANCTI_06_30: {
    flexibility: "santos",
    rankVariants: [
        { rubrics: "*", name: "Duplex", precedence: 3.5 },
     ],
    id: "SANCTI_06_30",
    name: "Comemoração S. Paulo, Apóstolo",
    color: "r",
    link: "missal/santos/06-30",
    type: "sancti",
    category: "santos",
    month: 6,
    day: 30,
  },
};
