import type { MassMap } from "../../domain";

export const SANCTI_07: MassMap = {
  SANCTI_07_01: {
    flexibility: "santos",
    id: "SANCTI_07_01",
    name: "Preciosíssimo Sangue de Nosso Senhor Jesus Cristo",
    rank: 1,
    color: "r",
    link: "missal/santos/07-01",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 1,
    novena: true,
  },
  SANCTI_07_02: {
    flexibility: "santos",
    id: "SANCTI_07_02",
    name: "Visitação de Nossa Senhora",
    rank: 2,
    color: "w",
    link: "missal/santos/07-02",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 2,
  },
  SANCTI_07_03: {
    flexibility: "santos",
    id: "SANCTI_07_03",
    name: "S. Leão II, Papa e Confessor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/07-03",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 3,
    suppressedIn: ["62"],
  },
  SANCTI_07_03_OUTRO_1962: {
    flexibility: "santos",
    id: "SANCTI_07_03_OUTRO_1962",
    name: "S. Ireneu, B. e Mártir",
    rank: 3,
    color: "r",
    calendar: "62",
    link: "missal/santos/06-28-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 7,
    day: 3,
  },
  SANCTI_07_04: {
    flexibility: "santos",
    id: "SANCTI_07_04",
    name: "S. Isabel, Rainha de Portugal e Viúva",
    rank: 3,
    color: "w",
    link: "missal/santos/07-04",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 4,
  },
  SANCTI_07_05: {
    flexibility: "santos",
    id: "SANCTI_07_05",
    name: "S. António Maria Zacarias, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/07-05",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 5,
  },
  SANCTI_07_07: {
    flexibility: "santos",
    id: "SANCTI_07_07",
    name: "S.S. Cirilo e Metódio, Bispos e Confessores",
    rank: 3,
    color: "w",
    link: "missal/santos/07-07",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 7,
  },
  SANCTI_07_10: {
    flexibility: "santos",
    id: "SANCTI_07_10",
    name: "Os Sete Irmãos Mártires e S.S. Rufina e Secunda, Virgens e Mártires",
    rank: 3,
    color: "r",
    link: "missal/santos/07-10",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 10,
  },
  SANCTI_07_11: {
    flexibility: "santos",
    id: "SANCTI_07_11",
    name: "S. Pio I, Papa e Mártir",
    rank: 4,
    color: "r",
    link: "missal/santos/07-11",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 11,
  },
  SANCTI_07_12: {
    flexibility: "santos",
    id: "SANCTI_07_12",
    name: "S. João Gualberto, Abade",
    rank: 3,
    color: "r",
    link: "missal/santos/07-12",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 12,
  },
  SANCTI_07_14: {
    flexibility: "santos",
    id: "SANCTI_07_14",
    name: "S. Boaventura, Bispo, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/07-14",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 14,
  },
  SANCTI_07_15: {
    flexibility: "santos",
    id: "SANCTI_07_15",
    name: "S. Henrique, Imperador e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/07-15",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 15,
  },
  SANCTI_07_15_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_07_15_PORTUGAL",
    name: "B. Inácio de Azevedo e Companheiros",
    rank: 3,
    color: "r",
    link: "missal/santos/07-15-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 7,
    day: 15,
  },
  SANCTI_07_16: {
    flexibility: "santos",
    id: "SANCTI_07_16",
    name: "B. V. Maria do Monte Carmelo",
    rank: 4,
    color: "w",
    link: "missal/santos/07-16",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 16,
  },
  SANCTI_07_16_BEJA: {
    flexibility: "santos",
    id: "SANCTI_07_16_BEJA",
    name: "S. Sisenando, Mártir",
    rank: 4,
    color: "r",
    link: "missal/santos/07-16-beja",
    type: "sancti",
    local: "beja",
    category: "santos",
    month: 7,
    day: 16,
  },
  SANCTI_07_17: {
    flexibility: "santos",
    id: "SANCTI_07_17",
    name: "S. Aleixo, Confessor",
    rank: 4,
    color: "w",
    link: "missal/santos/07-17",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 17,
  },
  SANCTI_07_18: {
    flexibility: "santos",
    id: "SANCTI_07_18",
    name: "S. Camilo de Lelis",
    rank: 3,
    color: "r",
    link: "missal/santos/07-18",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 18,
  },
  SANCTI_07_19: {
    flexibility: "santos",
    id: "SANCTI_07_19",
    name: "S. Vicente de Paulo, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/07-19",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 19,
  },
  SANCTI_07_20: {
    flexibility: "santos",
    id: "SANCTI_07_20",
    name: "S. Jerónimo Emiliano",
    rank: 3,
    color: "w",
    link: "missal/santos/07-20",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 20,
  },
  SANCTI_07_20_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_07_20_OUTRO",
    name: "Santa Margarida, Virgem e Mártir",
    rank: 4,
    color: "r",
    link: "missal/santos/07-20-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 7,
    day: 20,
  },
  SANCTI_07_20_COIMBRA: {
    flexibility: "santos",
    id: "SANCTI_07_20_COIMBRA",
    name: "Santa Colomba, Virgem e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/07-20-coimbra",
    type: "sancti",
    local: "coimbra",
    category: "santos",
    month: 7,
    day: 20,
  },
  SANCTI_07_21: {
    flexibility: "santos",
    id: "SANCTI_07_21",
    name: "S. Praxedes de Brindisi, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/07-21",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 21,
  },
  SANCTI_07_21_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_07_21_PORTUGAL",
    name: "Santo Anjo Custódio de Portugal",
    rank: 3,
    color: "w",
    link: "missal/santos/07-21-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 7,
    day: 21,
  },
  SANCTI_07_22: {
    flexibility: "santos",
    id: "SANCTI_07_22",
    name: "S. Maria Madalena, Penitente",
    rank: 3,
    color: "w",
    link: "missal/santos/07-22",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 22,
  },
  SANCTI_07_22_LISBOA: {
    flexibility: "santos",
    id: "SANCTI_07_22_LISBOA",
    name: "S. Lourenço de Brindes, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/07-22-lisboa",
    type: "sancti",
    local: "lisboa",
    category: "santos",
    month: 7,
    day: 22,
  },
  SANCTI_07_23: {
    flexibility: "santos",
    id: "SANCTI_07_23",
    name: "S. Apolinário, Bispo e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/07-23",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 23,
  },
  SANCTI_07_23_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_07_23_OUTRO",
    name: "S. Libório, Bispo e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/07-23-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 7,
    day: 23,
  },
  SANCTI_07_23_VISEU: {
    flexibility: "santos",
    id: "SANCTI_07_23_VISEU",
    name: "Na Dedicação da Igreja Catedral de Viseu",
    rank: 3,
    color: "w",
    link: "missal/santos/07-23-viseu",
    type: "sancti",
    local: "viseu",
    category: "santos",
    month: 7,
    day: 23,
  },
  SANCTI_07_24: {
    flexibility: "santos",
    id: "SANCTI_07_24",
    name: "Vigília de S. Tiago, Apóstolo",
    rank: 3,
    color: "v",
    link: "missal/santos/07-24",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 24,
    suppressedIn: ["62"],
  },
  // Rubrics 1960: St Christina on Jul 24th, replacing the Vigil of
  // St James (DO Kalendaria 1960.txt 07-24r). Proper text pending -
  // links to the Common of Virgin Martyrs meanwhile.
  SANCTI_07_24_1962: {
    flexibility: "santos",
    id: "SANCTI_07_24_1962",
    name: "S. Cristina, Virgem e Mártir",
    rank: 4,
    color: "r",
    link: "missal/comum/17virgensmartires1",
    type: "sancti",
    calendar: "62",
    category: "santos",
    month: 7,
    day: 24,
  },
  SANCTI_07_24_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_07_24_OUTRO",
    name: "Santa Cristina",
    rank: 4,
    color: "r",
    link: "missal/santos/07-24-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 7,
    day: 24,
  },
  SANCTI_07_25: {
    flexibility: "santos",
    id: "SANCTI_07_25",
    name: "S. Tiago, Apóstolo",
    rank: 2,
    color: "r",
    link: "missal/santos/07-25",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 25,
  },
  SANCTI_07_25_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_07_25_OUTRO",
    name: "S. Cristovão, Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/07-25-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 7,
    day: 25,
  },
  SANCTI_07_26: {
    flexibility: "santos",
    id: "SANCTI_07_26",
    name: "S. Ana, Mãe de Nossa Senhora",
    rank: 2,
    color: "w",
    link: "missal/santos/07-26",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 26,
  },
  SANCTI_07_27: {
    flexibility: "santos",
    id: "SANCTI_07_27",
    name: "S. Pantaleão, Mártir",
    rank: 4,
    color: "r",
    link: "missal/santos/07-27",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 27,
  },
  SANCTI_07_27_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_07_27_OUTRO",
    name: "B. Rodolfo Água-Viva e Outros, Márts",
    rank: 4,
    color: "r",
    link: "missal/santos/07-27-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 7,
    day: 27,
  },
  SANCTI_07_28: {
    flexibility: "santos",
    id: "SANCTI_07_28",
    name: "S.S. Nazário e Celso, Mártires",
    rank: 3,
    color: "r",
    link: "missal/santos/07-28",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 28,
  },
  SANCTI_07_28_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_07_28_OUTRO",
    name: "S. Vítor, Papa e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/07-28-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 7,
    day: 28,
  },
  SANCTI_07_28_OUTRO_2: {
    flexibility: "santos",
    id: "SANCTI_07_28_OUTRO_2",
    name: "S. Inocêncio, Papa e Confessor",
    rank: 3,
    color: "r",
    link: "missal/santos/07-28-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 7,
    day: 28,
  },
  SANCTI_07_29: {
    flexibility: "santos",
    id: "SANCTI_07_29",
    name: "S. Marta, Virgem",
    rank: 3,
    color: "w",
    link: "missal/santos/07-29",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 29,
  },
  SANCTI_07_29_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_07_29_OUTRO",
    name: "S. Félix II, Papa e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/07-29-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 7,
    day: 29,
  },
  SANCTI_07_30: {
    flexibility: "santos",
    id: "SANCTI_07_30",
    name: "S.S. Ábdon e Senen, Mártires",
    rank: 4,
    color: "r",
    link: "missal/santos/07-30",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 30,
  },
  SANCTI_07_31: {
    flexibility: "santos",
    id: "SANCTI_07_31",
    name: "S. Inácio de Loiola, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/07-31",
    type: "sancti",
    category: "santos",
    month: 7,
    day: 31,
  },
};
