import type { MassMap } from "../../domain";

export const SANCTI_08: MassMap = {
  SANCTI_08_01: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_01",
    name: "Os Santos Mártires Macabeus",
    color: "r",
    link: "missal/santos/08-01",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 1,
  },
  SANCTI_08_01_AD_VINCULA: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex II classis", precedence: 5 }],
    id: "SANCTI_08_01_AD_VINCULA",
    name: "S. Pedro ad Vincula (Cadeia de S. Pedro)",
    color: "r",
    // Proper page pending - links to the Macabees commemoration of the
    // same date meanwhile.
    link: "missal/santos/08-01",
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 8,
    day: 1,
  },
  SANCTI_08_02: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_02",
    name: "S. Afonso de Ligório, Bispo, Confessor e Doutor da Igreja",
    color: "r",
    link: "missal/santos/08-02",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 2,
  },
  SANCTI_08_02_OUTRO: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_02_OUTRO",
    name: "S. Estêvão I, Papa e Mártir",
    color: "r",
    link: "missal/santos/08-02-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 8,
    day: 2,
  },
  SANCTI_08_04: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_04",
    name: "S. Domingos, Confessor",
    color: "w",
    link: "missal/santos/08-04",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 4,
  },
  SANCTI_08_05: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_05",
    name: "Dedicação da Igreja de Nossa Senhora das Neves",
    color: "w",
    link: "missal/santos/08-05",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 5,
  },
  SANCTI_08_06: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex II classis", precedence: 5 }],
    id: "SANCTI_08_06",
    name: "Transfiguração de Nosso Senhor Jesus Cristo",
    color: "r",
    link: "missal/santos/08-06",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 6,
  },
  SANCTI_08_06_OUTRO: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_06_OUTRO",
    name: "S. S. Sixto, Papa, Felicíssimo e Agapito, Márts.",
    color: "r",
    link: "missal/santos/08-06-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 8,
    day: 6,
  },
  SANCTI_08_06_OUTRO_2: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_06_OUTRO_2",
    name: "S. Sixto II, Papa e Mártir",
    color: "r",
    link: "missal/santos/08-06-outro-2",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 8,
    day: 6,
  },
  SANCTI_08_07: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_07",
    name: "S. Caetano, Confessor",
    color: "r",
    link: "missal/santos/08-07",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 7,
  },
  SANCTI_08_08: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_08",
    name: "S. Ciríaco e Outros, Mártires",
    color: "r",
    link: "missal/santos/08-08",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 8,
  },
  SANCTI_08_09: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex II classis", precedence: 5 }],
    id: "SANCTI_08_09",
    name: "S. João Maria Vianney, Confessor",
    color: "w",
    link: "missal/santos/08-09",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 9,
  },
  SANCTI_08_09_OUTRO_2: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_09_OUTRO_2",
    name: "S. Romão, Mártir",
    color: "r",
    link: "missal/santos/08-09-outro-2",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 8,
    day: 9,
  },
  SANCTI_08_10: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex II classis", precedence: 5 }],
    id: "SANCTI_08_10",
    name: "S. Lourenço, Mártir",
    color: "r",
    link: "missal/santos/08-10",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 10,
  },
  SANCTI_08_11: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_11",
    name: "S.S. Tibúrcio e Susana, Mártires",
    color: "r",
    link: "missal/santos/08-11",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 11,
  },
  SANCTI_08_11_OUTRO: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_11_OUTRO",
    name: "S. Filomena, Virgem e Mártir",
    color: "r",
    link: "missal/santos/08-11-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 8,
    day: 11,
  },
  SANCTI_08_12: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_12",
    name: "S. Clara, Virgem",
    color: "w",
    link: "missal/santos/08-12",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 12,
  },
  SANCTI_08_13: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_13",
    name: "S.S. Hipólito e Cassiano, Mártires",
    color: "r",
    link: "missal/santos/08-13",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 13,
  },
  SANCTI_08_14: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex II classis", precedence: 5 }],
    id: "SANCTI_08_14",
    name: "Vigília da Assunção de Nossa Senhora",
    color: "w",
    link: "missal/santos/08-14",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 14,
  },
  SANCTI_08_15: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex I classis", precedence: 6.5 }],
    id: "SANCTI_08_15",
    name: "Assunção de Nossa Senhora",
    color: "w",
    link: "missal/santos/08-15",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 15,
    novena: true,
  },
  SANCTI_08_16: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex II classis", precedence: 5 }],
    id: "SANCTI_08_16",
    name: "S. Joaquim, Pai de Nossa Senhora",
    color: "w",
    link: "missal/santos/08-16",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 16,
  },
  SANCTI_08_17: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_17",
    name: "S. Jacinto, Confessor",
    color: "w",
    link: "missal/santos/08-17",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 17,
  },
  SANCTI_08_18_OITAVA_ASSUNCAO: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex II classis", precedence: 5 }],
    id: "SANCTI_08_18_OITAVA_ASSUNCAO",
    name: "Dentro da Oitava da Assunção de Nossa Senhora",
    color: "w",
    link: "missal/santos/08-15",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 18,
  },
  SANCTI_08_18_OUTRO: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_18_OUTRO",
    name: "S. Roque, Confessor",
    color: "w",
    link: "missal/santos/08-18-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 8,
    day: 18,
  },
  SANCTI_08_19: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_19",
    name: "S. João Eudes, Confessor",
    color: "w",
    link: "missal/santos/08-19",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 19,
  },
  SANCTI_08_20: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_20",
    name: "S. Bernardo, Abade e Doutor da Igreja",
    color: "w",
    link: "missal/santos/08-20",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 20,
    novena: true,
  },
  SANCTI_08_21: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_21",
    name: "S. Joana de Chantal, Viúva",
    color: "w",
    link: "missal/santos/08-21",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 21,
  },
  SANCTI_08_22: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex II classis", precedence: 5 }],
    id: "SANCTI_08_22",
    name: "Imaculado Coração de Nossa Senhora",
    color: "w",
    link: "missal/santos/08-22",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 22,
  },
  SANCTI_08_22_OUTRO: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_22_OUTRO",
    name: "S. Timóteo e Outros, Mártires",
    color: "r",
    link: "missal/santos/08-22-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 8,
    day: 22,
  },
  SANCTI_08_23: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_23",
    name: "S. Filipe Benício, Confessor",
    color: "w",
    link: "missal/santos/08-23",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 23,
  },
  SANCTI_08_24: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex II classis", precedence: 5 }],
    id: "SANCTI_08_24",
    name: "S. Bartolomeu, Apóstolo",
    color: "r",
    link: "missal/santos/08-24",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 24,
  },
  SANCTI_08_25: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_25",
    name: "S. Luís, Rei de França e Confessor",
    color: "w",
    link: "missal/santos/08-25",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 25,
  },
  SANCTI_08_26: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_26",
    name: "S. Zeferino",
    color: "r",
    link: "missal/santos/08-26",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 26,
  },
  SANCTI_08_27: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_27",
    name: "S. José Calasans, Confessor",
    color: "w",
    link: "missal/santos/08-27",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 27,
  },
  SANCTI_08_28: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_28",
    name: "S. Agostinho, Bispo, Confessor e Doutor da Igreja",
    color: "r",
    link: "missal/santos/08-28",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 28,
  },
  SANCTI_08_28_OUTRO: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_28_OUTRO",
    name: "S. Hermes, Mártir",
    color: "r",
    link: "missal/santos/08-28-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 8,
    day: 28,
  },
  SANCTI_08_29: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_29",
    name: "Degolação de  S. João Baptista",
    color: "r",
    link: "missal/santos/08-29",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 29,
  },
  SANCTI_08_30: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_30",
    name: "Santa Rosa de Lima, Virgem",
    color: "r",
    link: "missal/santos/08-30",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 30,
  },
  SANCTI_08_31: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_08_31",
    name: "S. Raimundo Nonato, Confessor",
    color: "w",
    link: "missal/santos/08-31",
    type: "sancti",
    category: "santos",
    month: 8,
    day: 31,
  },

  SANCTI_08_23_VIGILIA: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_08_23_VIGILIA",
    name: "Vigília de S. Bartolomeu, Apóstolo",
    // Abolished by the 1955 reform.
    color: "v",
    link: "missal/santos/08-24",
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 8,
    day: 23,
  },
};
