import type { MassMap } from "../../domain";

export const SANCTI_09: MassMap = {
  SANCTI_09_01: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_01",
    name: "S. Egídio, Abade",
    color: "w",
    link: "missal/santos/09-01",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 1,
  },
  SANCTI_09_01_OUTRO: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_01_OUTRO",
    name: "S. S. Doze Irmãos, Mártires",
    color: "r",
    link: "missal/santos/09-01-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 9,
    day: 1,
  },
  SANCTI_09_02: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_02",
    name: "S. Estêvão, Rei e Confessor",
    color: "w",
    link: "missal/santos/09-02",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 2,
  },
  SANCTI_09_03: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_03",
    name: "S. Pio X, Papa e Confessor",
    color: "w",
    link: "missal/santos/09-03",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 3,
  },
  SANCTI_09_05: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_05",
    name: "S. Lourenço Justiniano, Bispo e Confessor",
    color: "w",
    link: "missal/santos/09-05",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 5,
  },
  SANCTI_09_08: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex II classis", precedence: 5 }],
    id: "SANCTI_09_08",
    name: "Natividade da B. V. Maria",
    color: "w",
    link: "missal/santos/09-08",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 8,
  },
  SANCTI_09_09: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_09",
    name: "S. Gorgónio, Mártir",
    color: "r",
    link: "missal/santos/09-09",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 9,
  },
  SANCTI_09_09_ANGOLA: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_09_ANGOLA",
    name: "S. Pedro Claver, Confessor",
    color: "w",
    link: "missal/santos/09-09-angola",
    type: "sancti",
    local: "angola",
    category: "santos",
    month: 9,
    day: 9,
  },
  SANCTI_09_10: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_10",
    name: "S. Nicolau Tolentino, Confessor",
    color: "w",
    link: "missal/santos/09-10",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 10,
  },
  SANCTI_09_11: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_11",
    name: "S. S. Proto e Jacinto, Mártires",
    color: "r",
    link: "missal/santos/09-11",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 11,
  },
  SANCTI_09_12: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_12",
    name: "Santíssimo Nome de Maria",
    color: "w",
    link: "missal/santos/09-12",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 12,
  },
  SANCTI_09_14: {
    flexibility: "santos",
    id: "SANCTI_09_14",
    name: "Exaltação da Santa Cruz",
    color: "r",
    link: "missal/santos/09-14",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 14,
    rankVariants: [
      { rubrics: "*", name: "Duplex majus", precedence: 4 },
      { rubrics: "R1960", name: "Duplex II classis", precedence: 5.5 },
      { rubrics: "Cist", name: "Duplex II classis", precedence: 3 },
    ],
  },
  SANCTI_09_15: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex II classis", precedence: 5 }],
    id: "SANCTI_09_15",
    name: "Sete Dores da B. V. Maria",
    color: "w",
    link: "missal/santos/09-15",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 15,
    novena: true,
  },
  SANCTI_09_16: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_16",
    name: "S. S. Cornélio e Cipriano, Mártires",
    color: "w",
    link: "missal/santos/09-16",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 16,
  },
  SANCTI_09_16_OUTRO: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_16_OUTRO",
    name: "S. Cornélio, Papa e Mártir",
    color: "r",
    link: "missal/santos/09-16-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 9,
    day: 16,
  },
  SANCTI_09_16_OUTRO_2: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_16_OUTRO_2",
    name: "Santa Eufémia e Outros, Mártires",
    color: "r",
    link: "missal/santos/09-16-outro-2",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 9,
    day: 16,
  },
  SANCTI_09_16_PORTO: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_16_PORTO",
    name: "Na Dedicação da Igreja Catedral do Porto, a 16 de Setembro",
    color: "w",
    link: "missal/santos/09-16-porto",
    type: "sancti",
    local: "porto",
    category: "santos",
    month: 9,
    day: 16,
  },
  SANCTI_09_17: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_17",
    name: "Imp. dos Estigmas em S. Francisco",
    color: "w",
    link: "missal/santos/09-17",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 17,
  },
  SANCTI_09_18: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_18",
    name: "S. José Cupertino, Confessor",
    color: "w",
    link: "missal/santos/09-18",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 18,
  },
  SANCTI_09_19: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_19",
    name: "S. Januário e Outros, Mártires",
    color: "r",
    link: "missal/santos/09-19",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 19,
  },
  SANCTI_09_20: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_20",
    name: "Vigília de S. Mateus, Apóstolo e Evangelista",
    color: "v",
    link: "missal/santos/09-20",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 20,
  },
  SANCTI_09_20_OUTRO: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_20_OUTRO",
    name: "S. Eustáquio e Outros, Mártires",
    color: "r",
    link: "missal/santos/09-20-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 9,
    day: 20,
  },
  SANCTI_09_21: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex II classis", precedence: 5 }],
    id: "SANCTI_09_21",
    name: "S. Mateus, Apóstolo e Evangelista",
    color: "r",
    link: "missal/santos/09-21",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 21,
  },
  SANCTI_09_22: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_22",
    name: "S. Tomás de Vilanova, Bispo e Confessor",
    color: "w",
    link: "missal/santos/09-22",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 22,
  },
  SANCTI_09_23: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_23",
    name: "S. Lino, Papa e Mártir",
    color: "r",
    link: "missal/santos/09-23",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 23,
  },
  SANCTI_09_23_OUTRO: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_23_OUTRO",
    name: "Santa Tecla, Virgem e Mártir",
    color: "r",
    link: "missal/santos/09-23-outro",
    // Divino Afflatu-era observance; dropped by the 1960 reform.
    suppressedIn: ["62"],
    type: "sancti",
    category: "santos",
    month: 9,
    day: 23,
  },
  SANCTI_09_24: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_24",
    name: "B. V. Maria das Mercês",
    color: "w",
    link: "missal/santos/09-24",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 24,
  },
  SANCTI_09_26: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Simplex", precedence: 1.5 }],
    id: "SANCTI_09_26",
    name: "S. S. Cipriano e Justina, Mártires",
    color: "r",
    link: "missal/santos/09-26",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 26,
  },
  SANCTI_09_27: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_27",
    name: "S. S. Cosme e Damião, Mártires",
    color: "r",
    link: "missal/santos/09-27",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 27,
  },
  SANCTI_09_28: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_28",
    name: "S. Venceslau, Mártir",
    color: "r",
    link: "missal/santos/09-28",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 28,
  },
  SANCTI_09_29: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex I classis", precedence: 6.5 }],
    id: "SANCTI_09_29",
    name: "Dedicação de S. Miguel Arcanjo",
    color: "w",
    link: "missal/santos/09-29",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 29,
    novena: true,
  },
  SANCTI_09_30: {
    flexibility: "santos",
    rankVariants: [{ rubrics: "*", name: "Duplex", precedence: 3.5 }],
    id: "SANCTI_09_30",
    name: "S. Jerónimo, Presbítero Confessor e Doutor",
    color: "w",
    link: "missal/santos/09-30",
    type: "sancti",
    category: "santos",
    month: 9,
    day: 30,
  },
};
