import type { MassMap } from "../../domain";

export const SANCTI_10: MassMap = {
  SANCTI_10_01: {
    flexibility: "santos",
    id: "SANCTI_10_01",
    name: "S. Remigio",
    rank: 4,
    color: "w",
    link: "missal/santos/10-01",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 1,
  },
  SANCTI_10_01_LISBOA: {
    flexibility: "santos",
    id: "SANCTI_10_01_LISBOA",
    name: "S. Veríssimo e Outros, Mártires",
    rank: 4,
    color: "w",
    link: "missal/santos/10-01-lisboa",
    type: "sancti",
    local: "lisboa",
    category: "santos",
    month: 10,
    day: 1,
  },
  SANCTI_10_02: {
    flexibility: "santos",
    id: "SANCTI_10_02",
    name: "Santos Anjos da Guarda",
    rank: 3,
    color: "w",
    link: "missal/santos/10-02",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 2,
  },
  SANCTI_10_03: {
    flexibility: "santos",
    id: "SANCTI_10_03",
    name: "Santa Teresa do Menino Jesus",
    rank: 3,
    color: "w",
    link: "missal/santos/10-03",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 3,
  },
  SANCTI_10_04: {
    flexibility: "santos",
    id: "SANCTI_10_04",
    name: "S. Francisco",
    rank: 3,
    color: "w",
    link: "missal/santos/10-04",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 4,
  },
  SANCTI_10_05: {
    flexibility: "santos",
    id: "SANCTI_10_05",
    name: "S. Plácido e Companheiros Mártires",
    rank: 4,
    color: "r",
    link: "missal/santos/10-05",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 5,
  },
  SANCTI_10_06: {
    flexibility: "santos",
    id: "SANCTI_10_06",
    name: "S. Bruno, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/10-06",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 6,
  },
  SANCTI_10_07: {
    flexibility: "santos",
    id: "SANCTI_10_07",
    name: "SS. Rosário da B. V. Maria",
    rank: 2,
    color: "w",
    link: "missal/santos/10-07",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 7,
    novena: true,
  },
  SANCTI_10_07_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_10_07_OUTRO",
    name: "S. Marcos, Papa e Conf.",
    rank: 4,
    color: "w",
    link: "missal/santos/10-07-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 10,
    day: 7,
  },
  SANCTI_10_07_OUTRO_2: {
    flexibility: "santos",
    id: "SANCTI_10_07_OUTRO_2",
    name: "S. S. Sérgio, Baco e Outros, Mártires",
    rank: 4,
    color: "r",
    link: "missal/santos/10-07-outro-2",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 10,
    day: 7,
  },
  SANCTI_10_08: {
    flexibility: "santos",
    id: "SANCTI_10_08",
    name: "Santa Brígida, Viúva",
    rank: 3,
    color: "w",
    link: "missal/santos/10-08",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 8,
  },
  SANCTI_10_08_OUTRO_1962: {
    flexibility: "santos",
    id: "SANCTI_10_08_OUTRO_1962",
    name: "S. S. Sérgio, Baco e Outros, Mártires",
    rank: 4,
    color: "r",
    calendar: "62",
    link: "missal/santos/10-07-outro-2",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 10,
    day: 8,
  },
  SANCTI_10_09: {
    flexibility: "santos",
    id: "SANCTI_10_09",
    name: "S. João Leonardo, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/10-09",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 9,
  },
  SANCTI_10_09_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_10_09_OUTRO",
    name: "S. Dionísio e Outros, Mártires",
    rank: 3,
    color: "r",
    link: "missal/santos/10-09-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 10,
    day: 9,
  },
  SANCTI_10_09_FUNCHAL: {
    flexibility: "santos",
    id: "SANCTI_10_09_FUNCHAL",
    name: "B. Virgem Maria do Monte",
    rank: 3,
    color: "w",
    link: "missal/santos/10-09-funchal",
    type: "sancti",
    local: "funchal",
    category: "santos",
    month: 10,
    day: 9,
  },
  SANCTI_10_10: {
    flexibility: "santos",
    id: "SANCTI_10_10",
    name: "S. Francisco de Bórgia",
    rank: 3,
    color: "w",
    link: "missal/santos/10-10",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 10,
  },
  SANCTI_10_11: {
    flexibility: "santos",
    id: "SANCTI_10_11",
    name: "Maternidade da B. V. Maria",
    rank: 2,
    color: "w",
    link: "missal/santos/10-11",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 11,
  },
  SANCTI_10_13: {
    flexibility: "santos",
    id: "SANCTI_10_13",
    name: "S. Eduardo, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/10-13",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 13,
  },
  SANCTI_10_14: {
    flexibility: "santos",
    id: "SANCTI_10_14",
    name: "S. Calisto I, Papa e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/10-14",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 14,
  },
  SANCTI_10_15: {
    flexibility: "santos",
    id: "SANCTI_10_15",
    name: "Santa Teresa, Virgem",
    rank: 3,
    color: "w",
    link: "missal/santos/10-15",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 15,
  },
  SANCTI_10_16: {
    flexibility: "santos",
    id: "SANCTI_10_16",
    name: "Santa Hedviges, Viúva",
    rank: 3,
    color: "w",
    link: "missal/santos/10-16",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 16,
  },
  SANCTI_10_16_ANGRA: {
    flexibility: "santos",
    id: "SANCTI_10_16_ANGRA",
    name: "Na Dedicação da Igreja Catedral de Angra",
    rank: 3,
    color: "w",
    link: "missal/santos/10-16-angra",
    type: "sancti",
    local: "angra",
    category: "santos",
    month: 10,
    day: 16,
  },
  SANCTI_10_17: {
    flexibility: "santos",
    id: "SANCTI_10_17",
    name: "Santa Margarida Maria, Virgem",
    rank: 3,
    color: "w",
    link: "missal/santos/10-17",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 17,
  },
  SANCTI_10_17_BRAGA: {
    flexibility: "santos",
    id: "SANCTI_10_17_BRAGA",
    name: "Trasl. de S. Pedro de Rates",
    rank: 3,
    color: "w",
    link: "missal/santos/10-17-braga",
    type: "sancti",
    local: "braga",
    category: "santos",
    month: 10,
    day: 17,
  },
  SANCTI_10_18: {
    flexibility: "santos",
    id: "SANCTI_10_18",
    name: "S. Lucas, Evangelista",
    rank: 2,
    color: "r",
    link: "missal/santos/10-18",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 18,
  },
  SANCTI_10_19: {
    flexibility: "santos",
    id: "SANCTI_10_19",
    name: "S. Pedro de Alcântara, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/10-19",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 19,
  },
  SANCTI_10_20: {
    flexibility: "santos",
    id: "SANCTI_10_20",
    name: "S. João Câncio, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/10-20",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 20,
  },
  SANCTI_10_20_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_10_20_PORTUGAL",
    name: "Santa Iria, Virgem e Mártir",
    rank: 3,
    color: "w",
    link: "missal/santos/10-20-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 10,
    day: 20,
  },
  SANCTI_10_21: {
    flexibility: "santos",
    id: "SANCTI_10_21",
    name: "S. Hilarião, Abade",
    rank: 4,
    color: "w",
    link: "missal/santos/10-21",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 21,
  },
  SANCTI_10_21_VISEU_LISBOA: {
    flexibility: "santos",
    id: "SANCTI_10_21_VISEU_LISBOA",
    name: "S. Úrsula e Outras, Virgens e Mártires",
    rank: 4,
    color: "w",
    link: "missal/santos/10-21-viseu-lisboa",
    type: "sancti",
    local: "viseu-lisboa",
    category: "santos",
    month: 10,
    day: 21,
  },
  SANCTI_10_22_GUARDA: {
    flexibility: "santos",
    id: "SANCTI_10_22_GUARDA",
    name: "Na Dedicação da Igreja Catedral da Guarda",
    rank: 4,
    color: "w",
    link: "missal/santos/10-22-guarda",
    type: "sancti",
    local: "guarda",
    category: "santos",
    month: 10,
    day: 22,
  },
  SANCTI_10_22_LISBOA_EVORA_BEJA: {
    flexibility: "santos",
    id: "SANCTI_10_22_LISBOA_EVORA_BEJA",
    name: "Na Dedicação da Basílica de Mafra",
    rank: 4,
    color: "w",
    link: "missal/santos/10-22-lisboa-evora-beja",
    type: "sancti",
    local: "lisboa-evora-beja",
    category: "santos",
    month: 10,
    day: 22,
  },
  SANCTI_10_23: {
    flexibility: "santos",
    id: "SANCTI_10_23",
    name: "S. António Maria Claret, Bispo e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/10-23",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 23,
  },
  SANCTI_10_23_ANGRA: {
    flexibility: "santos",
    id: "SANCTI_10_23_ANGRA",
    name: "Na Oitava da Dedicação da Igreja Catedral de Angra",
    rank: 4,
    color: "w",
    link: "missal/santos/10-23",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 23,
  },
  SANCTI_10_24: {
    flexibility: "santos",
    id: "SANCTI_10_24",
    name: "S. Rafael, Arcanjo",
    rank: 3,
    color: "w",
    link: "missal/santos/10-24",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 24,
  },
  SANCTI_10_25: {
    flexibility: "santos",
    id: "SANCTI_10_25",
    name: "S.S. Crisanto e Daria, Mártires",
    rank: 4,
    color: "r",
    link: "missal/santos/10-25",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 25,
  },
  SANCTI_10_25_BRAGA: {
    flexibility: "santos",
    id: "SANCTI_10_25_BRAGA",
    name: "Trasl. de S. Martinho de Dume",
    rank: 4,
    color: "w",
    link: "missal/santos/10-25-braga",
    type: "sancti",
    local: "braga",
    category: "santos",
    month: 10,
    day: 25,
  },
  SANCTI_10_25_EVORA_BEJA: {
    flexibility: "santos",
    id: "SANCTI_10_25_EVORA_BEJA",
    name: "S. S. Crispim e Crispiniano, Márts.",
    rank: 4,
    color: "w",
    link: "missal/santos/10-25-evora-beja",
    type: "sancti",
    local: "evora-beja",
    category: "santos",
    month: 10,
    day: 25,
  },
  SANCTI_10_25_FUNCHAL: {
    flexibility: "santos",
    id: "SANCTI_10_25_FUNCHAL",
    name: "Na Oitava da Dedicação da Igreja Catedral do Funchal",
    rank: 4,
    color: "w",
    link: "missal/santos/10-25-funchal",
    type: "sancti",
    local: "funchal",
    category: "santos",
    month: 10,
    day: 25,
  },
  SANCTI_10_27_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_10_27_PORTUGAL",
    name: "S. Gonçalo de Lagos",
    rank: 4,
    color: "w",
    link: "missal/santos/10-27-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 10,
    day: 27,
  },
  SANCTI_10_27_EVORA: {
    flexibility: "santos",
    id: "SANCTI_10_27_EVORA",
    name: "S. S. Vicente, Sabina e Cristeta",
    rank: 4,
    color: "w",
    link: "missal/santos/10-27-evora",
    type: "sancti",
    local: "evora",
    category: "santos",
    month: 10,
    day: 27,
  },
  SANCTI_10_28: {
    flexibility: "santos",
    id: "SANCTI_10_28",
    name: "S.S. Simão e Judas, Apóstolos",
    rank: 2,
    color: "r",
    link: "missal/santos/10-28",
    type: "sancti",
    category: "santos",
    month: 10,
    day: 28,
  },
  SANCTI_10_29_GUARDA: {
    flexibility: "santos",
    id: "SANCTI_10_29_GUARDA",
    name: "Na Oitava da Dedicação da Igreja Catedral da Guarda",
    rank: 4,
    color: "w",
    link: "missal/santos/10-29-guarda",
    type: "sancti",
    local: "guarda",
    category: "santos",
    month: 10,
    day: 29,
  },
  SANCTI_10_29_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_10_29_PORTUGAL",
    name: "Trasl. de Santa Isabel, Rainha",
    rank: 4,
    color: "w",
    link: "missal/santos/10-29-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 10,
    day: 29,
  },
  SANCTI_10_30_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_10_30_PORTUGAL",
    name: "Vitória dos Cristãos",
    rank: 4,
    color: "w",
    link: "missal/santos/10-30-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 10,
    day: 30,
  },
};
