import type { MassMap } from "../../domain";

export const SANCTI_11: MassMap = {
  SANCTI_11_01: {
    flexibility: "santos",
    id: "SANCTI_11_01",
    name: "Todos os Santos",
    rank: 1,
    color: "w",
    link: "missal/santos/11-01",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 1,
    novena: true,
  },
  SANCTI_11_02: {
    flexibility: "santos",
    id: "SANCTI_11_02",
    name: "Comemoração dos Fiéis Defuntos",
    rank: 1,
    color: "b",
    link: "missal/santos/11-02",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 2,
  },
  SANCTI_11_04: {
    flexibility: "santos",
    id: "SANCTI_11_04",
    name: "S. Carlos Borromeu, Bispo e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/11-04",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 4,
  },
  SANCTI_11_05_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_11_05_PORTUGAL",
    name: "Sagradas Relíquias",
    rank: 4,
    color: "w",
    link: "missal/santos/11-05-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 11,
    day: 5,
  },
  SANCTI_11_06_PORTUGAL: {
    flexibility: "santos",
    id: "SANCTI_11_06_PORTUGAL",
    name: "S. Nuno de Santa Maria",
    rank: 4,
    color: "w",
    link: "missal/santos/11-06-portugal",
    type: "sancti",
    local: "portugal",
    category: "santos",
    month: 11,
    day: 6,
    novena: true,
  },
  SANCTI_11_08: {
    flexibility: "santos",
    id: "SANCTI_11_08",
    name: "Os Quatro S.S. Mártires Coroados",
    rank: 4,
    color: "r",
    link: "missal/santos/11-08",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 8,
  },
  SANCTI_11_09: {
    flexibility: "santos",
    id: "SANCTI_11_09",
    name: "Dedicação da Basílica do Salvador",
    rank: 2,
    color: "w",
    link: "missal/santos/11-09",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 9,
  },
  SANCTI_11_10: {
    flexibility: "santos",
    id: "SANCTI_11_10",
    name: "S. André de Avelino, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/11-10",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 10,
  },
  SANCTI_11_11: {
    flexibility: "santos",
    id: "SANCTI_11_11",
    name: "S. Martinho, Bispo e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/11-11",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 11,
  },
  SANCTI_11_12: {
    flexibility: "santos",
    id: "SANCTI_11_12",
    name: "S. Martinho I, Papa e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/11-12",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 12,
  },
  SANCTI_11_13: {
    flexibility: "santos",
    id: "SANCTI_11_13",
    name: "S. Diogo, Confessor",
    rank: 4,
    color: "w",
    link: "missal/santos/11-13",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 13,
  },
  SANCTI_11_14: {
    flexibility: "santos",
    id: "SANCTI_11_14",
    name: "S. Josafá, Bispo e Mártir",
    rank: 3,
    color: "w",
    link: "missal/santos/11-14",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 14,
  },
  SANCTI_11_15: {
    flexibility: "santos",
    id: "SANCTI_11_15",
    name: "S. Alberto Magno, Bispo, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/11-15",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 15,
  },
  SANCTI_11_15_BRAGA: {
    flexibility: "santos",
    id: "SANCTI_11_15_BRAGA",
    name: "Na Dedicação da Basílica do Santíssimo Coração de Jesus",
    rank: 3,
    color: "w",
    link: "missal/santos/11-15-braga",
    type: "sancti",
    local: "braga",
    category: "santos",
    month: 11,
    day: 15,
  },
  SANCTI_11_16: {
    flexibility: "santos",
    id: "SANCTI_11_16",
    name: "S. Gertrudes, Virgem",
    rank: 3,
    color: "w",
    link: "missal/santos/11-16",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 16,
  },
  SANCTI_11_16_COIMBRA_BRAGANCA: {
    flexibility: "santos",
    id: "SANCTI_11_16_COIMBRA_BRAGANCA",
    name: "Na Dedicação das Igrejas Catedrais de Bragança e Coimbra",
    rank: 3,
    color: "w",
    link: "missal/santos/11-16-coimbra-braganca",
    type: "sancti",
    local: "coimbra-braganca",
    category: "santos",
    month: 11,
    day: 16,
  },
  SANCTI_11_17: {
    flexibility: "santos",
    id: "SANCTI_11_17",
    name: "S. Gregório Taumaturgo, Bispo e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/11-17",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 17,
  },
  SANCTI_11_18: {
    flexibility: "santos",
    id: "SANCTI_11_18",
    name: "Dedicação da Basílica de S.S Pedro e Paulo",
    rank: 3,
    color: "w",
    link: "missal/santos/11-18",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 18,
  },
  SANCTI_11_19: {
    flexibility: "santos",
    id: "SANCTI_11_19",
    name: "S. Isabel, Viúva",
    rank: 3,
    color: "w",
    link: "missal/santos/11-19",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 19,
  },
  SANCTI_11_19_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_11_19_OUTRO",
    name: "Comemoração de S. Ponciano, Papa e Mártir",
    rank: 4,
    color: "r",
    link: "missal/santos/11-19-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 11,
    day: 19,
  },
  SANCTI_11_20: {
    flexibility: "santos",
    id: "SANCTI_11_20",
    name: "S. Félix de Valois, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/11-20",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 20,
  },
  SANCTI_11_20_LAMEGO: {
    flexibility: "santos",
    id: "SANCTI_11_20_LAMEGO",
    name: "Na Dedicação da Igreja Catedral de Lamego",
    rank: 3,
    color: "w",
    link: "missal/santos/11-20-lamego",
    type: "sancti",
    local: "lamego",
    category: "santos",
    month: 11,
    day: 20,
  },
  SANCTI_11_21: {
    flexibility: "santos",
    id: "SANCTI_11_21",
    name: "Apresentação da Nossa Senhora",
    rank: 3,
    color: "w",
    link: "missal/santos/11-21",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 21,
  },
  SANCTI_11_22: {
    flexibility: "santos",
    id: "SANCTI_11_22",
    name: "S. Cecília, Virgem e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/11-22",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 22,
  },
  SANCTI_11_23: {
    flexibility: "santos",
    id: "SANCTI_11_23",
    name: "S. Clemente I, Papa e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/11-23",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 23,
  },
  SANCTI_11_23_COIMBRA_BRAGANCA: {
    flexibility: "santos",
    id: "SANCTI_11_23_COIMBRA_BRAGANCA",
    name: "Na Oitava da Dedicação das Igrejas Catedrais de Bragança e Coimbra",
    rank: 3,
    color: "w",
    link: "missal/santos/11-23-coimbra-braganca",
    type: "sancti",
    local: "coimbra-braganca",
    category: "santos",
    month: 11,
    day: 23,
  },
  SANCTI_11_24: {
    flexibility: "santos",
    id: "SANCTI_11_24",
    name: "S. João da Cruz, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/11-24",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 24,
  },
  SANCTI_11_24_VILA_REAL: {
    flexibility: "santos",
    id: "SANCTI_11_24_VILA_REAL",
    name: "Na Dedicação da Igreja Catedral de Vila Real",
    rank: 3,
    color: "w",
    link: "missal/santos/11-24-vila-real",
    type: "sancti",
    local: "vila-real",
    category: "santos",
    month: 11,
    day: 24,
  },
  SANCTI_11_25: {
    flexibility: "santos",
    id: "SANCTI_11_25",
    name: "S. Catarina, Virgem e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/11-25",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 25,
  },
  SANCTI_11_26: {
    flexibility: "santos",
    id: "SANCTI_11_26",
    name: "S. Silvestre, Abade",
    rank: 3,
    color: "w",
    link: "missal/santos/11-26",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 26,
  },
  SANCTI_11_26_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_11_26_OUTRO",
    name: "S. Pedro Alexandrino, B. e Mártir",
    rank: 4,
    color: "w",
    link: "missal/santos/11-26-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 11,
    day: 26,
  },
  SANCTI_11_27_LAMEGO: {
    flexibility: "santos",
    id: "SANCTI_11_27_LAMEGO",
    name: "Na Oitava da Dedicação da Igreja Catedral da Lamego",
    rank: 3,
    color: "w",
    link: "missal/santos/11-27-lamego",
    type: "sancti",
    local: "lamego",
    category: "santos",
    month: 11,
    day: 27,
  },
  SANCTI_11_28: {
    flexibility: "santos",
    id: "SANCTI_11_28",
    name: "Santa Catarina Labouré, Virgem",
    rank: 3,
    color: "w",
    link: "missal/santos/11-28",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 28,
  },
  SANCTI_11_28_BRAGA: {
    flexibility: "santos",
    id: "SANCTI_11_28_BRAGA",
    name: "S. Tiago Intercísio, Mártir",
    rank: 3,
    color: "w",
    link: "missal/santos/11-28-braga",
    type: "sancti",
    category: "santos",
    local: "braga",
    month: 11,
    day: 28,
  },
  SANCTI_11_29: {
    flexibility: "santos",
    id: "SANCTI_11_29",
    name: "Vigília de S. André, Apóstolo",
    rank: 4,
    color: "r",
    link: "missal/santos/11-29",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 29,
      suppressedIn: ["62"],
},
  SANCTI_11_30: {
    flexibility: "santos",
    id: "SANCTI_11_30",
    name: "S. André, Apóstolo",
    rank: 2,
    color: "r",
    link: "missal/santos/11-30",
    type: "sancti",
    category: "santos",
    month: 11,
    day: 30,
  },
};
