import type { MassMap } from "../../domain";

export const SANCTI_12: MassMap = {
  SANCTI_12_01_VILA_REAL: {
    flexibility: "santos",
    id: "SANCTI_12_01_VILA_REAL",
    name: "Na Oitava da Dedicação da Igreja Catedral de Vila Real",
    rank: 3,
    color: "w",
    link: "missal/santos/12-01-vila-real",
    type: "sancti",
    local: "vila-real",
    category: "santos",
    month: 12,
    day: 1,
  },
  SANCTI_12_02: {
    flexibility: "santos",
    id: "SANCTI_12_02",
    name: "S. Bibiana, Virgem e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/12-02",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 2,
  },
  SANCTI_12_03: {
    flexibility: "santos",
    id: "SANCTI_12_03",
    name: "S. Francisco Xavier, Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/12-03",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 3,
  },
  SANCTI_12_04: {
    flexibility: "santos",
    id: "SANCTI_12_04",
    name: "S. Pedro Chrysólogo, Bispo, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/12-04",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 4,
  },
  SANCTI_12_04_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_12_04_OUTRO",
    name: "Santa Bárbara, Virgem e Mártir",
    rank: 4,
    color: "r",
    link: "missal/santos/12-04-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 12,
    day: 4,
  },
  SANCTI_12_05: {
    flexibility: "santos",
    id: "SANCTI_12_05",
    name: "S. Sabbas, Abade",
    rank: 4,
    color: "w",
    link: "missal/santos/12-05",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 5,
  },
  SANCTI_12_05_BRAGA: {
    flexibility: "santos",
    id: "SANCTI_12_05_BRAGA",
    name: "S. Geraldo, Bispo e Conf.",
    rank: 4,
    color: "w",
    link: "missal/santos/12-05-braga",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 5,
    local: "braga",
  },
  SANCTI_12_06: {
    flexibility: "santos",
    id: "SANCTI_12_06",
    name: "S. Nicolau, Bispo e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/12-06",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 6,
  },
  SANCTI_12_07: {
    flexibility: "santos",
    id: "SANCTI_12_07",
    name: "S. Ambrósio, Bispo, Confessor e Doutor da Igreja",
    rank: 3,
    color: "w",
    link: "missal/santos/12-07",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 7,
  },
  SANCTI_12_07_OUTRO: {
    flexibility: "santos",
    id: "SANCTI_12_07_OUTRO",
    name: "Vigília Imaculada Conceição da SS. Virgem",
    rank: 4,
    color: "v",
    link: "missal/santos/12-07-outro",
    outro: true,
    type: "sancti",
    category: "santos",
    month: 12,
    day: 7,
  },
  SANCTI_12_08: {
    flexibility: "santos",
    id: "SANCTI_12_08",
    name: "Imaculada Conceição da SS. Virgem",
    rank: 1,
    color: "w",
    link: "missal/santos/12-08",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 8,
    novena: true,
  },
  SANCTI_12_09: {
    flexibility: "santos",
    id: "SANCTI_12_09",
    name: "Segundo Dia na Oitava",
    rank: 3,
    color: "w",
    link: "missal/santos/12-09",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 9,
    novena: false,
  },
  SANCTI_12_10: {
    flexibility: "santos",
    id: "SANCTI_12_10",
    name: "S. Melquíades, Papa e Mártir",
    rank: 4,
    color: "r",
    link: "missal/santos/12-10",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 10,
    suppressedIn: ["pre-55"],
  },
  SANCTI_12_10_OITAVA_IMACULADA: {
    flexibility: "santos",
    id: "SANCTI_12_10_OITAVA_IMACULADA",
    name: "Dentro da Oitava da Imaculada Conceição",
    rank: 2,
    color: "w",
    link: "missal/santos/12-10",
    type: "sancti",
    suppressedIn: ["62"],
    category: "santos",
    month: 12,
    day: 10,
  },
  SANCTI_12_11: {
    flexibility: "santos",
    id: "SANCTI_12_11",
    name: "S. Dâmaso, Papa e Confessor",
    rank: 3,
    color: "w",
    link: "missal/santos/12-11",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 11,
  },
  SANCTI_12_12: {
    flexibility: "santos",
    id: "SANCTI_12_12",
    name: "Quinto Dia na Oitava",
    rank: 3,
    color: "w",
    link: "missal/santos/12-12",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 12,
    novena: false,
  },
  SANCTI_12_12_BRASIL: {
    flexibility: "santos",
    id: "SANCTI_12_12_BRASIL",
    name: "Nossa Senhora de Guadalupe",
    rank: 3,
    color: "w",
    link: "missal/santos/12-12-brasil",
    type: "sancti",
    local: "brasil",
    category: "santos",
    month: 12,
    day: 12,
  },
  SANCTI_12_12_PORTO: {
    flexibility: "santos",
    id: "SANCTI_12_12_PORTO",
    name: "Trasladação de S. Pantaleão",
    rank: 3,
    color: "w",
    link: "missal/santos/12-12-porto",
    type: "sancti",
    local: "porto",
    category: "santos",
    month: 12,
    day: 12,
  },
  SANCTI_12_13: {
    flexibility: "santos",
    id: "SANCTI_12_13",
    name: "S. Luzia, Virgem e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/12-13",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 13,
  },
  SANCTI_12_14: {
    flexibility: "santos",
    id: "SANCTI_12_14",
    name: "Sétimo Dia na Oitava",
    rank: 3,
    color: "w",
    link: "missal/santos/12-14",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 14,
    novena: false,
  },
  SANCTI_12_16: {
    flexibility: "santos",
    id: "SANCTI_12_16",
    name: "S. Eusébio, Bispo e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/12-16",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 16,
  },
  SANCTI_12_19_BRAGA: {
    flexibility: "santos",
    id: "SANCTI_12_19_BRAGA",
    name: "Trasladação de S. Geraldo",
    rank: 4,
    color: "w",
    link: "missal/santos/12-19-braga",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 19,
    local: "braga",
  },
  SANCTI_12_20: {
    flexibility: "santos",
    id: "SANCTI_12_20",
    name: "Vigília S. Tomé, Apóstolo",
    rank: 3,
    color: "r",
    link: "missal/santos/12-20",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 20,
  },
  SANCTI_12_21: {
    flexibility: "santos",
    id: "SANCTI_12_21",
    name: "S. Tomé, Apóstolo",
    rank: 2,
    color: "r",
    link: "missal/santos/12-21",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 21,
  },
  SANCTI_12_24: {
    flexibility: "santos",
    id: "SANCTI_12_24",
    name: "Vigília Natal de N. S. Jesus Cristo",
    rank: 1,
    color: "v",
    link: "missal/santos/12-24",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 24,
  },
  SANCTI_12_25_1: {
    flexibility: "santos",
    id: "SANCTI_12_25_1",
    name: "Missa da Noite de Natal de N. S. Jesus Cristo",
    rank: 1,
    color: "w",
    link: "missal/santos/12-25-0",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 25,
  },
  SANCTI_12_25_2: {
    flexibility: "santos",
    id: "SANCTI_12_25_2",
    name: "Missa da Aurora de Natal de N. S. Jesus Cristo",
    rank: 1,
    color: "w",
    link: "missal/santos/12-25-1",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 25,
  },
  SANCTI_12_25_3: {
    flexibility: "santos",
    id: "SANCTI_12_25_3",
    name: "Missa do Dia de Natal de N. S. Jesus Cristo",
    rank: 1,
    color: "w",
    link: "missal/santos/12-25-2",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 25,
  },
  SANCTI_12_26: {
    flexibility: "santos",
    id: "SANCTI_12_26",
    name: "S. Estêvão, Primeiro Mártir",
    rank: 2,
    color: "r",
    link: "missal/santos/12-26",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 26,
  },
  SANCTI_12_27: {
    flexibility: "santos",
    id: "SANCTI_12_27",
    name: "S. João, Apóstolo e Evangelista",
    rank: 2,
    color: "w",
    link: "missal/santos/12-27",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 27,
  },
  SANCTI_12_28: {
    flexibility: "santos",
    id: "SANCTI_12_28",
    name: "Santos Inocentes",
    rank: 2,
    color: "r",
    link: "missal/santos/12-28",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 28,
  },
  SANCTI_12_29: {
    flexibility: "santos",
    id: "SANCTI_12_29",
    name: "S. Tomás de Cantuária, Bispo e Mártir",
    rank: 3,
    color: "r",
    link: "missal/santos/12-29",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 29,
    suppressedIn: ["62"],
  },
  SANCTI_12_30: {
    flexibility: "santos",
    id: "SANCTI_12_30",
    name: "Sexto dia da Oitava do Natal",
    rank: 2,
    color: "w",
    link: "missal/santos/12-30",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 30,
  },
  SANCTI_12_31: {
    flexibility: "santos",
    id: "SANCTI_12_31",
    name: "S. Silvestre, Papa e Confessor",
    rank: 4,
    color: "w",
    link: "missal/santos/12-31",
    type: "sancti",
    category: "santos",
    month: 12,
    day: 31,
    rankVariants: [
      { rubrics: "*", name: "Duplex", precedence: 3.0 },
      { rubrics: "Rubrics 1960 - 1960", name: "Duplex II classis", precedence: 5.0 },
    ],
  },
};
