packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  typescript: 5.3.3
  date-fns: ^3.6.0
  "@types/node": ^20.9.0
  tailwindcss: ^4.1.16
  eslint: ^9.0.0

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.10
    "@types/react-dom": ^19.1.10
