packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.9.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
  date-fns: ^3.6.0
  "@date-fns/utc": ^1.2.0
  "@types/node": ^20.9.0
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
