packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  tailwindcss: ^3.4.10
  typescript: 5.3.3
  date-fns: ^3.6.0
  "@types/node": ^20.9.0
  "@biomejs/biome": ^1.8.3
  react: 18.2.0
  react-dom: 18.2.0
  "@types/react": 18.2.79
  "@types/react-dom": 18.2.25
