import type { MassMap } from "../domain";

/** Comuns da Missa. */
export const COMMUNES: MassMap = {
  COMMUNE_C_10A: {
    flexibility: "commune",
    id: "COMMUNE_C_10A",
    name: "1ª Missa da Virgem Maria - Missa Roráte cœli",
    rank: 0,
    color: "w",
    link: "missal/comum/27missamaria1",
    type: "feria",
    category: "comum",
  },
  COMMUNE_C_10B: {
    flexibility: "commune",
    id: "COMMUNE_C_10B",
    name: "2ª Missa da Virgem Maria - Missa Vultum tuum",
    rank: 0,
    color: "w",
    link: "missal/comum/28missamaria2",
    type: "feria",
    category: "comum",
  },
  COMMUNE_C_10C: {
    flexibility: "commune",
    id: "COMMUNE_C_10C",
    name: "3º Missa da Virgem Maria – Missa Salve, Sancta Parens",
    rank: 0,
    color: "w",
    link: "missal/comum/29missamaria3",
    type: "feria",
    category: "comum",
  },
  COMMUNE_C_10PASC: {
    flexibility: "commune",
    id: "COMMUNE_C_10PASC",
    name: "4 Missa da Virgem Maria – Missa Salve, Sancta Parens",
    rank: 0,
    color: "w",
    link: "missal/comum/30missamaria4",
    type: "feria",
    category: "comum",
  },
  COMMUNE_C_10T: {
    flexibility: "commune",
    id: "COMMUNE_C_10T",
    name: "5ª Missa da Virgem Maria - Missa Salve, Sancta Parens",
    rank: 0,
    color: "w",
    link: "missal/comum/31missamaria5",
    type: "feria",
    category: "comum",
  },
};
