import type { MassMap } from "../domain";

/** Missas votivas. */
export const VOTIVAS: MassMap = {
  VOTIVE_PENT01_0: {
    flexibility: "votivas",
    rankVariants: [{ rubrics: "*", name: "Votiva", precedence: 0.5 }],
    id: "VOTIVE_PENT01_0",
    name: "Santíssima Trindade",
    color: "w",
    link: "missal/votivas/santissimatrindade",
    type: "feria",
    category: "votivas",
  },
  VOTIVE_PENT02_5: {
    flexibility: "votivas",
    rankVariants: [{ rubrics: "*", name: "Votiva", precedence: 0.5 }],
    id: "VOTIVE_PENT02_5",
    name: "Santíssimo Coração de Jesus",
    color: "w",
    link: "missal/votivas/coracaojesus",
    type: "feria",
    category: "votivas",
    novena: true,
  },
  VOTIVE_ANGELS: {
    flexibility: "votivas",
    rankVariants: [{ rubrics: "*", name: "Votiva", precedence: 0.5 }],
    id: "VOTIVE_ANGELS",
    name: "Anjos",
    color: "w",
    link: "missal/votivas/anjos",
    type: "feria",
    category: "votivas",
  },
  VOTIVE_JOSEPH: {
    flexibility: "votivas",
    rankVariants: [{ rubrics: "*", name: "Votiva", precedence: 0.5 }],
    id: "VOTIVE_JOSEPH",
    name: "S. José",
    color: "w",
    link: "missal/votivas/jose",
    type: "feria",
    category: "votivas",
  },
  VOTIVE_JESUSETERNALPRIEST: {
    flexibility: "votivas",
    rankVariants: [{ rubrics: "*", name: "Votiva", precedence: 0.5 }],
    id: "VOTIVE_JESUSETERNALPRIEST",
    name: "N. S. Jesus Cristo Sumo e Eterno Sacerdote",
    color: "w",
    link: "missal/votivas/jesuseternosacerdote",
    type: "feria",
    category: "votivas",
  },
};
