import { expect, test } from "vitest";
import { getDay } from "../../lib/getDay";

test("2024-11-02", () => {
  const proper = getDay("2024-11-02");

  expect(proper).toMatchObject([
    {
      info: {
        colors: ["b"],
        date: "2024-11-02",
        day: {
          celebration: [
            {
              colors: ["b"],
              date: "2024-11-02",
              flexibility: "sancti",
              id: "sancti:11-02m1:1:b",
              name: "11-02m1",
              priority: 25,
              rank: 1,
              title: "Comemoração dos Fiéis Defuntos, 1ª Missa",
              weekday: 6,
            },
            {
              colors: ["b"],
              date: "2024-11-02",
              flexibility: "sancti",
              id: "sancti:11-02m2:1:b",
              name: "11-02m2",
              priority: 26,
              rank: 1,
              title: "Comemoração dos Fiéis Defuntos, 2ª Missa",
              weekday: 6,
            },
            {
              colors: ["b"],
              date: "2024-11-02",
              flexibility: "sancti",
              id: "sancti:11-02m3:1:b",
              name: "11-02m3",
              priority: 27,
              rank: 1,
              title: "Comemoração dos Fiéis Defuntos, 3ª Missa",
              weekday: 6,
            },
          ],
          commemoration: [],
          date: "2024-11-02",
          tempora: [
            {
              colors: ["g"],
              date: "2024-11-02",
              flexibility: "tempora",
              id: "tempora:Pent23-6:4:g",
              name: "Pent23-6",
              priority: 80,
              rank: 4,
              title: "Sábado da 23ª semana depois de Pentecostes",
              weekday: 6,
            },
          ],
        },
        id: "sancti:11-02m1:1:b",
        rank: 1,
        tempora: "Sábado da 23ª semana depois de Pentecostes",
        title: "Comemoração dos Fiéis Defuntos, 1ª Missa",
      },
      sections: [
        {
          body: {
            latin: [
              "In Commemoratione Omnium Fidelium Defunctorum Ad primam Missam;;Duplex;;3;;ex C9",
              "",
            ],
            vernacular: [
              "In Commemoratione Omnium Fidelium Defunctorum Ad primam Missam;;Duplex;;3;;ex C9",
              "",
            ],
          },
          id: "Rank",
        },
        {
          body: {
            latin: undefined,
            vernacular: [
              "Commemoratione Omnium Fidelium Defunctorum Ad primam Missam;;Duplex Solemnity;;6;;ex C9",
              "",
            ],
          },
          id: "RankNewcal",
        },
        {
          body: {
            latin: undefined,
            vernacular: [
              "In Commemoratione Omnium Fidelium Defunctorum Ad primam Missam;;I. classis;;6;;ex C9",
              "",
              "",
            ],
          },
          id: "Rank1960",
        },
        {
          body: {
            latin: [
              "ex C9",
              "no Gloria",
              "no Credo",
              "Prefatio=Defunctorum",
              "multiple3",
              "Sequentia",
              "",
            ],
            vernacular: [
              "ex C9",
              "no Gloria",
              "no Credo",
              "Prefatioo=Defunctorum",
              "multiple3",
              "Sequentia",
              "Requiem gloria",
              "",
            ],
          },
          id: "Rule",
        },
        {
          body: {
            latin: undefined,
            vernacular: [
              "## 02 XI – Comemoração dos Fiéis Defuntos - 1ª Missa",
              "1 classe",
              "Paramentos vermelhos",
              "",
            ],
          },
          id: "Comment",
        },
        {
          body: {
            latin: ["Missa Defunctorum quotidianis, Requiem aeternam", ""],
            vernacular: ["Missa Defunctorum quotidianis, Requiem aeternam", ""],
          },
          id: "Name",
        },
        {
          body: {
            latin: [
              "4 Esdr 2:34; 2:35",
              "Réquiem ætérnam dona eis, Dómine: et lux perpétua lúceat eis.",
              "Ps 64:2-3",
              "Te decet hymnus, Deus, in Sion, et tibi reddétur votum in Jerúsalem: exáudi oratiónem meam, ad te omnis caro véniet.",
              "Réquiem ætérnam dona eis, Dómine: et lux perpétua lúceat eis.",
              "",
            ],
            vernacular: [
              "4 Ezd 2:34; 2:35",
              "Dai-lhes, Senhor, o eterno repouso, e que lhes resplandeça a luz perpétua.",
              "Sl 64:2-3",
              "A Vós, Senhor, dirigimos estes hinos em Sião: e oferecemos estes votos em Jerusalém: ouvi a minha oração: todas as criaturas devem comparecer ante Vós.",
              "Dai-lhes, Senhor, o eterno repouso, e que lhes resplandeça a luz perpétua.",
              "",
            ],
          },
          id: "Introitus",
        },
        {
          body: {
            latin: [
              "Fidélium, Deus, ómnium Cónditor et Redémptor: animábus famulórum famularúmque tuárum remissiónem cunctórum tríbue peccatórum; ut indulgéntiam, quam semper optavérunt, piis supplicatiónibus consequántur:",
              "Qui vivis…",
              "",
            ],
            vernacular: [
              "Ó Deus, Criador e Redentor de todos os fiéis, concedei às almas dos vossos servos a remissão de todos seus pecados, a fim de que pelas nossas humilíssimas orações alcancem da vossa misericórdia o perdão que sempre desejaram.",
              "Ó Vós, que viveis...",
              "",
            ],
          },
          id: "Oratio",
        },
        {
          body: {
            latin: [
              "Léctio Epístolæ beáti Pauli Apóstoli ad Corínthios",
              "1 Cor 15:51-57",
              "Fratres: Ecce, mystérium vobis dico: Omnes quidem resurgámus, sed non omnes immutábimur. In moménto, in ictu óculi, in novíssima tuba: canet enim tuba, et mórtui resúrgent incorrúpti: et nos immutábimur. Opórtet enim corruptíbile hoc induere incorruptiónem: et mortále hoc indúere immortalitátem. Cum autem mortále hoc indúerit immortalitátem, tunc fiet sermo, qui scriptus est: Absórpta est mors in victória. Ubi est, mors, victória tua? Ubi est, mors, stímulus tuus? Stímulus autem mortis peccátum est: virtus vero peccáti lex. Deo autem grátias, qui dedit nobis victóriam per Dóminum nostrum Jesum Christum.",
              "",
            ],
            vernacular: [
              "Lição da Ep.ª do B. Ap.º Paulo aos Coríntios.",
              "1 Cor 15:51-57",
              "Irmãos: Eis um mystério que vos revelo: Ressuscitaremos todos certamente; mas não seremos todos mudados. Num instante, num abrir e fechar de olhos, ao som da última trombeta, porque, então a trombeta soará e os mortos ressuscitarão incorruptíveis, e nós seremos transmudados. Pois é preciso que este corpo corruptível se revista da incorruptibilidade, e que este corpo mortal se revista da imortalidade. Quando este corpo corruptível se revestir da incorruptibilidade e este corpo mortal se revestir da imortalidade, então se cumprirá a palavra que está escrita: «A morte foi absorvida pela vitória. Onde está, ó morte, a tua vitória? Onde está, ó morte, o teu aguilhão?». Ora, o aguilhão da morte é o pecado; e a força do pecado é a lei. Graças, pois, sejam rendidas a Deus, que nos concedeu a vitória por Jesus Cristo, Senhor nosso.",
              "",
            ],
          },
          id: "Lectio",
        },
        {
          body: {
            latin: [
              "4 Esdr 2:34 et 35.",
              "Réquiem ætérnam dona eis, Dómine: et lux perpétua lúceat eis.",
              "Ps 111:7.",
              "℣. In memória ætérna erit justus: ab auditióne mala non timébit.",
              "",
              "Tractus.",
              "Absólve, Dómine, ánimas ómnium fidélium ab omni vínculo delictórum.",
              "℣. Et grátia tua illis succurrénte, mereántur evádere judícium ultiónis.",
              "℣. Et lucis ætérnæ beatitúdine pérfrui.",
              "",
            ],
            vernacular: [
              "4 Ezdr 2:34-35",
              "Dai-lhes, Senhor, o eterno repouso, e que lhes resplandeça a luz perpétua.",
              "Sl 111:7",
              "℣. A recordação do homem justo permanecerá eternamente; este não temerá ouvir as sentenças más dos homens.",
              "",
              "Tractus",
              "Livrai, Senhor, as almas dos fiéis defuntos das cadeias dos seus pecados:",
              "℣. E que com o socorro da vossa graça consigam evitar o juízo da vingança:",
              "℣. E gozem a bem-aventurança da luz eterna.",
              "",
            ],
          },
          id: "Graduale",
        },
        {
          body: {
            latin: [
              "Dies iræ, dies illa",
              "Solvet sæclum in favílla:",
              "Teste David cum Sibýlla.",
              "",
              "Quantus tremor est futúrus,",
              "Quando judex est ventúrus,",
              "Cuncta stricte discussúrus!",
              "",
              "Tuba mirum spargens sonum",
              "Per sepúlcra regiónum,",
              "Coget omnes ante thronum.",
              "",
              "Mors stupébit et natúra,",
              "Cum resúrget creatúra,",
              "Judicánti responsúra.",
              "",
              "Liber scriptus proferétur,",
              "In quo totum continétur,",
              "Unde mundus judicétur.",
              "",
              "Judex ergo cum sedébit,",
              "Quidquid latet, apparébit:",
              "Nil inúltum remanébit.",
              "",
              "Quid sum miser tunc dictúrus?",
              "Quem patrónum rogatúrus,",
              "Cum vix justus sit secúrus?",
              "",
              "Rex treméndæ majestátis,",
              "Qui salvándos salvas gratis,",
              "Salva me, fons pietátis.",
              "",
              "Recordáre, Jesu pie,",
              "Quod sum causa tuæ viæ:",
              "Ne me perdas illa die.",
              "",
              "Quærens me, sedísti lassus:",
              "Redemísti Crucem passus:",
              "Tantus labor non sit cassus.",
              "",
              "Juste judex ultiónis,",
              "Donum fac remissiónis",
              "Ante diem ratiónis.",
              "",
              "Ingemísco, tamquam reus:",
              "Culpa rubet vultus meus:",
              "Supplicánti parce, Deus.",
              "",
              "Qui Maríam absolvísti,",
              "Et latrónem exaudísti,",
              "Mihi quoque spem dedísti.",
              "",
              "Preces meæ non sunt dignæ:",
              "Sed tu bonus fac benígne,",
              "Ne perénni cremer igne.",
              "",
              "Inter oves locum præsta,",
              "Et ab hœdis me sequéstra,",
              "Státuens in parte dextra.",
              "",
              "Confutátis maledíctis,",
              "Flammis ácribus addíctis:",
              "Voca me cum benedíctis.",
              "",
              "Oro supplex et acclínis,",
              "Cor contrítum quasi cinis:",
              "Gere curam mei finis.",
              "",
              "Lacrimósa dies illa,",
              "Qua resúrget ex favílla",
              "Judicándus homo reus.",
              "",
              "Huic ergo parce, Deus:",
              "Pie Jesu Dómine,",
              "Dona eis réquiem.",
              "Amen.",
              "",
            ],
            vernacular: [
              "Dia da ira aquele dia",
              "em que o universo será reduzido a cinzas,",
              "segundo as profecias de David e Sibila.",
              "",
              "Qual não será o terror dos homens",
              "quando o soberano Juiz vier examinar",
              "todas as acções com rigor!",
              "",
              "O som estridente da trombeta acordará os mortos,",
              "nas profundezas das sepulturas,",
              "reunindo-os todos diante do trono do Senhor.",
              "",
              "A morte e a natureza ficarão estupefactas",
              "quando a criatura comparecer",
              "para ser julgada pelo Juiz.",
              "",
              "Um livro aparecerá,",
              "onde está escrito tudo sobre o que há-de consistir",
              "o julgamento do mundo.",
              "",
              "Quando o Juiz se assentar no tribunal,",
              "tudo o que estiver oculto ficará descoberto,",
              "e nenhum crime ficará impune.",
              "",
              "Infeliz de mim! Que poderei dizer então?",
              "Que protector procurarei,",
              "quando somente o justo está tranquilo?!",
              "",
              "Ó Rei, cuja majestade é tremenda,",
              "mas que salvais, gratuitamente, os escolhidos,",
              "salvai-me, ó fonte de piedade!",
              "",
              "Recordai-Vos, ó piíssimo Jesus,",
              "de que vieste ao mundo por minha causa:",
              "não me condeneis nesse dia.",
              "",
              "Ó Vós, que Vos fatigastes em minha procura",
              "e que para me resgatardes morrestes na Cruz:",
              "não queirais que fiquem infrutíferos tantos esforços.",
              "",
              "Ó justo Juiz, que castigais com justiça,",
              "concedei-me o perdão das minhas faltas",
              "antes do dia do julgamento.",
              "",
              "Eu choro, como réu;",
              "as minhas culpas envergonham-me.",
              "Ó Deus, que minhas súplicas me alcancem perdão.",
              "",
              "Ó Vós, que absolvestes Maria",
              "e ouvistes o ladrão,",
              "e me concedestes também a esperança!",
              "",
              "Bem sei que minhas preces não são dignas;",
              "mas Vós, que sois bom,",
              "não consintais que eu arda no fogo eterno.",
              "",
              "Colocai-me entre os cordeiros,",
              "à vossa direita,",
              "e separai-me dos pecadores.",
              "",
              "Livrai-me da confusão",
              "e do suplicio dos malditos condenados",
              "e introduzi-me junto dos benditos de vosso Pai.",
              "",
              "Prostrado ante Vós, suplicante,",
              "com o coração esmagado, como reduzido a cinzas,",
              "Vos imploro, ó da morte.",
              "",
              "Dia de lágrimas aquele em",
              "que o homem renasça da sua cinza",
              "para ser julgado!",
              "",
              "Tende, pois, piedade dele, ó meu Deus!",
              "Ó piíssimo Jesus, ó Senhor,",
              "concedei-lhe o repouso eterno.",
              "Amen.",
              "",
            ],
          },
          id: "Sequentia",
        },
        {
          body: {
            latin: [
              "Sequéntia ☩ sancti Evangélii secúndum Joánnem",
              "Joann 5:25-29",
              "In illo témpore: Dixit Jesus turbis Judæórum: Amen, amen, dico vobis, quia venit hora, et nunc est, quando mórtui áudient vocem Fílii Dei: et qui audíerint, vivent. Sicut enim Pater habet vitam in semetípso, sic dedit et Fílio habére vitam in semetípso: et potestátem dedit ei judícium fácere, quia Fílius hóminis est. Nolíte mirári hoc, quia venit hora, in qua omnes, qui in monuméntis sunt, áudient vocem Fílii Dei: et procédent, qui bona fecérunt, in resurrectiónem vitæ: qui vero mala egérunt, in resurrectiónem judícii.",
              "",
            ],
            vernacular: [
              "Continuação ☩ do santo Evangelho segundo S. João.",
              "Jo 5:25-29",
              "Naquele tempo, disse Jesus às turbas dos judeus: «Em verdade, em verdade vos digo: A hora chega (ela chegou já) em que os mortos ouvirão a voz do Filho de Deus; e os que a ouvirem, viverão. Porque, assim como o Pai tem a vida em si, assim Ele deu ao Filho o poder de ter a vida em si; e deu-lhe, também, o poder de julgar, pois Ele é o Filho do homem. Não vos admireis disto, pois vem a hora em que todos aqueles que estão nos túmulos ouvirão a voz do Filho de Deus. Então, aqueles que tiverem praticado obras boas sairão para a ressurreição da vida eterna; e aqueles que tiverem praticado obras más ressuscitarão para a condenação».",
              "",
            ],
          },
          id: "Evangelium",
        },
        {
          body: {
            latin: [
              "Dómine Jesu Christe, Rex glóriæ, líbera ánimas ómnium fidélium defunctórum de pœnis inférni et de profúndo lacu: líbera eas de ore leónis, ne absórbeat eas tártarus, ne cadant in obscúrum: sed sígnifer sanctus Míchaël repræséntet eas in lucem sanctam:",
              "* Quam olim Abrahæ promisísti et sémini ejus.",
              "℣. Hóstias et preces tibi, Dómine, laudis offérimus: tu súscipe pro animábus illis, quarum hódie memóriam fácimus: fac eas, Dómine, de morte transíre ad vitam.",
              "* Quam olim Abrahæ promisísti et sémini ejus.",
              "",
            ],
            vernacular: [
              "Senhor Jesus Cristo, Rei da glória, livrai as almas de todos os fiéis defuntos das penas do inferno e do lago profundo; livrai-as da boca do leão; que o inferno as não sepulte, nem elas se abismem nas trevas desse lugar tremendo; mas que S. Miguel, que é o porta-estandarte divino, as conduza até à luz santa. Como outrora prometestes a Abraão e à sua posteridade.",
              "℣. Vos oferecemos, Senhor, estas hóstias e estas orações de louvor: aceitai-as pelas almas daqueles que hoje comemoramos, e fazei-as passar da morte à vida: Como outrora prometestes a Abraão e à sua posteridade.",
              "",
            ],
          },
          id: "Offertorium",
        },
        {
          body: {
            latin: [
              "Hóstias, quǽsumus, Dómine, quas tibi pro animábus famulórum famularúmque tuárum offérimus, propitiátus inténde: ut, quibus fídei christiánæ méritum contulísti, dones et prǽmium.",
              "Per Dominum…",
              "",
            ],
            vernacular: [
              "Olhai benigno, Senhor, Vos suplicamos, para as hóstias que Vos oferecemos pelas almas dos vossos servos, a fim de que, depois de lhes haverdes concedido o dom da fé cristã, lhes proporcioneis a recompensa.",
              "Por nosso Senhor...",
              "",
            ],
          },
          id: "Secreta",
        },
        {
          body: {
            latin: [
              "Defunctorum",
              "Vere dignum et justum est, æquum et salutáre, nos tibi semper et ubíque grátias ágere: Dómine sancte, Pater omnípotens, ætérne Deus: per Christum, Dóminum nostrum. In quo nobis spes beátæ resurrectiónis effúlsit, ut, quos contrístat certa moriéndi condício, eósdem consolétur futúræ immortalitátis promíssio. Tuis enim fidélibus, Dómine, vita mutátur, non tóllitur: et, dissolúta terréstris hujus incolátus domo, ætérna in cælis habitátio comparátur. Et ídeo cum Angelis et Archángelis, cum Thronis et Dominatiónibus cumque omni milítia cœléstis exércitus hymnum glóriæ tuæ cánimus, sine fine dicéntes:",
              "",
            ],
            vernacular: [
              "dos Defuntos",
              "É verdadeiramente digno e justo, racional e salutar que sempre e em todos os lugares Vos dêmos graças, Senhor santo, Pai omnipotente, eterno Deus, por meio de nosso Senhor Jesus Cristo, em quem nos concedestes a esperança da feliz ressurreição; de sorte que, conquanto a condição certa da nossa morte nos entristeça, fiquemos consolados com a promessa da imortalidade futura. Pois, para os vossos fiéis, Senhor, a vida muda-se, não se acaba; e, desfeita esta Inorada terrena, adquire-se a habitação eterna nos céus. E, por isso, com os Anjos e Arcanjos, com os Tronos e Dominações e com toda a milícia do exército celestial, cantamos o hino da vossa glória, dizendo sem cessar:",
              "",
              "",
            ],
          },
          id: "Prefatio",
        },
        {
          body: {
            latin: [
              "4 Esdr 2:35; 2:34",
              "Lux ætérna lúceat eis, Dómine:",
              "* Cum Sanctis tuis in ætérnum: quia pius es.",
              "℣. Requiem ætérnam dona eis, Dómine: et lux perpétua lúceat eis.",
              "* Cum Sanctis tuis in ætérnum: quia pius es.",
              "",
            ],
            vernacular: [
              "4 Ezdr 2:35; 2:34",
              "Que a luz eterna lhes resplandeça: Com os vossos Santos em todos os séculos, ó Senhor, pois sois bom.",
              "℣. Dai-lhes, Senhor, o eterno repouso, e que a luz perpétua lhes resplandeça: Com os vossos santos em todos os séculos, ó Senhor, pois sois misericordioso.",
              "",
              "",
            ],
          },
          id: "Communio",
        },
        {
          body: {
            latin: [
              "Animábus, quǽsumus, Dómine, famulórum famularúmque tuárum orátio profíciat supplicántium: ut eas et a peccátis ómnibus éxuas, et tuæ redemptiónis fácias esse partícipes:",
              "Qui vivis…",
              "",
            ],
            vernacular: [
              "Que as nossas humildes preces sejam proveitosas às almas dos vossos servos e servas, a fim de que, soltas das cadeias dos seus pecados, participem dos frutos da vossa redenção.",
              "Ó Vós, que viveis...",
              "",
            ],
          },
          id: "Postcommunio",
        },
      ],
    },
    {
      info: {
        colors: ["b"],
        date: "2024-11-02",
        day: {
          celebration: [
            {
              colors: ["b"],
              date: "2024-11-02",
              flexibility: "sancti",
              id: "sancti:11-02m1:1:b",
              name: "11-02m1",
              priority: 25,
              rank: 1,
              title: "Comemoração dos Fiéis Defuntos, 1ª Missa",
              weekday: 6,
            },
            {
              colors: ["b"],
              date: "2024-11-02",
              flexibility: "sancti",
              id: "sancti:11-02m2:1:b",
              name: "11-02m2",
              priority: 26,
              rank: 1,
              title: "Comemoração dos Fiéis Defuntos, 2ª Missa",
              weekday: 6,
            },
            {
              colors: ["b"],
              date: "2024-11-02",
              flexibility: "sancti",
              id: "sancti:11-02m3:1:b",
              name: "11-02m3",
              priority: 27,
              rank: 1,
              title: "Comemoração dos Fiéis Defuntos, 3ª Missa",
              weekday: 6,
            },
          ],
          commemoration: [],
          date: "2024-11-02",
          tempora: [
            {
              colors: ["g"],
              date: "2024-11-02",
              flexibility: "tempora",
              id: "tempora:Pent23-6:4:g",
              name: "Pent23-6",
              priority: 80,
              rank: 4,
              title: "Sábado da 23ª semana depois de Pentecostes",
              weekday: 6,
            },
          ],
        },
        id: "sancti:11-02m2:1:b",
        rank: 1,
        tempora: "Sábado da 23ª semana depois de Pentecostes",
        title: "Comemoração dos Fiéis Defuntos, 2ª Missa",
      },
      sections: [
        {
          body: {
            latin: [
              "In Commemoratione Omnium Fidelium Defunctorum Ad secundam Missam;;Duplex;;3;;ex C9",
              "",
            ],
            vernacular: [
              "In Commemoratione Omnium Fidelium Defunctorum Ad secundam Missam;;Duplex;;3;;ex C9",
              "",
            ],
          },
          id: "Rank",
        },
        {
          body: {
            latin: undefined,
            vernacular: [
              "In Commemoratione Omnium Fidelium Defunctorum Ad secundam Missam;;Duplex Solemnity;;6;;ex C9",
              "",
            ],
          },
          id: "RankNewcal",
        },
        {
          body: {
            latin: undefined,
            vernacular: [
              "In Commemoratione Omnium Fidelium Defunctorum Ad secundam Missam;;I. classis;;6;;ex C9",
              "",
            ],
          },
          id: "Rank1960",
        },
        {
          body: {
            latin: [
              "ex C9",
              "no Gloria",
              "no Credo",
              "Prefatio=Defunctorum",
              "multiple3",
              "Sequentia",
              "",
            ],
            vernacular: [
              "ex C9",
              "no Gloria",
              "no Credo",
              "Prefatio=Defunctorum",
              "multiple3",
              "Sequentia",
              "Requiem gloria",
              "",
            ],
          },
          id: "Rule",
        },
        {
          body: {
            latin: undefined,
            vernacular: [
              "## 02 XI – Comemoração dos Fiéis Defuntos - 2ª Missa",
              "",
            ],
          },
          id: "Comment",
        },
        {
          body: {
            latin: ["Missa Defunctorum quotidianis, Requiem aeternam", ""],
            vernacular: ["Missa Defunctorum quotidianis, Requiem aeternam", ""],
          },
          id: "Name",
        },
        {
          body: {
            latin: [
              "4 Esdr 2:34; 2:35",
              "Réquiem ætérnam dona eis, Dómine: et lux perpétua lúceat eis.",
              "Ps 64:2-3",
              "Te decet hymnus, Deus, in Sion, et tibi reddétur votum in Jerúsalem: exáudi oratiónem meam, ad te omnis caro véniet.",
              "Réquiem ætérnam dona eis, Dómine: et lux perpétua lúceat eis.",
              "",
            ],
            vernacular: [
              "4 Ezd 2:34; 2:35",
              "Dai-lhes, Senhor, o eterno repouso, e que lhes resplandeça a luz perpétua.",
              "Sl 64:2-3",
              "A Vós, Senhor, dirigimos estes hinos em Sião: e oferecemos estes votos em Jerusalém: ouvi a minha oração: todas as criaturas devem comparecer ante Vós.",
              "Dai-lhes, Senhor, o eterno repouso, e que lhes resplandeça a luz perpétua.",
              "",
              "",
            ],
          },
          id: "Introitus",
        },
        {
          body: {
            latin: [
              "Deus, indulgentiárum Dómine: da animábus famulórum famularúmque tuárum refrigérii sedem, quiétis beatitúdinem et lúminis claritátem.",
              "Per Dominum…",
              "",
            ],
            vernacular: [
              "Ó Deus, Senhor das misericórdias, concedei às almas dos vossos servos o lugar do refrigério, a bem-aventurança do repouso e o esplendor da luz.",
              "Por nosso Senhor...",
              "",
            ],
          },
          id: "Oratio",
        },
        {
          body: {
            latin: [
              "Léctio libri Machabæórum",
              "2 Mach 12:43-46",
              "In diébus illis: Vir fortíssimus Judas, facta collatióne, duódecim mília drachmas argénti misit Jerosólymam, offérri pro peccátis mortuórum sacrifícium, bene et religióse de resurrectióne cógitans, nisi enim eos, qui cecíderant, resurrectúros speráret, supérfluum viderétur et vanum oráre pro mórtuis: et quia considerábat, quod hi, qui cum pietáte dormitiónem accéperant, óptimam habérent repósitam grátiam. Sancta ergo et salúbris est cogitátio pro defunctis exoráre, ut a peccátis solvántur.",
              "",
            ],
            vernacular: [
              "Lição do livro dos Macabeus.",
              "2 Mac 12:43-46",
              "Naqueles dias, um varão forte chamado Judas, havendo feito um peditório, recolheu a quantia de doze mil dracmas de prata, que enviou para Jerusalém, para ser oferecido um sacrifício pelos pecados dos mortos; pois ele possuía bons e religiosos pensamentos acerca da ressurreição (e, com efeito, se ele não esperasse que aqueles que haviam sucumbido ressuscitassem um dia, teria pensado que era vão e supérfluo orar pelos mortos). Assim, acreditava que abundante misericórdia estava reservada para aqueles que morressem piedosamente. Na verdade, é um santo e salutar pensamento orar pelos mortos, para que sejam livres dos seus pecados.",
              "",
            ],
          },
          id: "Lectio",
        },
        {
          body: {
            latin: [
              "4 Esdr 2:34 et 35.",
              "Réquiem ætérnam dona eis, Dómine: et lux perpétua lúceat eis.",
              "Ps 111:7.",
              "℣. In memória ætérna erit justus: ab auditióne mala non timébit.",
              "",
              "Tractus.",
              "Absólve, Dómine, ánimas ómnium fidélium ab omni vínculo delictórum.",
              "℣. Et grátia tua illis succurrénte, mereántur evádere judícium ultiónis.",
              "℣. Et lucis ætérnæ beatitúdine pérfrui.",
              "",
            ],
            vernacular: [
              "4 Ezdr 2:34-35",
              "Dai-lhes, Senhor, o eterno repouso, e que lhes resplandeça a luz perpétua.",
              "Sl 111:7",
              "℣. A recordação do homem justo permanecerá eternamente; este não temerá ouvir as sentenças más dos homens.",
              "",
              "Tractus",
              "Livrai, Senhor, as almas dos fiéis defuntos das cadeias dos seus pecados:",
              "℣. E que com o socorro da vossa graça consigam evitar o juízo da vingança:",
              "℣. E gozem a bem-aventurança da luz eterna.",
              "",
              "",
            ],
          },
          id: "Graduale",
        },
        {
          body: {
            latin: [
              "Dies iræ, dies illa",
              "Solvet sæclum in favílla:",
              "Teste David cum Sibýlla.",
              "",
              "Quantus tremor est futúrus,",
              "Quando judex est ventúrus,",
              "Cuncta stricte discussúrus!",
              "",
              "Tuba mirum spargens sonum",
              "Per sepúlcra regiónum,",
              "Coget omnes ante thronum.",
              "",
              "Mors stupébit et natúra,",
              "Cum resúrget creatúra,",
              "Judicánti responsúra.",
              "",
              "Liber scriptus proferétur,",
              "In quo totum continétur,",
              "Unde mundus judicétur.",
              "",
              "Judex ergo cum sedébit,",
              "Quidquid latet, apparébit:",
              "Nil inúltum remanébit.",
              "",
              "Quid sum miser tunc dictúrus?",
              "Quem patrónum rogatúrus,",
              "Cum vix justus sit secúrus?",
              "",
              "Rex treméndæ majestátis,",
              "Qui salvándos salvas gratis,",
              "Salva me, fons pietátis.",
              "",
              "Recordáre, Jesu pie,",
              "Quod sum causa tuæ viæ:",
              "Ne me perdas illa die.",
              "",
              "Quærens me, sedísti lassus:",
              "Redemísti Crucem passus:",
              "Tantus labor non sit cassus.",
              "",
              "Juste judex ultiónis,",
              "Donum fac remissiónis",
              "Ante diem ratiónis.",
              "",
              "Ingemísco, tamquam reus:",
              "Culpa rubet vultus meus:",
              "Supplicánti parce, Deus.",
              "",
              "Qui Maríam absolvísti,",
              "Et latrónem exaudísti,",
              "Mihi quoque spem dedísti.",
              "",
              "Preces meæ non sunt dignæ:",
              "Sed tu bonus fac benígne,",
              "Ne perénni cremer igne.",
              "",
              "Inter oves locum præsta,",
              "Et ab hœdis me sequéstra,",
              "Státuens in parte dextra.",
              "",
              "Confutátis maledíctis,",
              "Flammis ácribus addíctis:",
              "Voca me cum benedíctis.",
              "",
              "Oro supplex et acclínis,",
              "Cor contrítum quasi cinis:",
              "Gere curam mei finis.",
              "",
              "Lacrimósa dies illa,",
              "Qua resúrget ex favílla",
              "Judicándus homo reus.",
              "",
              "Huic ergo parce, Deus:",
              "Pie Jesu Dómine,",
              "Dona eis réquiem.",
              "Amen.",
              "",
            ],
            vernacular: [
              "Dia da ira aquele dia",
              "em que o universo será reduzido a cinzas,",
              "segundo as profecias de David e Sibila.",
              "",
              "Qual não será o terror dos homens",
              "quando o soberano Juiz vier examinar",
              "todas as acções com rigor!",
              "",
              "O som estridente da trombeta acordará os mortos,",
              "nas profundezas das sepulturas,",
              "reunindo-os todos diante do trono do Senhor.",
              "",
              "A morte e a natureza ficarão estupefactas",
              "quando a criatura comparecer",
              "para ser julgada pelo Juiz.",
              "",
              "Um livro aparecerá,",
              "onde está escrito tudo sobre o que há-de consistir",
              "o julgamento do mundo.",
              "",
              "Quando o Juiz se assentar no tribunal,",
              "tudo o que estiver oculto ficará descoberto,",
              "e nenhum crime ficará impune.",
              "",
              "Infeliz de mim! Que poderei dizer então?",
              "Que protector procurarei,",
              "quando somente o justo está tranquilo?!",
              "",
              "Ó Rei, cuja majestade é tremenda,",
              "mas que salvais, gratuitamente, os escolhidos,",
              "salvai-me, ó fonte de piedade!",
              "",
              "Recordai-Vos, ó piíssimo Jesus,",
              "de que vieste ao mundo por minha causa:",
              "não me condeneis nesse dia.",
              "",
              "Ó Vós, que Vos fatigastes em minha procura",
              "e que para me resgatardes morrestes na Cruz:",
              "não queirais que fiquem infrutíferos tantos esforços.",
              "",
              "Ó justo Juiz, que castigais com justiça,",
              "concedei-me o perdão das minhas faltas",
              "antes do dia do julgamento.",
              "",
              "Eu choro, como réu;",
              "as minhas culpas envergonham-me.",
              "Ó Deus, que minhas súplicas me alcancem perdão.",
              "",
              "Ó Vós, que absolvestes Maria",
              "e ouvistes o ladrão,",
              "e me concedestes também a esperança!",
              "",
              "Bem sei que minhas preces não são dignas;",
              "mas Vós, que sois bom,",
              "não consintais que eu arda no fogo eterno.",
              "",
              "Colocai-me entre os cordeiros,",
              "à vossa direita,",
              "e separai-me dos pecadores.",
              "",
              "Livrai-me da confusão",
              "e do suplicio dos malditos condenados",
              "e introduzi-me junto dos benditos de vosso Pai.",
              "",
              "Prostrado ante Vós, suplicante,",
              "com o coração esmagado, como reduzido a cinzas,",
              "Vos imploro, ó da morte.",
              "",
              "Dia de lágrimas aquele em",
              "que o homem renasça da sua cinza",
              "para ser julgado!",
              "",
              "Tende, pois, piedade dele, ó meu Deus!",
              "Ó piíssimo Jesus, ó Senhor,",
              "concedei-lhe o repouso eterno.",
              "Amen.",
              "",
              "",
            ],
          },
          id: "Sequentia",
        },
        {
          body: {
            latin: [
              "Sequéntia ☩ sancti Evangélii secúndum Joánnem",
              "Joann 6:37-40",
              "In illo témpore: Dixit Jesus turbis Judæórum: Omne, quod dat mihi Pater, ad me véniet: et eum, qui venit ad me, non ejíciam foras: quia descéndi de cælo, non ut fáciam voluntátem meam, sed voluntátem ejus, qui misit me. Hæc est autem volúntas ejus, qui misit me, Patris: ut omne, quod dedit mihi, non perdam ex eo, sed resúscitem illud in novíssimo die. Hæc est autem volúntas Patris mei, qui misit me: ut omnis, qui videt Fílium et credit in eum, hábeat vitam ætérnam, et ego resuscitábo eum in novíssimo die.",
              "",
            ],
            vernacular: [
              "Continuação ☩ do santo Evangelho segundo S. João.",
              "Jo 6:37-40",
              "Naquele tempo, disse Jesus à multidão dos judeus: «Todo o que o Pai me dá, virá a mim; e o que vem a mim o não desprezarei; porquanto desci do céu, não para fazer a minha vontade, mas de quem me enviou. Ora, a vontade de meu Pai, que me enviou, é que não perca nenhum daqueles que me deu, mas que os ressuscite no último dia. Esta é a vontade de meu Pai, que me enviou: que todo aquele que vê o Filho e acredita n’Ele alcance a vida eterna; e Eu o ressuscitarei no último dia».",
              "",
            ],
          },
          id: "Evangelium",
        },
        {
          body: {
            latin: [
              "Dómine Jesu Christe, Rex glóriæ, líbera ánimas ómnium fidélium defunctórum de pœnis inférni et de profúndo lacu: líbera eas de ore leónis, ne absórbeat eas tártarus, ne cadant in obscúrum: sed sígnifer sanctus Míchaël repræséntet eas in lucem sanctam:",
              "* Quam olim Abrahæ promisísti et sémini ejus.",
              "℣. Hóstias et preces tibi, Dómine, laudis offérimus: tu súscipe pro animábus illis, quarum hódie memóriam fácimus: fac eas, Dómine, de morte transíre ad vitam.",
              "* Quam olim Abrahæ promisísti et sémini ejus.",
              "",
            ],
            vernacular: [
              "Senhor Jesus Cristo, Rei da glória, livrai as almas de todos os fiéis defuntos das penas do inferno e do lago profundo; livrai-as da boca do leão; que o inferno as não sepulte, nem elas se abismem nas trevas desse lugar tremendo; mas que S. Miguel, que é o porta-estandarte divino, as conduza até à luz santa. Como outrora prometestes a Abraão e à sua posteridade.",
              "℣. Vos oferecemos, Senhor, estas hóstias e estas orações de louvor: aceitai-as pelas almas daqueles que hoje comemoramos, e fazei-as passar da morte à vida: Como outrora prometestes a Abraão e à sua posteridade.",
              "",
              "",
            ],
          },
          id: "Offertorium",
        },
        {
          body: {
            latin: [
              "Propitiáre, Dómine, supplicatiónibus nostris, pro animábus famulórum famularúmque tuárum, pro quibus tibi offérimus sacrifícium laudis; ut eas Sanctórum tuórum consórtio sociáre dignéris.",
              "Per Dominum…",
              "",
            ],
            vernacular: [
              "Sede propício, Senhor, às nossas súplicas em favor das almas dos vossos servos; nós Vos oferecemos por elas este sacrifício de louvor, a fim de que Vos digneis admiti-las na companhia dos vossos santos.",
              "Por nosso Senhor...",
              "",
            ],
          },
          id: "Secreta",
        },
        {
          body: {
            latin: [
              "Defunctorum",
              "Vere dignum et justum est, æquum et salutáre, nos tibi semper et ubíque grátias ágere: Dómine sancte, Pater omnípotens, ætérne Deus: per Christum, Dóminum nostrum. In quo nobis spes beátæ resurrectiónis effúlsit, ut, quos contrístat certa moriéndi condício, eósdem consolétur futúræ immortalitátis promíssio. Tuis enim fidélibus, Dómine, vita mutátur, non tóllitur: et, dissolúta terréstris hujus incolátus domo, ætérna in cælis habitátio comparátur. Et ídeo cum Angelis et Archángelis, cum Thronis et Dominatiónibus cumque omni milítia cœléstis exércitus hymnum glóriæ tuæ cánimus, sine fine dicéntes:",
              "",
            ],
            vernacular: [
              "dos Defuntos",
              "É verdadeiramente digno e justo, racional e salutar que sempre e em todos os lugares Vos dêmos graças, Senhor santo, Pai omnipotente, eterno Deus, por meio de nosso Senhor Jesus Cristo, em quem nos concedestes a esperança da feliz ressurreição; de sorte que, conquanto a condição certa da nossa morte nos entristeça, fiquemos consolados com a promessa da imortalidade futura. Pois, para os vossos fiéis, Senhor, a vida muda-se, não se acaba; e, desfeita esta Inorada terrena, adquire-se a habitação eterna nos céus. E, por isso, com os Anjos e Arcanjos, com os Tronos e Dominações e com toda a milícia do exército celestial, cantamos o hino da vossa glória, dizendo sem cessar:",
              "",
              "",
            ],
          },
          id: "Prefatio",
        },
        {
          body: {
            latin: [
              "4 Esdr 2:35; 2:34",
              "Lux ætérna lúceat eis, Dómine:",
              "* Cum Sanctis tuis in ætérnum: quia pius es.",
              "℣. Requiem ætérnam dona eis, Dómine: et lux perpétua lúceat eis.",
              "* Cum Sanctis tuis in ætérnum: quia pius es.",
              "",
            ],
            vernacular: [
              "4 Ezdr 2:35; 2:34",
              "Que a luz eterna lhes resplandeça: Com os vossos Santos em todos os séculos, ó Senhor, pois sois bom.",
              "℣. Dai-lhes, Senhor, o eterno repouso, e que a luz perpétua lhes resplandeça: Com os vossos santos em todos os séculos, ó Senhor, pois sois misericordioso.",
              "",
              "",
              "",
            ],
          },
          id: "Communio",
        },
        {
          body: {
            latin: [
              "Præsta, quǽsumus, Dómine: ut ánimæ famulórum famularúmque tuárum, his purgátæ sacrifíciis, indulgéntiam páriter et réquiem cápiant sempitérnam.",
              "Per Dominum…",
              "",
            ],
            vernacular: [
              "Senhor, Vos rogamos, permiti que a alma dos vossos servos, havendo sido purificada pela virtude destes sacrifícios, receba ao mesmo tempo a indulgência e o sempiterno perdão.",
              "Por nosso Senhor...",
              "",
            ],
          },
          id: "Postcommunio",
        },
      ],
    },
    {
      info: {
        colors: ["b"],
        date: "2024-11-02",
        day: {
          celebration: [
            {
              colors: ["b"],
              date: "2024-11-02",
              flexibility: "sancti",
              id: "sancti:11-02m1:1:b",
              name: "11-02m1",
              priority: 25,
              rank: 1,
              title: "Comemoração dos Fiéis Defuntos, 1ª Missa",
              weekday: 6,
            },
            {
              colors: ["b"],
              date: "2024-11-02",
              flexibility: "sancti",
              id: "sancti:11-02m2:1:b",
              name: "11-02m2",
              priority: 26,
              rank: 1,
              title: "Comemoração dos Fiéis Defuntos, 2ª Missa",
              weekday: 6,
            },
            {
              colors: ["b"],
              date: "2024-11-02",
              flexibility: "sancti",
              id: "sancti:11-02m3:1:b",
              name: "11-02m3",
              priority: 27,
              rank: 1,
              title: "Comemoração dos Fiéis Defuntos, 3ª Missa",
              weekday: 6,
            },
          ],
          commemoration: [],
          date: "2024-11-02",
          tempora: [
            {
              colors: ["g"],
              date: "2024-11-02",
              flexibility: "tempora",
              id: "tempora:Pent23-6:4:g",
              name: "Pent23-6",
              priority: 80,
              rank: 4,
              title: "Sábado da 23ª semana depois de Pentecostes",
              weekday: 6,
            },
          ],
        },
        id: "sancti:11-02m3:1:b",
        rank: 1,
        tempora: "Sábado da 23ª semana depois de Pentecostes",
        title: "Comemoração dos Fiéis Defuntos, 3ª Missa",
      },
      sections: [
        {
          body: {
            latin: [
              "In Commemoratione Omnium Fidelium Defunctorum Ad tertiam Missam;;Duplex;;3;;ex C9",
              "",
            ],
            vernacular: [
              "In Commemoratione Omnium Fidelium Defunctorum Ad tertiam Missam;;Duplex;;3;;ex C9",
              "",
            ],
          },
          id: "Rank",
        },
        {
          body: {
            latin: undefined,
            vernacular: [
              "In Commemoratione Omnium Fidelium Defunctorum Ad tertiam Missam;;Duplex Solemnity;;6;;ex C9",
              "",
            ],
          },
          id: "RankNewcal",
        },
        {
          body: {
            latin: undefined,
            vernacular: [
              "In Commemoratione Omnium Fidelium Defunctorum Ad tertiam Missam;;I. classis;;6;;ex C9",
              "",
            ],
          },
          id: "Rank1960",
        },
        {
          body: {
            latin: [
              "ex C9",
              "no Gloria",
              "no Credo",
              "Prefatio=Defunctorum",
              "multiple3",
              "Sequentia",
              "",
            ],
            vernacular: [
              "ex C9",
              "no Gloria",
              "no Credo",
              "Prefatio=Defunctorum",
              "multiple3",
              "Sequentia",
              "Requiem gloria",
              "",
            ],
          },
          id: "Rule",
        },
        {
          body: {
            latin: undefined,
            vernacular: [
              "## 02 XI – Comemoração dos Fiéis Defuntos - 3ª Missa",
              "",
            ],
          },
          id: "Comment",
        },
        {
          body: {
            latin: ["Missa Defunctorum quotidianis, Requiem aeternam", ""],
            vernacular: ["Missa Defunctorum quotidianis, Requiem aeternam", ""],
          },
          id: "Name",
        },
        {
          body: {
            latin: [
              "4 Esdr 2:34; 2:35",
              "Réquiem ætérnam dona eis, Dómine: et lux perpétua lúceat eis.",
              "Ps 64:2-3",
              "Te decet hymnus, Deus, in Sion, et tibi reddétur votum in Jerúsalem: exáudi oratiónem meam, ad te omnis caro véniet.",
              "Réquiem ætérnam dona eis, Dómine: et lux perpétua lúceat eis.",
              "",
            ],
            vernacular: [
              "4 Ezd 2:34; 2:35",
              "Dai-lhes, Senhor, o eterno repouso, e que lhes resplandeça a luz perpétua.",
              "Sl 64:2-3",
              "A Vós, Senhor, dirigimos estes hinos em Sião: e oferecemos estes votos em Jerusalém: ouvi a minha oração: todas as criaturas devem comparecer ante Vós.",
              "Dai-lhes, Senhor, o eterno repouso, e que lhes resplandeça a luz perpétua.",
              "",
              "",
            ],
          },
          id: "Introitus",
        },
        {
          body: {
            latin: [
              "Deus, véniæ largítor et humánæ salútis amátor: quǽsumus cleméntiam tuam; ut nostræ congregatiónis fratres, propínquos et benefactóres, qui ex hoc sǽculo transiérunt, beáta María semper Vírgine intercedénte cum ómnibus Sanctis tuis, ad perpétuæ beatitúdinis consórtium perveníre concédas.",
              "Per Dominum…",
              "",
            ],
            vernacular: [
              "Ó Deus, que perdoais aos pecadores e desejais a salvação dos homens, imploramos a vossa clemência, por intercessão da bem-aventurada Maria, sempre Virgem, e de todos os Santos, em favor dos nossos irmãos, parentes e benfeitores, que saíram deste mundo, a fim de que alcancem a bem-aventurança eterna.",
              "Por nosso Senhor...",
              "",
            ],
          },
          id: "Oratio",
        },
        {
          body: {
            latin: [
              "Léctio libri Apocalýpsis beáti Joánnis Apóstoli",
              "Apoc 14:13",
              "In diébus illis: Audívi vocem de cœlo, dicéntem mihi: Scribe: Beáti mórtui, qui in Dómino moriúntur. Amodo jam dicit Spíritus, ut requiéscant a labóribus suis: ópera enim illórum sequúntur illos.",
              "",
            ],
            vernacular: [
              "Lição do Livro do Apocalipse do B. Ap.º João.",
              "Apoc 14:13",
              "Naqueles dias, ouvi uma voz do céu que me dizia: «Escreve: Bem-aventurados os mortos, que morrem no Senhor; porquanto, diz o Espírito, eles vão logo descansar no Senhor, visto que suas obras os acompanham».",
              "",
            ],
          },
          id: "Lectio",
        },
        {
          body: {
            latin: [
              "4 Esdr 2:34 et 35.",
              "Réquiem ætérnam dona eis, Dómine: et lux perpétua lúceat eis.",
              "Ps 111:7.",
              "℣. In memória ætérna erit justus: ab auditióne mala non timébit.",
              "",
              "Tractus.",
              "Absólve, Dómine, ánimas ómnium fidélium ab omni vínculo delictórum.",
              "℣. Et grátia tua illis succurrénte, mereántur evádere judícium ultiónis.",
              "℣. Et lucis ætérnæ beatitúdine pérfrui.",
              "",
            ],
            vernacular: [
              "4 Ezdr 2:34-35",
              "Dai-lhes, Senhor, o eterno repouso, e que lhes resplandeça a luz perpétua.",
              "Sl 111:7",
              "℣. A recordação do homem justo permanecerá eternamente; este não temerá ouvir as sentenças más dos homens.",
              "",
              "Tractus",
              "Livrai, Senhor, as almas dos fiéis defuntos das cadeias dos seus pecados:",
              "℣. E que com o socorro da vossa graça consigam evitar o juízo da vingança:",
              "℣. E gozem a bem-aventurança da luz eterna.",
              "",
              "",
            ],
          },
          id: "Graduale",
        },
        {
          body: {
            latin: [
              "Dies iræ, dies illa",
              "Solvet sæclum in favílla:",
              "Teste David cum Sibýlla.",
              "",
              "Quantus tremor est futúrus,",
              "Quando judex est ventúrus,",
              "Cuncta stricte discussúrus!",
              "",
              "Tuba mirum spargens sonum",
              "Per sepúlcra regiónum,",
              "Coget omnes ante thronum.",
              "",
              "Mors stupébit et natúra,",
              "Cum resúrget creatúra,",
              "Judicánti responsúra.",
              "",
              "Liber scriptus proferétur,",
              "In quo totum continétur,",
              "Unde mundus judicétur.",
              "",
              "Judex ergo cum sedébit,",
              "Quidquid latet, apparébit:",
              "Nil inúltum remanébit.",
              "",
              "Quid sum miser tunc dictúrus?",
              "Quem patrónum rogatúrus,",
              "Cum vix justus sit secúrus?",
              "",
              "Rex treméndæ majestátis,",
              "Qui salvándos salvas gratis,",
              "Salva me, fons pietátis.",
              "",
              "Recordáre, Jesu pie,",
              "Quod sum causa tuæ viæ:",
              "Ne me perdas illa die.",
              "",
              "Quærens me, sedísti lassus:",
              "Redemísti Crucem passus:",
              "Tantus labor non sit cassus.",
              "",
              "Juste judex ultiónis,",
              "Donum fac remissiónis",
              "Ante diem ratiónis.",
              "",
              "Ingemísco, tamquam reus:",
              "Culpa rubet vultus meus:",
              "Supplicánti parce, Deus.",
              "",
              "Qui Maríam absolvísti,",
              "Et latrónem exaudísti,",
              "Mihi quoque spem dedísti.",
              "",
              "Preces meæ non sunt dignæ:",
              "Sed tu bonus fac benígne,",
              "Ne perénni cremer igne.",
              "",
              "Inter oves locum præsta,",
              "Et ab hœdis me sequéstra,",
              "Státuens in parte dextra.",
              "",
              "Confutátis maledíctis,",
              "Flammis ácribus addíctis:",
              "Voca me cum benedíctis.",
              "",
              "Oro supplex et acclínis,",
              "Cor contrítum quasi cinis:",
              "Gere curam mei finis.",
              "",
              "Lacrimósa dies illa,",
              "Qua resúrget ex favílla",
              "Judicándus homo reus.",
              "",
              "Huic ergo parce, Deus:",
              "Pie Jesu Dómine,",
              "Dona eis réquiem.",
              "Amen.",
              "",
            ],
            vernacular: [
              "Dia da ira aquele dia",
              "em que o universo será reduzido a cinzas,",
              "segundo as profecias de David e Sibila.",
              "",
              "Qual não será o terror dos homens",
              "quando o soberano Juiz vier examinar",
              "todas as acções com rigor!",
              "",
              "O som estridente da trombeta acordará os mortos,",
              "nas profundezas das sepulturas,",
              "reunindo-os todos diante do trono do Senhor.",
              "",
              "A morte e a natureza ficarão estupefactas",
              "quando a criatura comparecer",
              "para ser julgada pelo Juiz.",
              "",
              "Um livro aparecerá,",
              "onde está escrito tudo sobre o que há-de consistir",
              "o julgamento do mundo.",
              "",
              "Quando o Juiz se assentar no tribunal,",
              "tudo o que estiver oculto ficará descoberto,",
              "e nenhum crime ficará impune.",
              "",
              "Infeliz de mim! Que poderei dizer então?",
              "Que protector procurarei,",
              "quando somente o justo está tranquilo?!",
              "",
              "Ó Rei, cuja majestade é tremenda,",
              "mas que salvais, gratuitamente, os escolhidos,",
              "salvai-me, ó fonte de piedade!",
              "",
              "Recordai-Vos, ó piíssimo Jesus,",
              "de que vieste ao mundo por minha causa:",
              "não me condeneis nesse dia.",
              "",
              "Ó Vós, que Vos fatigastes em minha procura",
              "e que para me resgatardes morrestes na Cruz:",
              "não queirais que fiquem infrutíferos tantos esforços.",
              "",
              "Ó justo Juiz, que castigais com justiça,",
              "concedei-me o perdão das minhas faltas",
              "antes do dia do julgamento.",
              "",
              "Eu choro, como réu;",
              "as minhas culpas envergonham-me.",
              "Ó Deus, que minhas súplicas me alcancem perdão.",
              "",
              "Ó Vós, que absolvestes Maria",
              "e ouvistes o ladrão,",
              "e me concedestes também a esperança!",
              "",
              "Bem sei que minhas preces não são dignas;",
              "mas Vós, que sois bom,",
              "não consintais que eu arda no fogo eterno.",
              "",
              "Colocai-me entre os cordeiros,",
              "à vossa direita,",
              "e separai-me dos pecadores.",
              "",
              "Livrai-me da confusão",
              "e do suplicio dos malditos condenados",
              "e introduzi-me junto dos benditos de vosso Pai.",
              "",
              "Prostrado ante Vós, suplicante,",
              "com o coração esmagado, como reduzido a cinzas,",
              "Vos imploro, ó da morte.",
              "",
              "Dia de lágrimas aquele em",
              "que o homem renasça da sua cinza",
              "para ser julgado!",
              "",
              "Tende, pois, piedade dele, ó meu Deus!",
              "Ó piíssimo Jesus, ó Senhor,",
              "concedei-lhe o repouso eterno.",
              "Amen.",
              "",
              "",
            ],
          },
          id: "Sequentia",
        },
        {
          body: {
            latin: [
              "Sequéntia ☩ sancti Evangélii secúndum Joánnem",
              "Joann 6:51-55",
              "In illo témpore: Dixit Jesus turbis Judæórum: Ego sum panis vivus, qui de cœlo descéndi. Si quis manducáverit ex hoc pane, vivet in ætérnum: et panis, quem ego dabo, caro mea est pro mundi vita. Litigábant ergo Judæi ad ínvicem, dicéntes: Quómodo potest hic nobis carnem suam dare ad manducándum? Dixit ergo eis Jesus: Amen, amen, dico vobis: nisi manducavéritis carnem Fílii hóminis et bibéritis ejus sánguinem, non habébitis vitam in vobis. Qui mánducat meam carnem et bibit meum sánguinem, habet vitam ætérnam: et ego resuscitábo eum in novíssimo die.",
              "",
            ],
            vernacular: [
              "Continuação ☩ do santo Evangelho segundo S. João.",
              "Jo 6:51-55",
              "Naquele tempo, disse Jesus às turbas dos judeus: «Eu sou o pão vivo, que desci do céu. Se alguém comer deste pão, viverá eternamente; pois o pão que dou é a minha carne para a vida do mundo». Porém os judeus discutiam uns com os outros, dizendo: «Como pode Ele dar-nos a comer a sua carne?». Jesus respondeu-lhes: «Em verdade, em verdade vos digo: se não comerdes a carne do Filho do homem e não beberdes o seu sangue, não tereis a vida em vós. Aquele que come a minha carne e bebe o meu sangue tem a vida eterna, e Eu o ressuscitarei no último dia».",
              "",
            ],
          },
          id: "Evangelium",
        },
        {
          body: {
            latin: [
              "Dómine Jesu Christe, Rex glóriæ, líbera ánimas ómnium fidélium defunctórum de pœnis inférni et de profúndo lacu: líbera eas de ore leónis, ne absórbeat eas tártarus, ne cadant in obscúrum: sed sígnifer sanctus Míchaël repræséntet eas in lucem sanctam:",
              "* Quam olim Abrahæ promisísti et sémini ejus.",
              "℣. Hóstias et preces tibi, Dómine, laudis offérimus: tu súscipe pro animábus illis, quarum hódie memóriam fácimus: fac eas, Dómine, de morte transíre ad vitam.",
              "* Quam olim Abrahæ promisísti et sémini ejus.",
              "",
            ],
            vernacular: [
              "Senhor Jesus Cristo, Rei da glória, livrai as almas de todos os fiéis defuntos das penas do inferno e do lago profundo; livrai-as da boca do leão; que o inferno as não sepulte, nem elas se abismem nas trevas desse lugar tremendo; mas que S. Miguel, que é o porta-estandarte divino, as conduza até à luz santa. Como outrora prometestes a Abraão e à sua posteridade.",
              "℣. Vos oferecemos, Senhor, estas hóstias e estas orações de louvor: aceitai-as pelas almas daqueles que hoje comemoramos, e fazei-as passar da morte à vida: Como outrora prometestes a Abraão e à sua posteridade.",
              "",
              "",
            ],
          },
          id: "Offertorium",
        },
        {
          body: {
            latin: [
              "Deus, cujus misericórdiæ non est númerus, súscipe propítius preces humilitátis nostræ: et animábus fratrum, propinquórum et benefactórum nostrórum, quibus tui nóminis dedísti confessiónem, per hæc sacraménta salútis nostræ, cunctórum remissiónem tríbue peccatórum.",
              "Per Dominum…",
              "",
            ],
            vernacular: [
              "Ó Deus, cuja misericórdia é infinita, ouvi benigno as nossas humildes preces, e concedei, pela virtude deste sacramento da nossa salvação, o perdão dos seus pecados às almas dos nossos irmãos, parentes e benfeitores, aos quais permitistes a graça de confessarem o vosso nome.",
              "Por nosso Senhor...",
              "",
            ],
          },
          id: "Secreta",
        },
        {
          body: {
            latin: [
              "Defunctorum",
              "Vere dignum et justum est, æquum et salutáre, nos tibi semper et ubíque grátias ágere: Dómine sancte, Pater omnípotens, ætérne Deus: per Christum, Dóminum nostrum. In quo nobis spes beátæ resurrectiónis effúlsit, ut, quos contrístat certa moriéndi condício, eósdem consolétur futúræ immortalitátis promíssio. Tuis enim fidélibus, Dómine, vita mutátur, non tóllitur: et, dissolúta terréstris hujus incolátus domo, ætérna in cælis habitátio comparátur. Et ídeo cum Angelis et Archángelis, cum Thronis et Dominatiónibus cumque omni milítia cœléstis exércitus hymnum glóriæ tuæ cánimus, sine fine dicéntes:",
              "",
            ],
            vernacular: [
              "dos Defuntos",
              "É verdadeiramente digno e justo, racional e salutar que sempre e em todos os lugares Vos dêmos graças, Senhor santo, Pai omnipotente, eterno Deus, por meio de nosso Senhor Jesus Cristo, em quem nos concedestes a esperança da feliz ressurreição; de sorte que, conquanto a condição certa da nossa morte nos entristeça, fiquemos consolados com a promessa da imortalidade futura. Pois, para os vossos fiéis, Senhor, a vida muda-se, não se acaba; e, desfeita esta Inorada terrena, adquire-se a habitação eterna nos céus. E, por isso, com os Anjos e Arcanjos, com os Tronos e Dominações e com toda a milícia do exército celestial, cantamos o hino da vossa glória, dizendo sem cessar:",
              "",
              "",
            ],
          },
          id: "Prefatio",
        },
        {
          body: {
            latin: [
              "4 Esdr 2:35; 2:34",
              "Lux ætérna lúceat eis, Dómine:",
              "* Cum Sanctis tuis in ætérnum: quia pius es.",
              "℣. Requiem ætérnam dona eis, Dómine: et lux perpétua lúceat eis.",
              "* Cum Sanctis tuis in ætérnum: quia pius es.",
              "",
            ],
            vernacular: [
              "4 Ezdr 2:35; 2:34",
              "Que a luz eterna lhes resplandeça: Com os vossos Santos em todos os séculos, ó Senhor, pois sois bom.",
              "℣. Dai-lhes, Senhor, o eterno repouso, e que a luz perpétua lhes resplandeça: Com os vossos santos em todos os séculos, ó Senhor, pois sois misericordioso.",
              "",
              "",
              "",
            ],
          },
          id: "Communio",
        },
        {
          body: {
            latin: [
              "Præsta, quǽsumus, omnípotens et miséricors Deus: ut ánimæ fratrum, propinquórum et benefactórum nostrórum, pro quibus hoc sacrifícium laudis tuæ obtúlimus majestáti; per hujus virtútem sacraménti a peccátis ómnibus expiátæ, lucis perpétuæ, te miseránte, recípiant beatitúdinem.",
              "Per Dominum…",
              "",
            ],
            vernacular: [
              "Ó Deus omnipotente e misericordioso, Vos pedimos, concedei às almas dos nossos irmãos, parentes e benfeitores, pelos quais oferecemos à vossa majestade este sacrifício de louvor, a graça de alcançarem da vossa misericórdia, pela virtude deste sacramento, a expiação dos pecados e a felicidade da luz eterna.",
              "Por nosso Senhor...",
              "",
            ],
          },
          id: "Postcommunio",
        },
      ],
    },
  ]);
});
