import type { MassMap } from "../../domain";

/** Temporas do Advento e da oitava do Natal. */
export const TEMPORA_ADVENTO: MassMap = {
  TEMPORA_ADV1_0: {
    flexibility: "tempora",
    id: "TEMPORA_ADV1_0",
    name: "1ª Domingo do Advento",
    rank: 1,
    color: "v",
    link: "missal/advento/adv1-0",
    // Privileged semiduplex Sunday (DA); every Sunday is II class under
    // Rubrics 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex privilegiatum", precedence: 6.9 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "advent",
    category: "advento",
    weekday: 0,
    week: 1,
  },
  TEMPORA_ADV1_1: {
    flexibility: "tempora",
    id: "TEMPORA_ADV1_1",
    name: "Segunda-feira da 1ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv1-0",
    type: "advent",
    category: "advento",
    weekday: 1,
    week: 1,
  },
  TEMPORA_ADV1_2: {
    flexibility: "tempora",
    id: "TEMPORA_ADV1_2",
    name: "Terça-feira da 1ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv1-0",
    type: "advent",
    category: "advento",
    weekday: 2,
    week: 1,
  },
  TEMPORA_ADV1_3: {
    flexibility: "tempora",
    id: "TEMPORA_ADV1_3",
    name: "Quarta-feira da 1ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv1-0",
    type: "advent",
    category: "advento",
    weekday: 3,
    week: 1,
  },
  TEMPORA_ADV1_4: {
    flexibility: "tempora",
    id: "TEMPORA_ADV1_4",
    name: "Quinta-feira da 1ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv1-0",
    type: "advent",
    category: "advento",
    weekday: 4,
    week: 1,
  },
  TEMPORA_ADV1_5: {
    flexibility: "tempora",
    id: "TEMPORA_ADV1_5",
    name: "Sexta-feira da 1ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv1-0",
    type: "advent",
    category: "advento",
    weekday: 5,
    week: 1,
  },
  TEMPORA_ADV1_6: {
    flexibility: "tempora",
    id: "TEMPORA_ADV1_6",
    name: "Sábado da 1ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv1-0",
    type: "advent",
    category: "advento",
    weekday: 6,
    week: 1,
  },
  TEMPORA_ADV2_0: {
    flexibility: "tempora",
    id: "TEMPORA_ADV2_0",
    name: "2º Domingo do Advento",
    rank: 1,
    color: "v",
    link: "missal/advento/adv2-0",
    // Privileged semiduplex Sunday (DA); every Sunday is II class under
    // Rubrics 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex privilegiatum", precedence: 6.9 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "advent",
    category: "advento",
    weekday: 0,
    week: 2,
  },
  TEMPORA_ADV2_1: {
    flexibility: "tempora",
    id: "TEMPORA_ADV2_1",
    name: "Segunda-feira da 2ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv2-0",
    type: "advent",
    category: "advento",
    weekday: 1,
    week: 2,
  },
  TEMPORA_ADV2_2: {
    flexibility: "tempora",
    id: "TEMPORA_ADV2_2",
    name: "Terça-feira da 2ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv2-0",
    type: "advent",
    category: "advento",
    weekday: 2,
    week: 2,
  },
  TEMPORA_ADV2_3: {
    flexibility: "tempora",
    id: "TEMPORA_ADV2_3",
    name: "Quarta-feira da 2ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv2-0",
    type: "advent",
    category: "advento",
    weekday: 3,
    week: 2,
  },
  TEMPORA_ADV2_4: {
    flexibility: "tempora",
    id: "TEMPORA_ADV2_4",
    name: "Quinta-feira da 2ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv2-0",
    type: "advent",
    category: "advento",
    weekday: 4,
    week: 2,
  },
  TEMPORA_ADV2_5: {
    flexibility: "tempora",
    id: "TEMPORA_ADV2_5",
    name: "Sexta-feira da 2ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv2-0",
    type: "advent",
    category: "advento",
    weekday: 5,
    week: 2,
  },
  TEMPORA_ADV2_6: {
    flexibility: "tempora",
    id: "TEMPORA_ADV2_6",
    name: "Sábado da 2ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv2-0",
    type: "advent",
    category: "advento",
    weekday: 6,
    week: 2,
  },
  TEMPORA_ADV3_0: {
    flexibility: "tempora",
    id: "TEMPORA_ADV3_0",
    name: "3º Domingo do Advento",
    rank: 1,
    color: "v",
    link: "missal/advento/adv3-0",
    // Privileged semiduplex Sunday (DA); every Sunday is II class under
    // Rubrics 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex privilegiatum", precedence: 6.9 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "advent",
    category: "advento",
    weekday: 0,
    week: 3,
  },
  TEMPORA_ADV3_1: {
    flexibility: "tempora",
    id: "TEMPORA_ADV3_1",
    name: "Segunda-feira da 3ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv3-0",
    type: "advent",
    category: "advento",
    weekday: 1,
    week: 3,
  },
  TEMPORA_ADV3_2: {
    flexibility: "tempora",
    id: "TEMPORA_ADV3_2",
    name: "Terça-feira da 3ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv3-0",
    type: "advent",
    category: "advento",
    weekday: 2,
    week: 3,
  },
  TEMPORA_ADV3_3: {
    flexibility: "tempora",
    id: "TEMPORA_ADV3_3",
    name: "Quarta-feira das Têmporas de Inverno",
    rank: 2,
    color: "v",
    link: "missal/advento/adv3-3",
    type: "advent",
    category: "advento",
    weekday: 3,
    week: 3,
  },
  TEMPORA_ADV3_4: {
    flexibility: "tempora",
    id: "TEMPORA_ADV3_4",
    name: "Quinta-feira da 3ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv3-0",
    type: "advent",
    category: "advento",
    weekday: 4,
    week: 3,
  },
  TEMPORA_ADV3_5: {
    flexibility: "tempora",
    id: "TEMPORA_ADV3_5",
    name: "Sexta-feira das Têmporas de Inverno",
    rank: 2,
    color: "v",
    link: "missal/advento/adv3-5",
    type: "advent",
    category: "advento",
    weekday: 5,
    week: 3,
  },
  TEMPORA_ADV3_6: {
    flexibility: "tempora",
    id: "TEMPORA_ADV3_6",
    name: "Sábado das Têmporas de Inverno",
    rank: 2,
    color: "v",
    link: "missal/advento/adv3-6",
    type: "advent",
    category: "advento",
    weekday: 6,
    week: 3,
  },
  TEMPORA_ADV4_0: {
    flexibility: "tempora",
    id: "TEMPORA_ADV4_0",
    name: "4º Domingo do Advento",
    rank: 1,
    color: "v",
    link: "missal/advento/adv4-0",
    // Privileged semiduplex Sunday (DA); every Sunday is II class under
    // Rubrics 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex privilegiatum", precedence: 6.9 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "advent",
    category: "advento",
    weekday: 0,
    week: 4,
  },
  TEMPORA_ADV4_1: {
    flexibility: "tempora",
    id: "TEMPORA_ADV4_1",
    name: "Segunda-feira da 4ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv4-0",
    type: "advent",
    category: "advento",
    weekday: 1,
    week: 4,
  },
  TEMPORA_ADV4_2: {
    flexibility: "tempora",
    id: "TEMPORA_ADV4_2",
    name: "Terça-feira da 4ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv4-0",
    type: "advent",
    category: "advento",
    weekday: 2,
    week: 4,
  },
  TEMPORA_ADV4_3: {
    flexibility: "tempora",
    id: "TEMPORA_ADV4_3",
    name: "Quarta-feira da 4ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv4-0",
    type: "advent",
    category: "advento",
    weekday: 3,
    week: 4,
  },
  TEMPORA_ADV4_4: {
    flexibility: "tempora",
    id: "TEMPORA_ADV4_4",
    name: "Quinta-feira da 4ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv4-0",
    type: "advent",
    category: "advento",
    weekday: 4,
    week: 4,
  },
  TEMPORA_ADV4_5: {
    flexibility: "tempora",
    id: "TEMPORA_ADV4_5",
    name: "Sexta-feira da 4ª semana do Advento",
    rank: 3,
    color: "v",
    link: "missal/advento/adv4-0",
    type: "advent",
    category: "advento",
    weekday: 5,
    week: 4,
  },
  TEMPORA_NAT1_0: {
    flexibility: "tempora",
    id: "TEMPORA_NAT1_0",
    name: "Domingo dentro do Oitavário do Natal",
    rank: 2,
    color: "w",
    link: "missal/natal/nat1-0",
    type: "feria",
    category: "natal",
    weekday: 0,
    week: 1,
  },
  TEMPORA_NAT2_0: {
    flexibility: "tempora",
    id: "TEMPORA_NAT2_0",
    name: "Santíssimo Nome de Jesus",
    rank: 2,
    color: "w",
    link: "missal/natal/nat2-0",
    type: "feria",
    category: "natal",
    weekday: 0,
    week: 2,
    novena: true,
  },
};
