import type { MassMap } from "../../domain";

/** Temporas do tempo do Natal após a Epifania. */
export const TEMPORA_EPIFANIA: MassMap = {
  TEMPORA_EPI1_0A: {
    flexibility: "tempora",
    id: "TEMPORA_EPI1_0A",
    name: "Sagrada Família",
    rank: 2,
    color: "w",
    link: "missal/epifania/epi1-0a",
    type: "post-epiphany",
    category: "epifania",
    weekday: 0,
    week: 1,
    rankVariants: [
      { rubrics: "*", name: "Duplex majus", precedence: 5.61 },
    ],
  },
  TEMPORA_EPI1_1: {
    flexibility: "tempora",
    id: "TEMPORA_EPI1_1",
    name: "Segunda-feira da semana após a Epifania",
    rank: 4,
    color: "w",
    link: "missal/epifania/epi1-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 1,
    week: 1,
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5.6 },
      { rubrics: "Rubrics 1960 - 1960", name: "Feria", precedence: 1.2 },
    ],
  },
  TEMPORA_EPI1_2: {
    flexibility: "tempora",
    id: "TEMPORA_EPI1_2",
    name: "Terça-feira da semana após a Epifania",
    rank: 4,
    color: "w",
    link: "missal/epifania/epi1-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 2,
    week: 1,
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5.6 },
      { rubrics: "Rubrics 1960 - 1960", name: "Feria", precedence: 1.2 },
    ],
  },
  TEMPORA_EPI1_3: {
    flexibility: "tempora",
    id: "TEMPORA_EPI1_3",
    name: "Quarta-feira da semana após a Epifania",
    rank: 4,
    color: "w",
    link: "missal/epifania/epi1-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 3,
    week: 1,
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5.6 },
      { rubrics: "Rubrics 1960 - 1960", name: "Feria", precedence: 1.2 },
    ],
  },
  TEMPORA_EPI1_4: {
    flexibility: "tempora",
    id: "TEMPORA_EPI1_4",
    name: "Quinta-feira da semana após a Epifania",
    rank: 4,
    color: "w",
    link: "missal/epifania/epi1-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 4,
    week: 1,
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5.6 },
      { rubrics: "Rubrics 1960 - 1960", name: "Feria", precedence: 1.2 },
    ],
  },
  TEMPORA_EPI1_5: {
    flexibility: "tempora",
    id: "TEMPORA_EPI1_5",
    name: "Sexta-feira da semana após a Epifania",
    rank: 4,
    color: "w",
    link: "missal/epifania/epi1-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 5,
    week: 1,
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5.6 },
      { rubrics: "Rubrics 1960 - 1960", name: "Feria", precedence: 1.2 },
    ],
  },
  TEMPORA_EPI1_6: {
    flexibility: "tempora",
    id: "TEMPORA_EPI1_6",
    name: "Sábado da semana após a Epifania",
    rank: 4,
    color: "w",
    link: "missal/epifania/epi1-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 6,
    week: 1,
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5.6 },
      { rubrics: "Rubrics 1960 - 1960", name: "Feria", precedence: 1.2 },
    ],
  },
  TEMPORA_EPI2_0: {
    flexibility: "tempora",
    id: "TEMPORA_EPI2_0",
    name: "2º Domingo após a Epifania",
    rank: 2,
    color: "g",
    link: "missal/epifania/epi2-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "post-epiphany",
    category: "epifania",
    weekday: 0,
    week: 2,
  },
  TEMPORA_EPI2_1: {
    flexibility: "tempora",
    id: "TEMPORA_EPI2_1",
    name: "Segunda-feira da 2ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi2-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 1,
    week: 2,
  },
  TEMPORA_EPI2_2: {
    flexibility: "tempora",
    id: "TEMPORA_EPI2_2",
    name: "Terça-feira da 2ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi2-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 2,
    week: 2,
  },
  TEMPORA_EPI2_3: {
    flexibility: "tempora",
    id: "TEMPORA_EPI2_3",
    name: "Quarta-feira da 2ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi2-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 3,
    week: 2,
  },
  TEMPORA_EPI2_4: {
    flexibility: "tempora",
    id: "TEMPORA_EPI2_4",
    name: "Quinta-feira da 2ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi2-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 4,
    week: 2,
  },
  TEMPORA_EPI2_5: {
    flexibility: "tempora",
    id: "TEMPORA_EPI2_5",
    name: "Sexta-feira da 2ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi2-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 5,
    week: 2,
  },
  TEMPORA_EPI2_6: {
    flexibility: "tempora",
    id: "TEMPORA_EPI2_6",
    name: "Sábado da 2ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi2-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 6,
    week: 2,
  },
  TEMPORA_EPI3_0: {
    flexibility: "tempora",
    id: "TEMPORA_EPI3_0",
    name: "3º Domingo após a Epifania",
    rank: 2,
    color: "g",
    link: "missal/epifania/epi3-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "post-epiphany",
    category: "epifania",
    weekday: 0,
    week: 3,
  },
  TEMPORA_EPI3_1: {
    flexibility: "tempora",
    id: "TEMPORA_EPI3_1",
    name: "Segunda-feira da 3ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi3-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 1,
    week: 3,
  },
  TEMPORA_EPI3_2: {
    flexibility: "tempora",
    id: "TEMPORA_EPI3_2",
    name: "Terça-feira da 3ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi3-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 2,
    week: 3,
  },
  TEMPORA_EPI3_3: {
    flexibility: "tempora",
    id: "TEMPORA_EPI3_3",
    name: "Quarta-feira da 3ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi3-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 3,
    week: 3,
  },
  TEMPORA_EPI3_4: {
    flexibility: "tempora",
    id: "TEMPORA_EPI3_4",
    name: "Quinta-feira da 3ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi3-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 4,
    week: 3,
  },
  TEMPORA_EPI3_5: {
    flexibility: "tempora",
    id: "TEMPORA_EPI3_5",
    name: "Sexta-feira da 3ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi3-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 5,
    week: 3,
  },
  TEMPORA_EPI3_6: {
    flexibility: "tempora",
    id: "TEMPORA_EPI3_6",
    name: "Sábado da 3ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi3-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 6,
    week: 3,
  },
  TEMPORA_EPI4_0: {
    flexibility: "tempora",
    id: "TEMPORA_EPI4_0",
    name: "4º Domingo após a Epifania",
    rank: 2,
    color: "g",
    link: "missal/epifania/epi4-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "post-epiphany",
    category: "epifania",
    weekday: 0,
    week: 4,
  },
  TEMPORA_EPI4_1: {
    flexibility: "tempora",
    id: "TEMPORA_EPI4_1",
    name: "Segunda-feira da 4ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi4-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 1,
    week: 4,
  },
  TEMPORA_EPI4_2: {
    flexibility: "tempora",
    id: "TEMPORA_EPI4_2",
    name: "Terça-feira da 4ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi4-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 2,
    week: 4,
  },
  TEMPORA_EPI4_3: {
    flexibility: "tempora",
    id: "TEMPORA_EPI4_3",
    name: "Quarta-feira da 4ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi4-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 3,
    week: 4,
  },
  TEMPORA_EPI4_4: {
    flexibility: "tempora",
    id: "TEMPORA_EPI4_4",
    name: "Quinta-feira da 4ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi4-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 4,
    week: 4,
  },
  TEMPORA_EPI4_5: {
    flexibility: "tempora",
    id: "TEMPORA_EPI4_5",
    name: "Sexta-feira da 4ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi4-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 5,
    week: 4,
  },
  TEMPORA_EPI4_6: {
    flexibility: "tempora",
    id: "TEMPORA_EPI4_6",
    name: "Sábado da 4ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi4-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 6,
    week: 4,
  },
  TEMPORA_EPI5_0: {
    flexibility: "tempora",
    id: "TEMPORA_EPI5_0",
    name: "5º Domingo após a Epifania",
    rank: 2,
    color: "g",
    link: "missal/epifania/epi5-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "post-epiphany",
    category: "epifania",
    weekday: 0,
    week: 5,
  },
  TEMPORA_EPI5_1: {
    flexibility: "tempora",
    id: "TEMPORA_EPI5_1",
    name: "Segunda-feira da 5ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi5-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 1,
    week: 5,
  },
  TEMPORA_EPI5_2: {
    flexibility: "tempora",
    id: "TEMPORA_EPI5_2",
    name: "Terça-feira da 5ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi5-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 2,
    week: 5,
  },
  TEMPORA_EPI5_3: {
    flexibility: "tempora",
    id: "TEMPORA_EPI5_3",
    name: "Quarta-feira da 5ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi5-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 3,
    week: 5,
  },
  TEMPORA_EPI5_4: {
    flexibility: "tempora",
    id: "TEMPORA_EPI5_4",
    name: "Quinta-feira da 5ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi5-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 4,
    week: 5,
  },
  TEMPORA_EPI5_5: {
    flexibility: "tempora",
    id: "TEMPORA_EPI5_5",
    name: "Sexta-feira da 5ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi5-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 5,
    week: 5,
  },
  TEMPORA_EPI5_6: {
    flexibility: "tempora",
    id: "TEMPORA_EPI5_6",
    name: "Sábado da 5ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi5-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 6,
    week: 5,
  },
  TEMPORA_EPI6_0: {
    flexibility: "tempora",
    id: "TEMPORA_EPI6_0",
    name: "6º Domingo após a Epifania",
    rank: 2,
    color: "g",
    link: "missal/epifania/epi6-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "post-epiphany",
    category: "epifania",
    weekday: 0,
    week: 6,
  },
  TEMPORA_EPI6_1: {
    flexibility: "tempora",
    id: "TEMPORA_EPI6_1",
    name: "Segunda-feira da 6ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi6-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 1,
    week: 6,
  },
  TEMPORA_EPI6_2: {
    flexibility: "tempora",
    id: "TEMPORA_EPI6_2",
    name: "Terça-feira da 6ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi6-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 2,
    week: 6,
  },
  TEMPORA_EPI6_3: {
    flexibility: "tempora",
    id: "TEMPORA_EPI6_3",
    name: "Quarta-feira da 6ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi6-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 3,
    week: 6,
  },
  TEMPORA_EPI6_4: {
    flexibility: "tempora",
    id: "TEMPORA_EPI6_4",
    name: "Quinta-feira da 6ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi6-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 4,
    week: 6,
  },
  TEMPORA_EPI6_5: {
    flexibility: "tempora",
    id: "TEMPORA_EPI6_5",
    name: "Sexta-feira da 6ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi6-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 5,
    week: 6,
  },
  TEMPORA_EPI6_6: {
    flexibility: "tempora",
    id: "TEMPORA_EPI6_6",
    name: "Sábado da 6ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/epifania/epi6-0",
    type: "post-epiphany",
    category: "epifania",
    weekday: 6,
    week: 6,
  },
};
