import type { MassMap } from "../../domain";

/** Temporas do Tempo Pascal. */
export const TEMPORA_PASCOA: MassMap = {
  TEMPORA_PASC0_0: {
    flexibility: "tempora",
    id: "TEMPORA_PASC0_0",
    name: "Domingo da Ressurreição",
    rank: 1,
    color: "w",
    link: "missal/pascoa/pasc0-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 0,
    week: 0,
  },
  TEMPORA_PASC0_1: {
    flexibility: "tempora",
    id: "TEMPORA_PASC0_1",
    name: "Segunda-feira Pascal",
    rank: 1,
    color: "w",
    link: "missal/pascoa/pasc0-1",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 1,
    week: 0,
  },
  TEMPORA_PASC0_2: {
    flexibility: "tempora",
    id: "TEMPORA_PASC0_2",
    name: "Terça-feira Pascal",
    rank: 1,
    color: "w",
    link: "missal/pascoa/pasc0-2",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 2,
    week: 0,
  },
  TEMPORA_PASC0_3: {
    flexibility: "tempora",
    id: "TEMPORA_PASC0_3",
    name: "Quarta-feira Pascal",
    rank: 1,
    color: "w",
    link: "missal/pascoa/pasc0-3",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 3,
    week: 0,
  },
  TEMPORA_PASC0_4: {
    flexibility: "tempora",
    id: "TEMPORA_PASC0_4",
    name: "Quinta-feira Pascal",
    rank: 1,
    color: "w",
    link: "missal/pascoa/pasc0-4",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 4,
    week: 0,
  },
  TEMPORA_PASC0_5: {
    flexibility: "tempora",
    id: "TEMPORA_PASC0_5",
    name: "Sexta-feira Pascal",
    rank: 1,
    color: "w",
    link: "missal/pascoa/pasc0-5",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 5,
    week: 0,
  },
  TEMPORA_PASC0_6: {
    flexibility: "tempora",
    id: "TEMPORA_PASC0_6",
    name: "Sábado Pascal",
    rank: 1,
    color: "w",
    link: "missal/pascoa/pasc0-6",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 6,
    week: 0,
  },
  TEMPORA_PASC1_0: {
    flexibility: "tempora",
    id: "TEMPORA_PASC1_0",
    name: "Domingo in Albis",
    rank: 1,
    color: "w",
    link: "missal/pascoa/pasc1-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 0,
    week: 1,
  },
  TEMPORA_PASC1_1: {
    flexibility: "tempora",
    id: "TEMPORA_PASC1_1",
    name: "Segunda-feira da 1º semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc1-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 1,
    week: 1,
  },
  TEMPORA_PASC1_2: {
    flexibility: "tempora",
    id: "TEMPORA_PASC1_2",
    name: "Terça-feira da 1ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc1-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 2,
    week: 1,
  },
  TEMPORA_PASC1_3: {
    flexibility: "tempora",
    id: "TEMPORA_PASC1_3",
    name: "Quarta-feira da 1ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc1-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 3,
    week: 1,
  },
  TEMPORA_PASC1_4: {
    flexibility: "tempora",
    id: "TEMPORA_PASC1_4",
    name: "Quinta-feira da 1ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc1-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 4,
    week: 1,
  },
  TEMPORA_PASC1_5: {
    flexibility: "tempora",
    id: "TEMPORA_PASC1_5",
    name: "Sexta-feira da 1ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc1-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 5,
    week: 1,
  },
  TEMPORA_PASC1_6: {
    flexibility: "tempora",
    id: "TEMPORA_PASC1_6",
    name: "Sábado da 1ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc1-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 6,
    week: 1,
  },
  TEMPORA_PASC2_0: {
    flexibility: "tempora",
    id: "TEMPORA_PASC2_0",
    name: "2º Domingo depois da Páscoa",
    rank: 2,
    color: "w",
    link: "missal/pascoa/pasc2-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 0,
    week: 2,
  },
  TEMPORA_PASC2_1: {
    flexibility: "tempora",
    id: "TEMPORA_PASC2_1",
    name: "Segunda-feira da 2ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc2-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 1,
    week: 2,
  },
  TEMPORA_PASC2_2: {
    flexibility: "tempora",
    id: "TEMPORA_PASC2_2",
    name: "Terça-feira da 2ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc2-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 2,
    week: 2,
  },
  TEMPORA_PASC2_3: {
    flexibility: "tempora",
    id: "TEMPORA_PASC2_3",
    name: "S. José, Padroeiro da Santa Igreja e dos Moribundos",
    rank: 2,
    color: "w",
    link: "missal/pascoa/pasc2-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 3,
    week: 2,
  },
  TEMPORA_PASC2_4: {
    flexibility: "tempora",
    id: "TEMPORA_PASC2_4",
    name: "Quinta-feira da 2ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc2-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 4,
    week: 2,
  },
  TEMPORA_PASC2_5: {
    flexibility: "tempora",
    id: "TEMPORA_PASC2_5",
    name: "Sexta-feira da 2ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc2-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 5,
    week: 2,
  },
  TEMPORA_PASC2_6: {
    flexibility: "tempora",
    id: "TEMPORA_PASC2_6",
    name: "Sábado da 2ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc2-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 6,
    week: 2,
  },
  TEMPORA_PASC3_0: {
    flexibility: "tempora",
    id: "TEMPORA_PASC3_0",
    name: "3º Domingo depois da Páscoa",
    rank: 2,
    color: "w",
    link: "missal/pascoa/pasc3-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 0,
    week: 3,
  },
  TEMPORA_PASC3_1: {
    flexibility: "tempora",
    id: "TEMPORA_PASC3_1",
    name: "Segunda-feira da 3ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc3-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 1,
    week: 3,
  },
  TEMPORA_PASC3_2: {
    flexibility: "tempora",
    id: "TEMPORA_PASC3_2",
    name: "Terça-feira da 3ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc3-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 2,
    week: 3,
  },
  TEMPORA_PASC3_3: {
    flexibility: "tempora",
    id: "TEMPORA_PASC3_3",
    name: "Quarta-feira da 3ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc3-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 3,
    week: 3,
  },
  TEMPORA_PASC3_4: {
    flexibility: "tempora",
    id: "TEMPORA_PASC3_4",
    name: "Quinta-feira da 3ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc3-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 4,
    week: 3,
  },
  TEMPORA_PASC3_5: {
    flexibility: "tempora",
    id: "TEMPORA_PASC3_5",
    name: "Sexta-feira da 3ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc3-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 5,
    week: 3,
  },
  TEMPORA_PASC3_6: {
    flexibility: "tempora",
    id: "TEMPORA_PASC3_6",
    name: "Sábado da 3ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc3-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 6,
    week: 3,
  },
  TEMPORA_PASC4_0: {
    flexibility: "tempora",
    id: "TEMPORA_PASC4_0",
    name: "4º Domingo depois da Páscoa",
    rank: 2,
    color: "w",
    link: "missal/pascoa/pasc4-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 0,
    week: 4,
  },
  TEMPORA_PASC4_1: {
    flexibility: "tempora",
    id: "TEMPORA_PASC4_1",
    name: "Segunda-feira da 4ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc4-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 1,
    week: 4,
  },
  TEMPORA_PASC4_2: {
    flexibility: "tempora",
    id: "TEMPORA_PASC4_2",
    name: "Terça-feira da 4ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc4-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 2,
    week: 4,
  },
  TEMPORA_PASC4_3: {
    flexibility: "tempora",
    id: "TEMPORA_PASC4_3",
    name: "Quarta-feira da 4ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc4-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 3,
    week: 4,
  },
  TEMPORA_PASC4_4: {
    flexibility: "tempora",
    id: "TEMPORA_PASC4_4",
    name: "Quinta-feira da 4ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc4-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 4,
    week: 4,
  },
  TEMPORA_PASC4_5: {
    flexibility: "tempora",
    id: "TEMPORA_PASC4_5",
    name: "Sexta-feira da 4ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc4-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 5,
    week: 4,
  },
  TEMPORA_PASC4_6: {
    flexibility: "tempora",
    id: "TEMPORA_PASC4_6",
    name: "Sábado da 4ª semana depois da Páscoa",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc4-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 6,
    week: 4,
  },
  TEMPORA_PASC5_0: {
    flexibility: "tempora",
    id: "TEMPORA_PASC5_0",
    name: "5º Domingo depois da Páscoa",
    rank: 2,
    color: "w",
    link: "missal/pascoa/pasc5-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 0,
    week: 5,
  },
  TEMPORA_PASC5_1: {
    flexibility: "tempora",
    id: "TEMPORA_PASC5_1",
    name: "Segunda-feira das Rogações",
    rank: 4,
    color: "v",
    link: "missal/pascoa/pasc5-1",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 1,
    week: 5,
  },
  TEMPORA_PASC5_2: {
    flexibility: "tempora",
    id: "TEMPORA_PASC5_2",
    name: "Terça-feira das Rogações",
    rank: 4,
    color: "w",
    link: "missal/pascoa/pasc5-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 2,
    week: 5,
  },
  TEMPORA_PASC5_3: {
    flexibility: "tempora",
    id: "TEMPORA_PASC5_3",
    name: "Vigília da Ascensão",
    rank: 2,
    color: "w",
    link: "missal/pascoa/pasc5-3",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 3,
    week: 5,
  },
  TEMPORA_PASC5_4: {
    flexibility: "tempora",
    id: "TEMPORA_PASC5_4",
    name: "Ascensão",
    rank: 1,
    color: "w",
    link: "missal/pascoa/pasc5-4",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 4,
    week: 5,
  },
  TEMPORA_PASC5_5: {
    flexibility: "tempora",
    id: "TEMPORA_PASC5_5",
    name: "Sexta-feira depois da Ascensão",
    rank: 3,
    color: "w",
    link: "missal/pascoa/pasc5-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 5,
    week: 5,
  },
  TEMPORA_PASC5_6: {
    flexibility: "tempora",
    id: "TEMPORA_PASC5_6",
    name: "Sábado depois da Ascensão",
    rank: 3,
    color: "w",
    link: "missal/pascoa/pasc5-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 6,
    week: 5,
  },
  TEMPORA_PASC6_0: {
    flexibility: "tempora",
    id: "TEMPORA_PASC6_0",
    name: "Domingo depois da Ascensão",
    rank: 2,
    color: "w",
    link: "missal/pascoa/pasc6-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 0,
    week: 6,
  },
  TEMPORA_PASC6_1: {
    flexibility: "tempora",
    id: "TEMPORA_PASC6_1",
    name: "Segunda-feira da semana depois da Ascensão",
    rank: 3,
    color: "w",
    link: "missal/pascoa/pasc6-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 1,
    week: 6,
  },
  TEMPORA_PASC6_2: {
    flexibility: "tempora",
    id: "TEMPORA_PASC6_2",
    name: "Terça-feira da semana depois da Ascensão",
    rank: 3,
    color: "w",
    link: "missal/pascoa/pasc6-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 2,
    week: 6,
  },
  TEMPORA_PASC6_3: {
    flexibility: "tempora",
    id: "TEMPORA_PASC6_3",
    name: "Quarta-feira da semana depois da Ascensão",
    rank: 3,
    color: "w",
    link: "missal/pascoa/pasc6-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 3,
    week: 6,
  },
  TEMPORA_PASC6_4: {
    flexibility: "tempora",
    id: "TEMPORA_PASC6_4",
    name: "Quinta-feira da semana depois da Ascensão",
    rank: 3,
    color: "w",
    link: "missal/pascoa/pasc6-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 4,
    week: 6,
  },
  TEMPORA_PASC6_5: {
    flexibility: "tempora",
    id: "TEMPORA_PASC6_5",
    name: "Sexta-feira da semana depois da Ascensão",
    rank: 3,
    color: "w",
    link: "missal/pascoa/pasc6-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 5,
    week: 6,
  },
  TEMPORA_PASC6_6: {
    flexibility: "tempora",
    id: "TEMPORA_PASC6_6",
    name: "Vigília de Pentecostes",
    rank: 1,
    color: "r",
    link: "missal/pascoa/pasc6-6",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 6,
    week: 6,
  },
  TEMPORA_PASC7_0: {
    flexibility: "tempora",
    id: "TEMPORA_PASC7_0",
    name: "Domingo de Pentecostes",
    rank: 1,
    color: "r",
    link: "missal/pascoa/pasc7-0",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 0,
    week: 7,
    novena: true,
  },
  TEMPORA_PASC7_1: {
    flexibility: "tempora",
    id: "TEMPORA_PASC7_1",
    name: "Segunda-feira na semana da oitava de Pentecostes",
    rank: 1,
    color: "r",
    link: "missal/pascoa/pasc7-1",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 1,
    week: 7,
  },
  TEMPORA_PASC7_2: {
    flexibility: "tempora",
    id: "TEMPORA_PASC7_2",
    name: "Terça-feira na semana da oitava de Pentecostes",
    rank: 1,
    color: "r",
    link: "missal/pascoa/pasc7-2",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 2,
    week: 7,
  },
  TEMPORA_PASC7_3: {
    flexibility: "tempora",
    id: "TEMPORA_PASC7_3",
    name: "Quarta-feira das Têmporas de Pentecostes",
    rank: 1,
    color: "r",
    link: "missal/pascoa/pasc7-3",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 3,
    week: 7,
  },
  TEMPORA_PASC7_4: {
    flexibility: "tempora",
    id: "TEMPORA_PASC7_4",
    name: "Quinta-feira na semana da oitava de Pentecostes",
    rank: 1,
    color: "r",
    link: "missal/pascoa/pasc7-4",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 4,
    week: 7,
  },
  TEMPORA_PASC7_5: {
    flexibility: "tempora",
    id: "TEMPORA_PASC7_5",
    name: "Sexta-feira das Têmporas de Pentecostes",
    rank: 1,
    color: "r",
    link: "missal/pascoa/pasc7-5",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 5,
    week: 7,
  },
  TEMPORA_PASC7_6: {
    flexibility: "tempora",
    id: "TEMPORA_PASC7_6",
    name: "Sábado das Têmporas de Pentecostes",
    rank: 1,
    color: "r",
    link: "missal/pascoa/pasc7-6",
    type: "pre-lent-to-pentcost",
    category: "pascoa",
    weekday: 6,
    week: 7,
  },
};
