import type { MassMap } from "../../domain";

/** Temporas do tempo depois de Pentecostes. */
export const TEMPORA_PENTECOSTES: MassMap = {
  TEMPORA_PENT01_0A: {
    flexibility: "tempora",
    id: "TEMPORA_PENT01_0A",
    name: "1ª Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent1-0a",
    type: "feria",
    category: "pentecostes",
    weekday: 6,
    week: 1,
  },
  TEMPORA_PENT01_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT01_0",
    name: "Domingo da Santíssima Trindade",
    rank: 1,
    color: "w",
    link: "missal/pentecostes/pent1-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 1,
  },
  TEMPORA_PENT01_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT01_1",
    name: "Segunda-feira depois 1ª semana da oitava de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent1-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 1,
  },
  TEMPORA_PENT01_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT01_2",
    name: "Terça-feira depois 1ª semana da oitava de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent1-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 1,
  },
  TEMPORA_PENT01_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT01_3",
    name: "Quarta-feira depois 1ª semana da oitava de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent1-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 1,
  },
  TEMPORA_PENT01_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT01_4",
    name: "Santíssimo Corpo de Cristo",
    rank: 1,
    color: "w",
    link: "missal/pentecostes/pent1-4",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 1,
    novena: true,
  },
  TEMPORA_PENT01_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT01_5",
    name: "Sexta-feira depois 1ª semana da oitava de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent1-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 1,
  },
  TEMPORA_PENT01_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT01_6",
    name: "Sábado depois 1ª semana da oitava de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent1-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 1,
  },
  TEMPORA_PENT02_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT02_0",
    name: "2º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent2-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 2,
  },
  TEMPORA_PENT02_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT02_1",
    name: "Segunda-feira da 2ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent2-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 2,
  },
  TEMPORA_PENT02_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT02_2",
    name: "Terça-feira da 2ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent2-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 2,
  },
  TEMPORA_PENT02_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT02_3",
    name: "Quarta-feira da 2ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent2-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 2,
  },
  TEMPORA_PENT02_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT02_4",
    name: "Quinta-feira da 2ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent2-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 2,
  },
  TEMPORA_PENT02_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT02_5",
    name: "Santíssimo Coração de Jesus",
    rank: 1,
    color: "w",
    link: "missal/pentecostes/pent2-5",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 2,
    novena: true,
  },
  TEMPORA_PENT02_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT02_6",
    name: "Sábado da 2ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent2-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 2,
  },
  TEMPORA_PENT03_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT03_0",
    name: "3º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent3-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 3,
  },
  TEMPORA_PENT03_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT03_1",
    name: "Segunda-feira da 3ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent3-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 3,
  },
  TEMPORA_PENT03_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT03_2",
    name: "Terça-feira da 3ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent3-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 3,
  },
  TEMPORA_PENT03_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT03_3",
    name: "Quarta-feira da 3ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent3-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 3,
  },
  TEMPORA_PENT03_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT03_4",
    name: "Quinta-feira da 3ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent3-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 3,
  },
  TEMPORA_PENT03_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT03_5",
    name: "Sexta-feira da 3ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent3-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 3,
  },
  TEMPORA_PENT03_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT03_6",
    name: "Sábado da 3ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent3-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 3,
  },
  TEMPORA_PENT04_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT04_0",
    name: "4º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent4-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 4,
  },
  TEMPORA_PENT04_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT04_1",
    name: "Segunda-feira da 4ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent4-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 4,
  },
  TEMPORA_PENT04_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT04_2",
    name: "Terça-feira da 4ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent4-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 4,
  },
  TEMPORA_PENT04_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT04_3",
    name: "Quarta-feira da 4ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent4-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 4,
  },
  TEMPORA_PENT04_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT04_4",
    name: "Quinta-feira da 4ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent4-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 4,
  },
  TEMPORA_PENT04_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT04_5",
    name: "Sexta-feira da 4ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent4-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 4,
  },
  TEMPORA_PENT04_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT04_6",
    name: "Sábado da 4ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent4-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 4,
  },
  TEMPORA_PENT05_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT05_0",
    name: "5º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent5-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 5,
  },
  TEMPORA_PENT05_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT05_1",
    name: "Segunda-feira da 5ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent5-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 5,
  },
  TEMPORA_PENT05_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT05_2",
    name: "Terça-feira da 5ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent5-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 5,
  },
  TEMPORA_PENT05_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT05_3",
    name: "Quarta-feira da 5ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent5-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 5,
  },
  TEMPORA_PENT05_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT05_4",
    name: "Quinta-feira da 5ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent5-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 5,
  },
  TEMPORA_PENT05_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT05_5",
    name: "Sexta-feira da 5ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent5-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 5,
  },
  TEMPORA_PENT05_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT05_6",
    name: "Sábado da 5ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent5-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 5,
  },
  TEMPORA_PENT06_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT06_0",
    name: "6º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent6-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 6,
  },
  TEMPORA_PENT06_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT06_1",
    name: "Segunda-feira da 6ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent6-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 6,
  },
  TEMPORA_PENT06_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT06_2",
    name: "Terça-feira da 6ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent6-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 6,
  },
  TEMPORA_PENT06_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT06_3",
    name: "Quarta-feira da 6ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent6-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 6,
  },
  TEMPORA_PENT06_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT06_4",
    name: "Quinta-feira da 6ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent6-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 6,
  },
  TEMPORA_PENT06_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT06_5",
    name: "Sexta-feira da 6ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent6-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 6,
  },
  TEMPORA_PENT06_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT06_6",
    name: "Sábado da 6ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent6-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 6,
  },
  TEMPORA_PENT07_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT07_0",
    name: "7º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent7-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 7,
  },
  TEMPORA_PENT07_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT07_1",
    name: "Segunda-feira da 7ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent7-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 7,
  },
  TEMPORA_PENT07_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT07_2",
    name: "Terça-feira da 7ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent7-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 7,
  },
  TEMPORA_PENT07_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT07_3",
    name: "Quarta-feira da 7ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent7-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 7,
  },
  TEMPORA_PENT07_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT07_4",
    name: "Quinta-feira da 7ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent7-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 7,
  },
  TEMPORA_PENT07_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT07_5",
    name: "Sexta-feira da 7ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent7-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 7,
  },
  TEMPORA_PENT07_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT07_6",
    name: "Sábado da 7ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent7-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 7,
  },
  TEMPORA_PENT08_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT08_0",
    name: "8º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent8-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 8,
  },
  TEMPORA_PENT08_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT08_1",
    name: "Segunda-feira da 8ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent8-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 8,
  },
  TEMPORA_PENT08_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT08_2",
    name: "Terça-feira da 8ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent8-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 8,
  },
  TEMPORA_PENT08_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT08_3",
    name: "Quarta-feira da 8ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent8-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 8,
  },
  TEMPORA_PENT08_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT08_4",
    name: "Quinta-feira da 8ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent8-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 8,
  },
  TEMPORA_PENT08_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT08_5",
    name: "Sexta-feira da 8ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent8-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 8,
  },
  TEMPORA_PENT08_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT08_6",
    name: "Sábado da 8ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent8-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 8,
  },
  TEMPORA_PENT09_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT09_0",
    name: "9º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent9-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 9,
  },
  TEMPORA_PENT09_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT09_1",
    name: "Segunda-feira da 9ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent9-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 9,
  },
  TEMPORA_PENT09_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT09_2",
    name: "Terça-feira da 9ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent9-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 9,
  },
  TEMPORA_PENT09_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT09_3",
    name: "Quarta-feira da 9ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent9-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 9,
  },
  TEMPORA_PENT09_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT09_4",
    name: "Quinta-feira da 9ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent9-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 9,
  },
  TEMPORA_PENT09_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT09_5",
    name: "Sexta-feira da 9ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent9-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 9,
  },
  TEMPORA_PENT09_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT09_6",
    name: "Sábado da 9ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent9-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 9,
  },
  TEMPORA_PENT10_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT10_0",
    name: "10º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent10-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 10,
  },
  TEMPORA_PENT10_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT10_1",
    name: "Segunda-feira da 10ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent10-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 10,
  },
  TEMPORA_PENT10_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT10_2",
    name: "Terça-feira da 10ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent10-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 10,
  },
  TEMPORA_PENT10_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT10_3",
    name: "Quarta-feira da 10ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent10-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 10,
  },
  TEMPORA_PENT10_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT10_4",
    name: "Quinta-feira da 10ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent10-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 10,
  },
  TEMPORA_PENT10_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT10_5",
    name: "Sexta-feira da 10ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent10-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 10,
  },
  TEMPORA_PENT10_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT10_6",
    name: "Sábado da 10ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent10-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 10,
  },
  TEMPORA_PENT11_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT11_0",
    name: "11º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent11-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 11,
  },
  TEMPORA_PENT11_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT11_1",
    name: "Segunda-feira da 11ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent11-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 11,
  },
  TEMPORA_PENT11_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT11_2",
    name: "Terça-feira da 11ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent11-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 11,
  },
  TEMPORA_PENT11_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT11_3",
    name: "Quarta-feira da 11ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent11-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 11,
  },
  TEMPORA_PENT11_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT11_4",
    name: "Quinta-feira da 11ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent11-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 11,
  },
  TEMPORA_PENT11_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT11_5",
    name: "Sexta-feira da 11ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent11-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 11,
  },
  TEMPORA_PENT11_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT11_6",
    name: "Sábado da 11ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent11-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 11,
  },
  TEMPORA_PENT12_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT12_0",
    name: "12º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent12-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 12,
  },
  TEMPORA_PENT12_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT12_1",
    name: "Segunda-feira da 12ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent12-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 12,
  },
  TEMPORA_PENT12_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT12_2",
    name: "Terça-feira da 12ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent12-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 12,
  },
  TEMPORA_PENT12_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT12_3",
    name: "Quarta-feira da 12ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent12-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 12,
  },
  TEMPORA_PENT12_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT12_4",
    name: "Quinta-feira da 12ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent12-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 12,
  },
  TEMPORA_PENT12_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT12_5",
    name: "Sexta-feira da 12ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent12-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 12,
  },
  TEMPORA_PENT12_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT12_6",
    name: "Sábado da 12ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent12-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 12,
  },
  TEMPORA_PENT13_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT13_0",
    name: "13º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent13-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 13,
  },
  TEMPORA_PENT13_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT13_1",
    name: "Segunda-feira da 13ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent13-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 13,
  },
  TEMPORA_PENT13_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT13_2",
    name: "Terça-feira da 13ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent13-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 13,
  },
  TEMPORA_PENT13_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT13_3",
    name: "Quarta-feira da 13ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent13-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 13,
  },
  TEMPORA_PENT13_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT13_4",
    name: "Quinta-feira da 13ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent13-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 13,
  },
  TEMPORA_PENT13_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT13_5",
    name: "Sexta-feira da 13ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent13-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 13,
  },
  TEMPORA_PENT13_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT13_6",
    name: "Sábado da 13ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent13-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 13,
  },
  TEMPORA_PENT14_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT14_0",
    name: "14º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent14-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 14,
  },
  TEMPORA_PENT14_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT14_1",
    name: "Segunda-feira da 14ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent14-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 14,
  },
  TEMPORA_PENT14_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT14_2",
    name: "Terça-feira da 14ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent14-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 14,
  },
  TEMPORA_PENT14_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT14_3",
    name: "Quarta-feira da 14ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent14-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 14,
  },
  TEMPORA_PENT14_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT14_4",
    name: "Quinta-feira da 14ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent14-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 14,
  },
  TEMPORA_PENT14_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT14_5",
    name: "Sexta-feira da 14ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent14-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 14,
  },
  TEMPORA_PENT14_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT14_6",
    name: "Sábado da 14ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent14-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 14,
  },
  TEMPORA_PENT15_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT15_0",
    name: "15º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent15-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 15,
  },
  TEMPORA_PENT15_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT15_1",
    name: "Segunda-feira da 15ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent15-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 15,
  },
  TEMPORA_PENT15_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT15_2",
    name: "Terça-feira da 15ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent15-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 15,
  },
  TEMPORA_PENT15_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT15_3",
    name: "Quarta-feira da 15ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent15-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 15,
  },
  TEMPORA_PENT15_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT15_4",
    name: "Quinta-feira da 15ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent15-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 15,
  },
  TEMPORA_PENT15_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT15_5",
    name: "Sexta-feira da 15ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent15-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 15,
  },
  TEMPORA_PENT15_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT15_6",
    name: "Sábado da 15ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent15-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 15,
  },
  TEMPORA_PENT16_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT16_0",
    name: "16º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent16-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 16,
  },
  TEMPORA_PENT16_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT16_1",
    name: "Segunda-feira da 16ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent16-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 16,
  },
  TEMPORA_PENT16_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT16_2",
    name: "Terça-feira da 16ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent16-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 16,
  },
  TEMPORA_PENT16_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT16_3",
    name: "Quarta-feira da 16ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent16-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 16,
  },
  TEMPORA_PENT16_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT16_4",
    name: "Quinta-feira da 16ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent16-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 16,
  },
  TEMPORA_PENT16_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT16_5",
    name: "Sexta-feira da 16ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent16-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 16,
  },
  TEMPORA_PENT16_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT16_6",
    name: "Sábado da 16ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent16-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 16,
  },
  TEMPORA_PENT17_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT17_0",
    name: "17º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent17-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 17,
  },
  TEMPORA_PENT17_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT17_1",
    name: "Segunda-feira da 17ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent17-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 17,
  },
  TEMPORA_PENT17_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT17_2",
    name: "Terça-feira da 17ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent17-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 17,
  },
  TEMPORA_PENT17_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT17_3",
    name: "Quarta-feira da 17ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent17-3",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 17,
  },
  TEMPORA_PENT_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT_3",
    name: "Quarta-feira das Têmporas de Setembro",
    rank: 2,
    color: "v",
    link: "missal/pentecostes/pent17-3",
    type: "ember-september",
    category: "pentecostes",
    weekday: 3,
  },
  TEMPORA_PENT17_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT17_4",
    name: "Quinta-feira da 17ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent17-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 17,
  },
  TEMPORA_PENT17_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT17_5",
    name: "Sexta-feira da 17ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent17-5",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 17,
  },
  TEMPORA_PENT_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT_5",
    name: "Sexta-feira das Têmporas de Setembro",
    rank: 2,
    color: "v",
    link: "missal/pentecostes/pent17-5",
    type: "ember-september",
    category: "pentecostes",
    weekday: 5,
  },
  TEMPORA_PENT17_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT17_6",
    name: "Sábado da 17ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent17-6",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 17,
  },
  TEMPORA_PENT_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT_6",
    name: "Sábado das Têmporas de Setembro",
    rank: 2,
    color: "v",
    link: "missal/pentecostes/pent17-6",
    type: "ember-september",
    category: "pentecostes",
    weekday: 6,
  },
  TEMPORA_PENT18_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT18_0",
    name: "18º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent18-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 18,
  },
  TEMPORA_PENT18_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT18_1",
    name: "Segunda-feira da 18ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent18-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 18,
  },
  TEMPORA_PENT18_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT18_2",
    name: "Terça-feira da 18ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent18-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 18,
  },
  TEMPORA_PENT18_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT18_3",
    name: "Quarta-feira da 18ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent18-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 18,
  },
  TEMPORA_PENT18_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT18_4",
    name: "Quinta-feira da 18ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent18-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 18,
  },
  TEMPORA_PENT18_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT18_5",
    name: "Sexta-feira da 18ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent18-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 18,
  },
  TEMPORA_PENT18_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT18_6",
    name: "Sábado da 18ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent18-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 18,
  },
  TEMPORA_PENT19_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT19_0",
    name: "19º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent19-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 19,
  },
  TEMPORA_PENT19_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT19_1",
    name: "Segunda-feira da 19ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent19-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 19,
  },
  TEMPORA_PENT19_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT19_2",
    name: "Terça-feira da 19ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent19-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 19,
  },
  TEMPORA_PENT19_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT19_3",
    name: "Quarta-feira da 19ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent19-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 19,
  },
  TEMPORA_PENT19_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT19_4",
    name: "Quinta-feira da 19ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent19-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 19,
  },
  TEMPORA_PENT19_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT19_5",
    name: "Sexta-feira da 19ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent19-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 19,
  },
  TEMPORA_PENT19_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT19_6",
    name: "Sábado da 19ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent19-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 19,
  },
  TEMPORA_PENT20_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT20_0",
    name: "20º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent20-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 20,
  },
  TEMPORA_PENT20_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT20_1",
    name: "Segunda-feira da 20ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent20-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 20,
  },
  TEMPORA_PENT20_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT20_2",
    name: "Terça-feira da 20ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent20-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 20,
  },
  TEMPORA_PENT20_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT20_3",
    name: "Quarta-feira da 20ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent20-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 20,
  },
  TEMPORA_PENT20_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT20_4",
    name: "Quinta-feira da 20ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent20-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 20,
  },
  TEMPORA_PENT20_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT20_5",
    name: "Sexta-feira da 20ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent20-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 20,
  },
  TEMPORA_PENT20_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT20_6",
    name: "Sábado da 20ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent20-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 20,
  },
  TEMPORA_PENT21_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT21_0",
    name: "21º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent21-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 21,
  },
  TEMPORA_PENT21_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT21_1",
    name: "Segunda-feira da 21ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent21-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 21,
  },
  TEMPORA_PENT21_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT21_2",
    name: "Terça-feira da 21ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent21-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 21,
  },
  TEMPORA_PENT21_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT21_3",
    name: "Quarta-feira da 21ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent21-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 21,
  },
  TEMPORA_PENT21_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT21_4",
    name: "Quinta-feira da 21ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent21-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 21,
  },
  TEMPORA_PENT21_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT21_5",
    name: "Sexta-feira da 21ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent21-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 21,
  },
  TEMPORA_PENT21_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT21_6",
    name: "Sábado da 21ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent21-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 21,
  },
  TEMPORA_PENT22_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT22_0",
    name: "22º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent22-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 22,
  },
  TEMPORA_PENT22_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT22_1",
    name: "Segunda-feira da 22ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent22-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 22,
  },
  TEMPORA_PENT22_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT22_2",
    name: "Terça-feira da 22ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent22-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 22,
  },
  TEMPORA_PENT22_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT22_3",
    name: "Quarta-feira da 22ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent22-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 22,
  },
  TEMPORA_PENT22_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT22_4",
    name: "Quinta-feira da 22ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent22-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 22,
  },
  TEMPORA_PENT22_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT22_5",
    name: "Sexta-feira da 22ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent22-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 22,
  },
  TEMPORA_PENT22_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT22_6",
    name: "Sábado da 22ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent22-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 22,
  },
  TEMPORA_PENT23_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT23_0",
    name: "23º Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent23-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 23,
  },
  TEMPORA_PENT23_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT23_1",
    name: "Segunda-feira da 23ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent23-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 23,
  },
  TEMPORA_PENT23_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT23_2",
    name: "Terça-feira da 23ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent23-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 23,
  },
  TEMPORA_PENT23_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT23_3",
    name: "Quarta-feira da 23ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent23-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 23,
  },
  TEMPORA_PENT23_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT23_4",
    name: "Quinta-feira da 23ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent23-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 23,
  },
  TEMPORA_PENT23_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT23_5",
    name: "Sexta-feira da 23ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent23-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 23,
  },
  TEMPORA_PENT23_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT23_6",
    name: "Sábado da 23ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent23-0",
    type: "pre-lent-to-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 23,
  },
  TEMPORA_PENTEPI3_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI3_0",
    name: "3º Domingo após a Epifania",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pentepi3-0",
    type: "pentepi",
    category: "epifania",
    weekday: 0,
    week: 3,
  },
  TEMPORA_PENTEPI3_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI3_1",
    name: "Segunda-feira da 3ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentiepi3-0",
    type: "pentepi",
    category: "epifania",
    weekday: 1,
    week: 3,
  },
  TEMPORA_PENTEPI3_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI3_2",
    name: "Terça-feira da 3ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi3-0",
    type: "pentepi",
    category: "epifania",
    weekday: 2,
    week: 3,
  },
  TEMPORA_PENTEPI3_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI3_3",
    name: "Quarta-feira da 3ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi3-0",
    type: "pentepi",
    category: "epifania",
    weekday: 3,
    week: 3,
  },
  TEMPORA_PENTEPI3_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI3_4",
    name: "Quinta-feira da 3ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi3-0",
    type: "pentepi",
    category: "epifania",
    weekday: 4,
    week: 3,
  },
  TEMPORA_PENTEPI3_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI3_5",
    name: "Sexta-feira da 3ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi3-0",
    type: "pentepi",
    category: "epifania",
    weekday: 5,
    week: 3,
  },
  TEMPORA_PENTEPI3_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI3_6",
    name: "Sábado da 3ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi3-0",
    type: "pentepi",
    category: "epifania",
    weekday: 6,
    week: 3,
  },
  TEMPORA_PENTEPI4_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI4_0",
    name: "4º Domingo após a Epifania",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pentepi4-0",
    type: "pentepi",
    category: "epifania",
    weekday: 0,
    week: 4,
  },
  TEMPORA_PENTEPI4_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI4_1",
    name: "Segunda-feira da 4ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi4-0",
    type: "pentepi",
    category: "epifania",
    weekday: 1,
    week: 4,
  },
  TEMPORA_PENTEPI4_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI4_2",
    name: "Terça-feira da 4ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi4-0",
    type: "pentepi",
    category: "epifania",
    weekday: 2,
    week: 4,
  },
  TEMPORA_PENTEPI4_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI4_3",
    name: "Quarta-feira da 4ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi4-0",
    type: "pentepi",
    category: "epifania",
    weekday: 3,
    week: 4,
  },
  TEMPORA_PENTEPI4_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI4_4",
    name: "Quinta-feira da 4ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi4-0",
    type: "pentepi",
    category: "epifania",
    weekday: 4,
    week: 4,
  },
  TEMPORA_PENTEPI4_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI4_5",
    name: "Sexta-feira da 4ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi4-0",
    type: "pentepi",
    category: "epifania",
    weekday: 5,
    week: 4,
  },
  TEMPORA_PENTEPI4_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI4_6",
    name: "Sábado da 4ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi4-0",
    type: "pentepi",
    category: "epifania",
    weekday: 6,
    week: 4,
  },
  TEMPORA_PENTEPI5_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI5_0",
    name: "5º Domingo após a Epifania",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pentepi5-0",
    type: "pentepi",
    category: "epifania",
    weekday: 0,
    week: 5,
  },
  TEMPORA_PENTEPI5_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI5_1",
    name: "Segunda-feira da 5ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi5-0",
    type: "pentepi",
    category: "epifania",
    weekday: 1,
    week: 5,
  },
  TEMPORA_PENTEPI5_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI5_2",
    name: "Terça-feira da 5ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi5-0",
    type: "pentepi",
    category: "epifania",
    weekday: 2,
    week: 5,
  },
  TEMPORA_PENTEPI5_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI5_3",
    name: "Quarta-feira da 5ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi5-0",
    type: "pentepi",
    category: "epifania",
    weekday: 3,
    week: 5,
  },
  TEMPORA_PENTEPI5_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI5_4",
    name: "Quinta-feira da 5ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi5-0",
    type: "pentepi",
    category: "epifania",
    weekday: 4,
    week: 5,
  },
  TEMPORA_PENTEPI5_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI5_5",
    name: "Sexta-feira da 5ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi5-0",
    type: "pentepi",
    category: "epifania",
    weekday: 5,
    week: 5,
  },
  TEMPORA_PENTEPI5_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI5_6",
    name: "Sábado da 5ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi5-0",
    type: "pentepi",
    category: "epifania",
    weekday: 6,
    week: 5,
  },
  TEMPORA_PENTEPI6_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI6_0",
    name: "6º Domingo após a Epifania",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pentepi6-0",
    type: "pentepi",
    category: "epifania",
    weekday: 0,
    week: 6,
  },
  TEMPORA_PENTEPI6_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI6_1",
    name: "Segunda-feira da 6ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi6-0",
    type: "pentepi",
    category: "epifania",
    weekday: 1,
    week: 6,
  },
  TEMPORA_PENTEPI6_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI6_2",
    name: "Terça-feira da 6ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi6-0",
    type: "pentepi",
    category: "epifania",
    weekday: 2,
    week: 6,
  },
  TEMPORA_PENTEPI6_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI6_3",
    name: "Quarta-feira da 6ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi6-0",
    type: "pentepi",
    category: "epifania",
    weekday: 3,
    week: 6,
  },
  TEMPORA_PENTEPI6_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI6_4",
    name: "Quinta-feira da 6ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi6-0",
    type: "pentepi",
    category: "epifania",
    weekday: 4,
    week: 6,
  },
  TEMPORA_PENTEPI6_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI6_5",
    name: "Sexta-feira da 6ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi6-0",
    type: "pentepi",
    category: "epifania",
    weekday: 5,
    week: 6,
  },
  TEMPORA_PENTEPI6_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENTEPI6_6",
    name: "Sábado da 6ª semana após a Epifania",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pentepi6-0",
    type: "pentepi",
    category: "epifania",
    weekday: 6,
    week: 6,
  },
  TEMPORA_PENT24_0: {
    flexibility: "tempora",
    id: "TEMPORA_PENT24_0",
    name: "24 Domingo depois de Pentecostes",
    rank: 2,
    color: "g",
    link: "missal/pentecostes/pent24-0",
    // Semiduplex Sunday (DA); every Sunday is II class under Rubrics
    // 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex", precedence: 5 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "week-24-after-pentcost",
    category: "pentecostes",
    weekday: 0,
    week: 24,
  },
  TEMPORA_PENT24_1: {
    flexibility: "tempora",
    id: "TEMPORA_PENT24_1",
    name: "Segunda-feira da 24ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent24-0",
    type: "week-24-after-pentcost",
    category: "pentecostes",
    weekday: 1,
    week: 24,
  },
  TEMPORA_PENT24_2: {
    flexibility: "tempora",
    id: "TEMPORA_PENT24_2",
    name: "Terça-feira da 24ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent24-0",
    type: "week-24-after-pentcost",
    category: "pentecostes",
    weekday: 2,
    week: 24,
  },
  TEMPORA_PENT24_3: {
    flexibility: "tempora",
    id: "TEMPORA_PENT24_3",
    name: "Quarta-feira da 24ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent24-0",
    type: "week-24-after-pentcost",
    category: "pentecostes",
    weekday: 3,
    week: 24,
  },
  TEMPORA_PENT24_4: {
    flexibility: "tempora",
    id: "TEMPORA_PENT24_4",
    name: "Quinta-feira da 24ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent24-0",
    type: "week-24-after-pentcost",
    category: "pentecostes",
    weekday: 4,
    week: 24,
  },
  TEMPORA_PENT24_5: {
    flexibility: "tempora",
    id: "TEMPORA_PENT24_5",
    name: "Sexta-feira da 24ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent24-0",
    type: "week-24-after-pentcost",
    category: "pentecostes",
    weekday: 5,
    week: 24,
  },
  TEMPORA_PENT24_6: {
    flexibility: "tempora",
    id: "TEMPORA_PENT24_6",
    name: "Sábado da 24ª semana depois de Pentecostes",
    rank: 4,
    color: "g",
    link: "missal/pentecostes/pent24-0",
    type: "week-24-after-pentcost",
    category: "pentecostes",
    weekday: 6,
    week: 24,
  },
};
