import type { MassMap } from "../../domain";

/** Temporas da Septuagésima e da Quaresma. */
export const TEMPORA_QUARESMA: MassMap = {
  TEMPORA_QUADP1_0: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP1_0",
    name: "Domingo da Septuagésima",
    rank: 2,
    color: "v",
    link: "missal/pre-quaresma/quadp1-0",
    // Privileged semiduplex Sunday (DA); every Sunday is II class under
    // Rubrics 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex privilegiatum", precedence: 6.9 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 0,
    week: 1,
  },
  TEMPORA_QUADP1_1: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP1_1",
    name: "Segunda-feira da semana da Septuagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp1-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 1,
    week: 1,
  },
  TEMPORA_QUADP1_2: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP1_2",
    name: "Terça-feira da semana da Septuagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp1-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 2,
    week: 1,
  },
  TEMPORA_QUADP1_3: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP1_3",
    name: "Quarta-feira da semana da Septuagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp1-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 3,
    week: 1,
  },
  TEMPORA_QUADP1_4: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP1_4",
    name: "Quinta-feira da semana da Septuagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp1-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 4,
    week: 1,
  },
  TEMPORA_QUADP1_5: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP1_5",
    name: "Sexta-feira da semana da Septuagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp1-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 5,
    week: 1,
  },
  TEMPORA_QUADP1_6: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP1_6",
    name: "Sábado da semana da Septuagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp1-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 6,
    week: 1,
  },
  TEMPORA_QUADP2_0: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP2_0",
    name: "Domingo da Sexagésima",
    rank: 2,
    color: "v",
    link: "missal/pre-quaresma/quadp2-0",
    // Privileged semiduplex Sunday (DA); every Sunday is II class under
    // Rubrics 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex privilegiatum", precedence: 6.9 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 0,
    week: 2,
  },
  TEMPORA_QUADP2_1: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP2_1",
    name: "Segunda-feira da semana da Sexagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp2-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 1,
    week: 2,
  },
  TEMPORA_QUADP2_2: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP2_2",
    name: "Terça-feira da semana da Sexagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp2-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 2,
    week: 2,
  },
  TEMPORA_QUADP2_3: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP2_3",
    name: "Quarta-feira da semana da Sexagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp2-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 3,
    week: 2,
  },
  TEMPORA_QUADP2_4: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP2_4",
    name: "Quinta-feira da semana da Sexagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp2-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 4,
    week: 2,
  },
  TEMPORA_QUADP2_5: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP2_5",
    name: "Sexta-feira da semana da Sexagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp2-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 5,
    week: 2,
  },
  TEMPORA_QUADP2_6: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP2_6",
    name: "Sábado da semana da Sexagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp2-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 6,
    week: 2,
  },
  TEMPORA_QUADP3_0: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP3_0",
    name: "Domingo da Quinquagésima",
    rank: 2,
    color: "v",
    link: "missal/pre-quaresma/quadp3-0",
    // Privileged semiduplex Sunday (DA); every Sunday is II class under
    // Rubrics 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex privilegiatum", precedence: 6.9 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 0,
    week: 3,
  },
  TEMPORA_QUADP3_1: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP3_1",
    name: "Segunda-feira da semana da Quinquagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp3-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 1,
    week: 3,
  },
  TEMPORA_QUADP3_2: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP3_2",
    name: "Terça-feira da semana da Quinquagésima",
    rank: 4,
    color: "v",
    link: "missal/pre-quaresma/quadp3-0",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 2,
    week: 3,
  },
  TEMPORA_QUADP3_3: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP3_3",
    name: "Quarta-feira de Cinzas",
    rank: 1,
    color: "v",
    link: "missal/pre-quaresma/quadp3-3",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 3,
    week: 3,
  },
  TEMPORA_QUADP3_4: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP3_4",
    name: "Quinta-feira depois das Cinzas",
    rank: 3,
    color: "v",
    link: "missal/pre-quaresma/quadp3-4",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 4,
    week: 3,
  },
  TEMPORA_QUADP3_5: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP3_5",
    name: "Sexta-feira depois das Cinzas",
    rank: 3,
    color: "v",
    link: "missal/pre-quaresma/quadp3-5",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 5,
    week: 3,
  },
  TEMPORA_QUADP3_6: {
    flexibility: "tempora",
    id: "TEMPORA_QUADP3_6",
    name: "Sábado depois das Cinzas",
    rank: 3,
    color: "v",
    link: "missal/pre-quaresma/quadp3-6",
    type: "pre-lent-to-pentcost",
    category: "pre-quaresma",
    weekday: 6,
    week: 3,
  },
  TEMPORA_QUAD1_0: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD1_0",
    name: "1º Domingo da Quaresma",
    rank: 1,
    color: "v",
    link: "missal/quaresma/quad1-0",
    // Privileged semiduplex Sunday (DA); every Sunday is II class under
    // Rubrics 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex privilegiatum", precedence: 6.9 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 0,
    week: 1,
  },
  TEMPORA_QUAD1_1: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD1_1",
    name: "Segunda-feira da 1ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad1-1",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 1,
    week: 1,
  },
  TEMPORA_QUAD1_2: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD1_2",
    name: "Terça-feira da 1ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad1-2",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 2,
    week: 1,
  },
  TEMPORA_QUAD1_3: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD1_3",
    name: "Quarta-feira da 1ª Semana da Quaresma, Têmporas da Primavera",
    rank: 2,
    color: "v",
    link: "missal/quaresma/quad1-3",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 3,
    week: 1,
  },
  TEMPORA_QUAD1_4: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD1_4",
    name: "Quinta-feira da 1ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad1-4",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 4,
    week: 1,
  },
  TEMPORA_QUAD1_5: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD1_5",
    name: "Sexta-feira 1ª semana da Quaresma, Têmporas da Primavera",
    rank: 2,
    color: "v",
    link: "missal/quaresma/quad1-5",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 5,
    week: 1,
  },
  TEMPORA_QUAD1_6: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD1_6",
    name: "Sábado da 1ª semana da Quaresma, Têmporas da Primavera",
    rank: 2,
    color: "v",
    link: "missal/quaresma/quad1-6",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 6,
    week: 1,
  },
  TEMPORA_QUAD2_0: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD2_0",
    name: "2º Domingo da Quaresma",
    rank: 1,
    color: "v",
    link: "missal/quaresma/quad2-0",
    // Privileged semiduplex Sunday (DA); every Sunday is II class under
    // Rubrics 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex privilegiatum", precedence: 6.9 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 0,
    week: 2,
  },
  TEMPORA_QUAD2_1: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD2_1",
    name: "Segunda-feira da 2ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad2-1",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 1,
    week: 2,
  },
  TEMPORA_QUAD2_2: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD2_2",
    name: "Terça-feira da 2ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad2-2",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 2,
    week: 2,
  },
  TEMPORA_QUAD2_3: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD2_3",
    name: "Quarta-feira da 2ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad2-3",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 3,
    week: 2,
  },
  TEMPORA_QUAD2_4: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD2_4",
    name: "Quinta-feira da 2ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad2-4",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 4,
    week: 2,
  },
  TEMPORA_QUAD2_5: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD2_5",
    name: "Sexta-feira da 2ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad2-5",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 5,
    week: 2,
  },
  TEMPORA_QUAD2_6: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD2_6",
    name: "Sábado da 2ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad2-6",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 6,
    week: 2,
  },
  TEMPORA_QUAD3_0: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD3_0",
    name: "3º Domingo da Quaresma",
    rank: 1,
    color: "v",
    link: "missal/quaresma/quad3-0",
    // Privileged semiduplex Sunday (DA); every Sunday is II class under
    // Rubrics 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex privilegiatum", precedence: 6.9 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 0,
    week: 3,
  },
  TEMPORA_QUAD3_1: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD3_1",
    name: "Segunda-feira da 3ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad3-1",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 1,
    week: 3,
  },
  TEMPORA_QUAD3_2: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD3_2",
    name: "Terça-feira da 3ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad3-2",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 2,
    week: 3,
  },
  TEMPORA_QUAD3_3: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD3_3",
    name: "Quarta-feira da 3ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad3-3",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 3,
    week: 3,
  },
  TEMPORA_QUAD3_4: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD3_4",
    name: "Quinta-feira da 3ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad3-4",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 4,
    week: 3,
  },
  TEMPORA_QUAD3_5: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD3_5",
    name: "Sexta-feira da 3ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad3-5",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 5,
    week: 3,
  },
  TEMPORA_QUAD3_6: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD3_6",
    name: "Sábado da 3ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad3-6",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 6,
    week: 3,
  },
  TEMPORA_QUAD4_0: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD4_0",
    name: "4º Domingo da Quaresma",
    rank: 1,
    color: "v",
    link: "missal/quaresma/quad4-0",
    // Privileged semiduplex Sunday (DA); every Sunday is II class under
    // Rubrics 1960 - divinum-officium Tempora/[Rank], applied per era.
    rankVariants: [
      { rubrics: "*", name: "Semiduplex privilegiatum", precedence: 6.9 },
      { rubrics: "Rubrics 1960 - 1960", name: "Dominica II classis", precedence: 5.1 },
    ],
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 0,
    week: 4,
  },
  TEMPORA_QUAD4_1: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD4_1",
    name: "Segunda-feira da 4ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad4-1",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 1,
    week: 4,
  },
  TEMPORA_QUAD4_2: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD4_2",
    name: "Terça-feira da 4ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad4-2",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 2,
    week: 4,
  },
  TEMPORA_QUAD4_3: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD4_3",
    name: "Quarta-feira da 4ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad4-3",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 3,
    week: 4,
  },
  TEMPORA_QUAD4_4: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD4_4",
    name: "Quinta-feira da 4ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad4-4",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 4,
    week: 4,
  },
  TEMPORA_QUAD4_5: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD4_5",
    name: "Sexta-feira da 4ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad4-5",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 5,
    week: 4,
  },
  TEMPORA_QUAD4_6: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD4_6",
    name: "Sábado da 4ª semana da Quaresma",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad4-6",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 6,
    week: 4,
  },
  TEMPORA_QUAD5_0: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD5_0",
    name: "Domingo da Paixão",
    rank: 1,
    color: "v",
    link: "missal/quaresma/quad5-0",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 0,
    week: 5,
  },
  TEMPORA_QUAD5_1: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD5_1",
    name: "Segunda-feira da semana da Paixão",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad5-1",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 1,
    week: 5,
  },
  TEMPORA_QUAD5_2: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD5_2",
    name: "Terça-feira da semana da Paixão",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad5-2",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 2,
    week: 5,
  },
  TEMPORA_QUAD5_3: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD5_3",
    name: "Quarta-feira da semana da Paixão",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad5-3",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 3,
    week: 5,
  },
  TEMPORA_QUAD5_4: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD5_4",
    name: "Quinta-feira da semana da Paixão",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad5-4",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 4,
    week: 5,
  },
  TEMPORA_QUAD5_5: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD5_5",
    name: "Sexta-feira da semana da Paixão",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad5-5",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 5,
    week: 5,
  },
  TEMPORA_QUAD5_6: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD5_6",
    name: "Sábado da semana da Paixão",
    rank: 3,
    color: "v",
    link: "missal/quaresma/quad5-6",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 6,
    week: 5,
  },
  TEMPORA_QUAD6_0: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD6_0",
    name: "Domingo de Ramos",
    rank: 1,
    color: "v",
    link: "missal/quaresma/quad6-0",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 0,
    week: 6,
  },
  TEMPORA_QUAD6_1: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD6_1",
    name: "Segunda-feira Santa",
    rank: 1,
    color: "v",
    link: "missal/quaresma/quad6-1",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 1,
    week: 6,
  },
  TEMPORA_QUAD6_2: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD6_2",
    name: "Terça-feira Santa",
    rank: 1,
    color: "v",
    link: "missal/quaresma/quad6-2",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 2,
    week: 6,
  },
  TEMPORA_QUAD6_3: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD6_3",
    name: "Quarta-feira Santa",
    rank: 1,
    color: "v",
    link: "missal/quaresma/quad6-3",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 3,
    week: 6,
  },
  TEMPORA_QUAD6_4: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD6_4",
    name: "Quinta-feira Santa",
    rank: 1,
    color: "w",
    link: "missal/quaresma/quad6-4",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 4,
    week: 6,
  },
  TEMPORA_QUAD6_5: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD6_5",
    name: "Sexta-feira Santa",
    rank: 1,
    color: "b",
    link: "missal/quaresma/quad6-5",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 5,
    week: 6,
  },
  TEMPORA_QUAD6_6: {
    flexibility: "tempora",
    id: "TEMPORA_QUAD6_6",
    name: "Sábado Santo",
    rank: 1,
    color: "vw",
    link: "missal/quaresma/quad6-6",
    type: "pre-lent-to-pentcost",
    category: "quaresma",
    weekday: 6,
    week: 6,
  },
};
