name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "18"
      - run: npm ci
      - run: npm test
