name: CI

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  FORCE_COLOR: 3

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - shell: bash
        run: pnpm add -g turbo

      - shell: bash
        run: pnpm install

      - name: Lint
        run: pnpm lint && pnpm lint:ws

      - name: Format
        run: pnpm format

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test
