name: merge

on:
  push:
    branches:
      - master

jobs:
  deploy-mobile:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: "🔸 Update Expo App"
        working-directory: apps/expo
        run: eas build --auto-submit --platform=android --profile=preview
