name: merge

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: "🔧 Build"
        working-directory: apps/astro
        run: pnpm run build
      - name: "🔸 Cloudflare Workers - Deploy 🚀"
        working-directory: apps/astro
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpx wrangler pages deploy dist --project-name tesourofieis
