name: merge

on:
  push:
    branches:
      - master

jobs:
  deploy-web:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: "🔧 Build"
        working-directory: apps/astro
        run: pnpm run build
      - name: "🔸 Cloudflare Workers - Deploy 🚀"
        working-directory: apps/astro
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: bunx wrangler pages deploy dist --project-name tesourofieis

  deploy-mobile:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: "🔸 Attempt EAS Update"
        id: eas-update
        working-directory: apps/expo
        run: eas update --auto
        continue-on-error: true
      - name: "🔸 EAS Build (if update failed)"
        if: steps.eas-update.outcome == 'failure'
        working-directory: apps/expo
        run: eas build --platform all --auto-submit --profile production --non-interactive --no-wait
