name: merge

on:
  push:
    branches:
      - master

jobs:
  update:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🏗️ Setup repo
        uses: actions/checkout@v4
      - name: 🏗️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 🏗️ Install
        run: npm install --prefer-offline

      - name: "🔸 Update Expo App"
        run: npx eas-cli --platform ios --platform android --non-interactive
