name: On pull request

on:
  pull_request:
    branches:
      - master

jobs:
  test-unit:
    name: Test unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "18"
      - run: npm ci
      - run: npm test
      - run: npm run bench

  test-e2e:
    needs: test-unit
    name: End to end
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
