name: On pull request

on:
  pull_request:
    branches:
      - master

jobs:
  test-unit:
    name: Test unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun test
      - run: bun bench

  test-e2e:
    needs: test-unit
    name: End to end
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Install Chromium
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npx playwright test
