name: On pull request

on:
  pull_request:
    branches:
      - master

permissions:
  pull-requests: write

jobs:
  test-unit:
    name: Test unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run bench
      - run: bun run test
      - run: bun run coverage
      - uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage/coverage-summary.json

  test-e2e:
    name: End to end
    needs: test-unit
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Install Chromium
        run: bunx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: bunx playwright test

  deploy:
    name: Deploy
    needs: test-e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --project-name=tesourofieis
          packageManager: bun
